### ISSUE TITLE
Does Octodash have Python 3 Support?

### ISSUE THREAD

**Issue by pilotw7** [UnchartedBull/OctoDash#1004]
Not sure if this is under the right header, or if it matters much, but does Octodash have Python 3 compatability? With Python 2 being EoL now and Octoprint moving onto Python 3 with the next update.

**Comment by gdachs** [comment]
It has no Python 3 support. It has no Python 2.X support either. It doesn't use Python at all.

**Comment by UnchartedBull** [comment]
OctoDash doesn't care at all what version of Python your OctoPrint instance is running on :)
