### ISSUE TITLE
White Box when touching

### ISSUE THREAD

**Issue by scorer21** [UnchartedBull/OctoDash#1016]
When touching the screen I see a white box where I touch, but the button doesn't actually activate. The box can be dragged arround when holding the touchscreen. Click only works after severeal tries.

![whitebox](https://user-images.githubusercontent.com/38925096/94290385-67183280-ff5a-11ea-979d-b66b295e2b5f.jpg)

**Comment by UnchartedBull** [comment]
Please provide more info (OS version, touchscreen, other libraries, fresh install?, ...)

**Comment by scorer21** [comment]
- OctoPrint 1.4.2 
- Python 3.7.3 
- OctoPi 0.17.0
- Raspian Buster (Octoprint Image - relatively fresh install)
- Touchscreen:
![81VntSOynPL _AC_SL1500_](https://user-images.githubusercontent.com/38925096/94460880-a8f2e400-01b9-11eb-838d-8314daec5d8c.jpg)

I found a fix you provided on another forum for exact the same problem. Tried it out, fixed the problem but it slowed down the interface tremendously. Reverted back to the latest official version (which is fast and responsive).

**Comment by TheNeskik** [comment]
What was your first solution ?
Are you using the latest official release of Octodash or a personnal build ?

**Comment by scorer21** [comment]
I used the version @UnchartedBull provided in issue #838 . This solved the problem with the white box but unfortunately I then had the problem of a very unresponisve interface which was very laggy. I then reverted back to the latest official version.

**Comment by UnchartedBull** [comment]
Closing this here now, since the white box is gone. I created a new issue for the sluggish interface: #1062.
