### ISSUE TITLE
Can't install octodash on ubuntu server

### ISSUE THREAD

**Issue by bepstein111** [UnchartedBull/OctoDash#1017]
**What doesn't work?**
Using the install script fails with `Package gir1.2-gnomekeyring-1.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source`

**What did you already try?**
Just tried installing. Also tried the info given on the wiki page about installation (manually installing dependencies etc), and all the dependencies installed fine except the one mentioned above. When I went to look for a .deb for it, I was able to install it but it gave me `gir1.2-gnomekeyring-1.0 depends on libgnome-keyring0 (= 3.12.0-1+b1); however:
  Package libgnome-keyring0 is not installed.` and I wasn't about to go on a dependency hunt.

**General Information:**
 - Ryzen 2700X build with an olllllddd 8400GS
 - Ubuntu Server 20.04
 - OctoDash Version [latest]
 - OctoPrint Version [latest]

**Additional context**
I had octoscreen installed before, but I uninstalled/purged it before trying to install this.

**Comment by carl1961** [comment]
i have same error on Debian 10. funny last week i installed it . been working on orange pi , so lots of reinstalling, testing. every where i read it has been removed

**Comment by UnchartedBull** [comment]
Dependency has been removed. Please try again after the PR is merged.
