### ISSUE TITLE
Update filament manager plugin

### ISSUE THREAD

**Issue by zaphod82** [UnchartedBull/OctoDash#1019]
Filament manager that is installed with the install script is abandoned.

Seems to be statically set to the older maintainers github.  Can you please update it to pull from https://github.com/OllisGit/OctoPrint-FilamentManager

This is the one that is referenced at https://plugins.octoprint.org/plugins/filamentmanager/ now.

**Comment by UnchartedBull** [comment]
Great catch, thanks!
