### ISSUE TITLE
Print preview displays inside progress ring

### ISSUE THREAD

**Issue by tusing** [UnchartedBull/OctoDash#1020]
**Describe the bug**

The print preview displays inside the progress ring instead of replacing it, which looks fairly ugly (as the preview is square and the ring is circular). The preview should replace the ring altogether, or the progress ring should instead become a progress bar and display under the preview image.

**To Reproduce**

Enable print preview for your Prusa printer: add `thumbnails = 16x16,256x256` to your config.ini.

**Expected behavior**

As shown in the image in the README, the preview should replace the ring as shown here:

![file_loaded](https://user-images.githubusercontent.com/1077203/94319160-ea2b8f80-ff3e-11ea-9e19-68da0a82d155.png)

**Screenshots**

![IMG_2523](https://user-images.githubusercontent.com/1077203/94319193-fadc0580-ff3e-11ea-8eaf-34bbb5d52b2a.jpg)

**General Information:**
- Prusa MK3S
- Raspberry Pi 4 w/ Hyperpixel 4 (800x480) running Raspbian

**Comment by UnchartedBull** [comment]
I'll merge this with #749 to clean up the issues a litte. Good idea to have a normal progress bar so the preview could be a bit bigger, will be included in one of the next releases.
