### ISSUE TITLE
[FR] Camera View

### ISSUE THREAD

**Issue by dcwalmsley** [UnchartedBull/OctoDash#1021]
Request a menu option to allow video to be displayed on touch screen to aid in aiming and focusing camera prior to starting a print.  

Not looking for anything more than a view screen.

Thanks,

Doug W

**Comment by UnchartedBull** [comment]
Already possible with Custom Actions & iFrames (just put in your webcam URL there): https://github.com/UnchartedBull/OctoDash/wiki/Custom-Actions#predefined-actions. More advanced stream will be tracked in #918.
