### ISSUE TITLE
Percentage is diffrent.

### ISSUE THREAD

**Issue by bchilton9** [UnchartedBull/OctoDash#1023]
Im not sure if there is a setting im missing or not. Octodash shows about 15% less then the webUI (Octopod on my phone shows 10% less too). Im thinking it might be print time genius adds the pre heat into the progress done but im not sure. Is there a way to sync them to the same percent? I dont care if the pre heat time is in there or not i would just like my screens to be in sync. Thank you.

**Comment by UnchartedBull** [comment]
OctoDash currently uses the file position for percentage calculations (default from OctoPrint). PTG somehow only replaces the numbers in the UI (now with time remaining) and not in the API, thus there could be a difference. I'll have a look and check whether I can get the PTG time somewhere :)

**Comment by KapJI** [comment]
For anyone who finds this issue:

You can install https://github.com/celogeek/OctoPrint-ProgressBasedOnTime plugin to make octoprint to report more accurate percentage.
