### ISSUE TITLE
Keep getting error "Can't retrieve layer progress!"

### ISSUE THREAD

**Issue by chilipeppr** [UnchartedBull/OctoDash#1040]
The bug I'm seeing is this:

![image](https://user-images.githubusercontent.com/7904621/95050604-b2d88380-06a0-11eb-9d1a-09ca3a49147f.png)

I just installed this on a Raspi4 tonight. Ran the standard install script. The app is working fine and in fact when it first came up I was not seeing this error. After a reboot I'm seeing this.

Here is the other error it shows. It toggles back and forth between this and "Can't retrieve printer status"
![image](https://user-images.githubusercontent.com/7904621/95050822-0d71df80-06a1-11eb-8f2c-cd37b9ae0535.png)

**General Information:**
 - Raspi4
 - OctoPrint version : 1.4.2
 - OctoPi version    : 0.17.0

**Comment by UnchartedBull** [comment]
Your URL isn't right. Please double check (either via UI or config file). If you don't know what is wrong with the URL please post it here.

**Comment by chilipeppr** [comment]
I have it set to localhost without any port specified as I'm running OctoPrint on port 80 like the defaut SD card install of OctoPrint runs on.

Here's my current setting. Keep in mind I connect to OctoPrint on this Raspi just fine.
![image](https://user-images.githubusercontent.com/7904621/95125569-04692880-070a-11eb-8051-d825f627be9b.png)

Even when I try the direct IP, which is what I type into my browser from my laptop to get to OctoPrint, that fails the same way:
![image](https://user-images.githubusercontent.com/7904621/95125688-2fec1300-070a-11eb-985c-bc9b24713714.png)

Even tried doing loopback IP, but fails same way.
![image](https://user-images.githubusercontent.com/7904621/95125717-3d090200-070a-11eb-9a1b-1254ba96b723.png)

Here I am connected in my browser just fine to 10.0.0.202.
![image](https://user-images.githubusercontent.com/7904621/95125782-4eeaa500-070a-11eb-8678-3033a5431377.png)

**Comment by TheNeskik** [comment]
I'm running the same configuration as you, and I need to put it on port 5000. Give it a try :)
If it doesn't work, you can try to put it on port 80. 
In your pictures we don't see any port.

**Comment by chilipeppr** [comment]
Yeah, that worked. Wow, I could have sworn I tried that at the beginning during the setup wizard and it failed until I finally thought to delete the port number thinking it would presume port 80, which it did, and then all was working. Perhaps it was always using port 5000 in the background and after reboot it finally started to use the empty value and that's why it failed?

Ok, thank you. 

![image](https://user-images.githubusercontent.com/7904621/95170069-b9323280-0768-11eb-90cc-b44e86ad1a8b.png)

**Comment by UnchartedBull** [comment]
Great that you got it working! The setup will be simplified with the next release, so you don't need to worry about ips and ports anymore :)

**Comment by berteding** [comment]
I have the same problem. 
I tried to set the port to 5000, now i get Connection to Octoprint timed out.
And I can no longer access the settings because it keeps trying to connect end then times out.
Is there a configuration file where the settings are stored?

**Comment by UnchartedBull** [comment]
https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings#manually-adjusting-the-settings

**Comment by nicwilson58** [comment]
> I'm running the same configuration as you, and I need to put it on port 5000. Give it a try :)
> If it doesn't work, you can try to put it on port 80.
> In your pictures we don't see any port.

I have this exact issue, I cannot change anything on the Pi screen as this error box keeps popping up over the top of the UI making it impossible to enter anything,  where else can I try setting these changes?  i looked at the setup link above but could not find anything there either?

**Comment by berteding** [comment]
It must be 127.0.0.1:5000, so changing only the port-number does not work and causes a hangup.

**Comment by Cordero808** [comment]
I am still getting this error and i have the address and port set

**Comment by JeremyProffitt** [comment]
This seems to be undocumented, but DisplayLayerProgress Plugin MUST be installed.

**Comment by Cordero808** [comment]
Sorry issue is resolved after I reinstalled.  Thankyou!!
