### ISSUE TITLE
Filament Loading/Unloading doesn't work correctly

### ISSUE THREAD

**Issue by davide-molino** [UnchartedBull/OctoDash#1050]
I've modified the config.json file to put the right feed lenght and the desired speed. The config is accepted because the values change in the dashboard... but the speed remain the same. I want to load/unload with an higher speed but also with the dashboard displaying, for example, 100 mm/s it always works at 30 mm/s. How can I fix this issue?

{
	"config": {
		"octoprint": {
			"url": "http://localhost:5000/api/",
			"accessToken": "..."
		},
		"printer": {
			"name": "i3 Mega-S",
			"xySpeed": 150,
			"zSpeed": 5,
			"defaultTemperatureFanSpeed": {
				"hotend": 190,
				"heatbed": 50,
				"fan": 75
			}
		},
		"filament": {
			"thickness": 1.75,
			"density": 1.25,
			"feedLength": 530,
			"feedSpeed": 100,
			"feedSpeedSlow": 80,
			"purgeDistance": 20,
			"useM600": false
		},
		"plugins": {
			"displayLayerProgress": {
				"enabled": true
			},
			"enclosure": {
				"enabled": false,
				"ambientSensorID": null,
				"filament1SensorID": null,
				"filament2SensorID": null
			},
			"filamentManager": {
				"enabled": true
			},
			"preheatButton": {
				"enabled": true
			},
			"printTimeGenius": {
				"enabled": true
			},
			"psuControl": {
				"enabled": false,
				"turnOnPSUWhenExitingSleep": false
			}
		},
		"octodash": {
			"customActions": [
				{
					"icon": "home",
					"command": "G28",
					"color": "#dcdde1",
					"confirm": false,
					"exit": false
				},
				{
					"icon": "snowflake",
					"command": "M140 S0; M104 S0",
					"color": "#4cd137",
					"confirm": false,
					"exit": true
				},
				{
					"icon": "moon",
					"command": "RESPOND TYPE=command MSG=action:bl25",
					"color": "#00a8ff",
					"confirm": false,
					"exit": false
				},
				{
					"icon": "sun",
					"command": "RESPOND TYPE=command MSG=action:bl100",
					"color": "#e1b12c",
					"confirm": false,
					"exit": false
				},
				{
					"icon": "network-wired",
					"command": "RESPOND TYPE=command MSG=action:set_ip",
					"color": "#7f8fa6",
					"confirm": false,
					"exit": false
				},
				{
					"icon": "cogs",
					"command": "M84",
					"color": "#e84118",
					"confirm": false,
					"exit": false
				}
			],
			"fileSorting": {
				"attribute": "name",
				"order": "asc"
			},
			"pollingInterval": 1500,
			"touchscreen": true,
			"turnScreenOffWhileSleeping": true,
			"preferPreviewWhilePrinting": false
		}
	}
}

**Comment by UnchartedBull** [comment]
I guess you figured out by yourself that you need to update your printer profile :). I added a section for that to the troubleshooting guide: https://github.com/UnchartedBull/OctoDash/wiki/Troubleshooting#filament-change-is-slower-than-specified-in-configuration and updated the explanation a little to make this more clear: https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings#feed-speed

**Comment by davide-molino** [comment]
exactly... problem solved. Thank you for answering my question... Octodash is adorable
