### ISSUE TITLE
Slow performance with Electron 10

### ISSUE THREAD

**Issue by UnchartedBull** [UnchartedBull/OctoDash#1062]
touchscreen seems to be noticeably slower after https://github.com/UnchartedBull/OctoDash/commit/a1577089c3515d3c294acbc69eca595f20c70fd0. 

* Could be linked to *::before and *::after selectors.
* Seems to be better while printing, which would support the pseudo-selector thesis, since there are less elements present while printing.

**Comment by UnchartedBull** [comment]
traced back to Electron 10 upgrade. Current master runs fine with Electron 9. Needs further investigation.

**Comment by TheNeskik** [comment]
Could it be linked to Hardware Acceleration ?

I'll try this weekend to add
`app.disableHardwareAcceleration();`
to main.js

(Post this comment here as a remember for me)

**Comment by UnchartedBull** [comment]
Can be, I just tried another dev build the other day and enabled the Fake KMS OpenGL driver for the Raspberry (which in fact enables GPU accelerated CSS). The performance was still sup-bar and probably a little worse than Electron 9 with no Hardware Acceleration. Electron 9 with hardware accelerated CSS was butter-smooth, so I think there is something else going on. But I never tried to disableHardwareAcceleration from Electron directly because it does give a notable performance improvement with the CSS animations.

**Comment by UnchartedBull** [comment]
I found a few more things which could be the cause of this issue:

- **browserWindow.backgroundThrottling** might be something to look into (set to false)
- **browserWindow.webgl** Raspberry doesn't support WebGL out of the box, so disabling this might be worth a try as well
- try building with a higher version of node, this probably won't have any effect whatsoever but it is worth a try. I'm currently building everything with 12.16.1, while Electron 10 uses 12.16.3. So trying to build everything with 15 might be something to try.

Those three points probably won't do much, but I wanted to write them down somewhere and they might be worth a try.

**Comment by Vamoss** [comment]
> Could it be linked to Hardware Acceleration ?
> 
> I'll try this weekend to add `app.disableHardwareAcceleration();` to main.js
> 
> (Post this comment here as a remember for me)

This saved me hooooours of work trying to figure out why my application was so slow when running on touchscreen.
Thank you!
