### ISSUE TITLE
Settings SAVE blanks screen and won't respond

### ISSUE THREAD

**Issue by M1dn1ghtN1nj4** [UnchartedBull/OctoDash#1071]
**Describe the bug**
When hitting SAVE in the settings menu, the screen goes blank and is unresponsive.

**To Reproduce**
1. Go into Settings
2. Hit SAVE
3. Witness bug

**Expected behavior**
Should return to the main screen

**General Information:**
 - Raspi 4B
 - OctoPi: 0.18.0
 - OctoPrint Version: 1.4.2
 - OctoDash Version: Build as of 10-11-2020

**Comment by komandrik** [comment]
I confirm. I get the same problem after updating to version 2.0.1 of Raspberry Pi 3B +

**Comment by UnchartedBull** [comment]
Will release V2.1.1 soonish to fix this.

**Comment by M1dn1ghtN1nj4** [comment]
I'm having a lot of issues recently with DisplayLayerProgress/values not
being recognized by OctoDash.  404 errors.  Now, I'm also unable to get
DisplayLayerProgress to actually install.  I'm not entirely sure what's
going on here.  Still working on a few things, but I feel like I'm running
in circles.  Has that plugin been giving you any grief?  Or is it just me?

**Comment by UnchartedBull** [comment]
Lots of issues piling up regarding DLP atm again. Working on switching over to websockets, this way DLP ignores can just be ignored. Olli did publish an update 1.15.2 which is supposed to fix some issues though.
