### ISSUE TITLE
Screensaver?

### ISSUE THREAD

**Issue by chilipeppr** [UnchartedBull/OctoDash#1078]
Is there a way to have a screensaver or have the screen turn off when not in use, but a touch of the screen turns it back on? I use the standard Raspberry Pi 7" touch screen and it just stays on 24/7 and I'm worried that I'm getting screen burn in and wasting electricity.

**Comment by UnchartedBull** [comment]
https://github.com/UnchartedBull/OctoDash/issues/809#issuecomment-657699783. More sophisticated version is tracked in #410.
