### ISSUE TITLE
Possible to increase vertical scrollbar width?

### ISSUE THREAD

**Issue by CaptainSweatpants** [UnchartedBull/OctoDash#1096]
Is there any way to increase the width of the scrollbar; or better yet, make the entire screen "scrollable" via touch? Its just a tad tricky to get my big fingers on the very small scrollbar on the right side.

**Comment by UnchartedBull** [comment]
Normally the full screen is scrollable via touch. What kind of display are you using?

**Comment by CaptainSweatpants** [comment]
LCD-SHOW 4".
Yeah i can only scroll with the tiny horizontal scrollbar,

**Comment by UnchartedBull** [comment]
It's one that is connected via GPIO only, right? Have you tried using the waveshare driver (https://github.com/waveshare/LCD-show), I don't know whether this fixes your problem, but it may be worth a try. Can also be a limitation of your hardware, as these cheap displays sometimes don't have enough touch resolution to track a "swipe" and rather send multiple click events.

There is unfortunately nothing I can do to get fullscreen scrolling working with these displays. And increasing the width of the scrollbar would mean cramping the other information even more and it would also make the scrollbar obnoxiously big on 5" and 7".

**Comment by thegarbz** [comment]
If it is in fact just a big finger problem and not a touchscreen problem you can customise the scrollbar width with a custom theme. 
Since I'm playing with a themes at the moment I may be able to help you with this, but as I'm commuting to Germany right now this may take a couple of weekends for me to get to.

**Comment by UnchartedBull** [comment]
Thanks to @thegarbz the bigfinger theme is available (Thanks for the PR)! Please try it with your installation and check whether scrolling is now a little more convenient :)
