### ISSUE TITLE
No startup Icon

### ISSUE THREAD

**Issue by eliteSchwein** [UnchartedBull/OctoDash#1099]
**Describe the bug**
Startup is just grey.

**To Reproduce**
Start the Programm

**Expected behavior**
Old startup logo is visible while octodash starts

**Screenshots**
 -tomorrow-

**General Information:**
 - Hardware waveshare 7", rpi4 4gb
 - OS Info raspbian buster 32bit desktop, i manuelly installed octoprint
 - OctoDash Version 2.1.0
 - OctoPrint Version 1.4.2

**Additional context**
You are amazing!

**Comment by UnchartedBull** [comment]
I don't seem to be able to replicate this, neither on the Pi nor the dev app. Could you maybe check if the icon does appear for a split-second during startup and disappears afterwards?

**Comment by eliteSchwein** [comment]
its just blank grey screen

**Comment by eliteSchwein** [comment]
ok switching the cable fixed it
