### ISSUE TITLE
Turn off backlight when sleeping, not just display

### ISSUE THREAD

**Issue by tomaae** [UnchartedBull/OctoDash#1100]
**Is your feature request related to a problem? Please describe.**
Option "Turn Screen Off While Sleeping" turns off display, but not backlight.

**Describe the solution you'd like**
Since there are many types of displays which are handled differently, I propose following solution:
Add 2 more options to config:
1. Execute command in cli when screen is turned off
2. Execute command in cli when screen is turned on

For example in my case it would be:
1. `gpio -g pwm 19 0`
2. `gpio -g pwm 19 40`

**Comment by UnchartedBull** [comment]
I added this to #410 as all the screensaver improvements will be tracked there.

**Comment by whoim2** [comment]
I solved this by connecting the backlight to the power-on pin (plug-in for octoprint) in parallel with the power supply relay, to an unused pair of contacts

**Comment by tomaae** [comment]
Thats not an option with my display unfortunately. I use full header display and messing with that would void warranty. I rather avoid that since its not cheap display.
