### ISSUE TITLE
Connecting to Printer after Power On. Sleeping mode

### ISSUE THREAD

**Issue by komandrik** [UnchartedBull/OctoDash#1101]
I have a printer with a wifi socket. When the printer is turned on, voltage is supplied to the printer and the power supply unit is pi3. After booting the system and starting the octodash - the LCD screen turns on in sleep mode. Octoprint WEB interface shows no connection with printer. You need to manually turn on the connection or click on the Oktodash screen, then the connection to the printer will occur.
I need that after turning on the printer and booting the system, the octodash opens on the main screen, and not in sleep mode.
How do I set it up?

**Comment by UnchartedBull** [comment]
![image](https://user-images.githubusercontent.com/19818061/96752280-86c23f80-13ce-11eb-9ce0-aefdd411820b.png)

Check those two boxes before connecting. After that OctoPrint should automatically connect,
