### ISSUE TITLE
SAVE hangs octodash

### ISSUE THREAD

**Issue by Protoncek** [UnchartedBull/OctoDash#1103]
**Describe the bug**
After upgrade to v2.1.0 hitting "save "button crashed octodash (just goes black) and restart of RPi is required

**To Reproduce**
1. Go to Settings
2. Click on 'Save'
3. that's it...

Is it just mine installation or...? I updated through octodash interface. When octodash freezes octoprint server works normally, so i can restart RPI from octoprint's web site.

BTW... i have installed "modified" user interface (custom styles), published somewhere here - i didn't modify nothing myself.

**Comment by UnchartedBull** [comment]
Duplicate #1071.

**Comment by Protoncek** [comment]
Ups... sorry, i didn’t look so far back, since v2.1.0 was released only 2 days ago and it didn’t happen to me in v2.0.0... so i automatically thought that it’s new version’s fault.
My bad...
