### ISSUE TITLE
Add Enclosure plugin Outputs as configurable actions

### ISSUE THREAD

**Issue by haplm** [UnchartedBull/OctoDash#1123]
**Is your feature request related to a problem? Please describe.**
I would like to turn LED on my enclosure ON and OFF with OctoDash. However, I'm not using Neopixel, but 12V LEDs controlled by a relay attached to one of the RPi GPIO pins. That pin is configured in Enclosure plugin as output (http://octopi.local/plugin/enclosure/outputs) like this:
```[{"index_id": 1, "label": "LED"}]```

**Describe the solution you'd like**
Include Enclosure outputs as predefine actions (https://github.com/UnchartedBull/OctoDash/wiki/Custom-Actions#predefined-actions)

Thanks!

**Comment by jbuszkie** [comment]
Is there a way to do this (work around) until V3 comes out?

**Comment by UnchartedBull** [comment]
I don't know of any. I'm not that familiar with Enclosure Plugin. Best guess would be to check whether you can define custom GCodes and just send those from OctoDash.

**Comment by Zapfmeister** [comment]
Enclosure seems to provide an API to trigger outputs:
https://github.com/vitormhenrique/OctoPrint-Enclosure/wiki/API-Control

You can request all current gpio status with
'''
http://**{URL}**/plugin/enclosure/getOutputStatus?apikey=**{APIKEY}**
'''

Regular GPIO
'''
http://**{URL}**/plugin/enclosure/setIO?status=**{STATUS}**&index_id=**{OUTPUT_ID}**&apikey=**{APIKEY}**
'''
OUTPUT_ID is the automatic generated number id from octoprint-enclosure setting
STATUS is can be true to turn it on and false to turn the output off

**Comment by UnchartedBull** [comment]
I actually wrote that API for the enclosure plugin (mainly to retrieve the temperatures). Should be fairly easy to achieve, it will just be a dumb toggle though, since the custom actions aren't able to handle states.
