### ISSUE TITLE
Does Octodash work with Klipper?

### ISSUE THREAD

**Issue by robotwizard** [UnchartedBull/OctoDash#1132]
Does Octodash work with Klipper?

**Comment by UnchartedBull** [comment]
Yes.

**Comment by flopana77** [comment]
Hi. Just to add to this issue, maybe this is useful in your case:

https://allpro3d.com/how-to-run-octodash-with-klipper-on-a-jetson-nano/

I have Octodash running with Ubuntu 18.04 on a Jetson Nano. I interface with Klipper through Octoprint. Hence, I hope that's  what you are looking for... =)
