### ISSUE TITLE
octodash 2.1.1 starts PLA print at 425 degree !

### ISSUE THREAD

**Issue by 3dattic** [UnchartedBull/OctoDash#1135]
**Describe the bug**
using Prusa 3MKs 
OctoPrint on Raspberry Pi 3B
Octodash 2.1.1
when starting the print from OctoDash the temp setting for PLA goes to 425 degrees. the prints stops with a Max Temp error. or a reset of  printter and then when run again it works okay.
**To Reproduce**

1. Go to 'save gcode to OctoPrint '
2. Click on 'start print PLA'
3. Temp goes to 425 degrees

**Expected behavior**

**Screenshots**

**General Information:**
 - Hardware Raspberry Pi 3b, 
 - OS Info Raspbian OctoPi
 - OctoDash Version 2.1.1
 - OctoPrint Version [1.4.2]

**Comment by UnchartedBull** [comment]
OctoDash doesn't change any of the existing GCode, neither does it set any temperature if you start a print. Have you started the print from the OctoPrint webinterface? Does the error appear there as well?
