### ISSUE TITLE
Real time clock on dash board

### ISSUE THREAD

**Issue by 3dattic** [UnchartedBull/OctoDash#1136]
**Is your feature request related to a problem? Please describe.**
feature request to adda a real time clock on the dash board, which can go half screen when clicked with other items on other half of the screen

**Describe the solution you'd like**
have a digital clock which can be different colours and styles and when clicked on this goes to half screen size and other icons fill the other half.

**Comment by UnchartedBull** [comment]
I don't really see the benefit of this. There will be no printer status shown if all the screen is occupied by a clock and some widgets, plus creating multiple different styled clocks would take a lot of time (which I currently don't have). There also is little to no screen estate left to show a digital clock on the printing screen.

Feel free to create a PR for this, but I won't be working on this. Sorry.
