### ISSUE TITLE
No api

### ISSUE THREAD

**Issue by stevenverde** [UnchartedBull/OctoDash#1140]
I just got octodash installed and during the setup screen it tries to connect to octoprint but it says my firewall is blocking it to try port 80 and for the life of me I can't get it to work.
I already tried port forwarding the raspberry Pi .

I'm using a raspberry Pi 3 b+ with a 3.5 SPI touch screen I have access to ssh only using the ip address not octopi.local. and octopi is the newest version also with the newest version of too Buster

**Comment by eliteSchwein** [comment]
Use 127.0.0.1:5000

**Comment by stevenverde** [comment]
> Use 127.0.0.1:5000

I have tried that and still nothing you mean try using it on the octodash?

**Comment by eliteSchwein** [comment]
Yes

**Comment by stevenverde** [comment]
Ya I've tried with no luck even tried changing the port to 80 and 5000 still nothing. When octodash loads it shows up on the main screen but when I click it it says firewall is blocking it and if I enter manually even with the IP you gave me still same thing

**Comment by stevenverde** [comment]
![1603927933061317314296929364028](https://user-images.githubusercontent.com/73571384/97507800-5e998a00-1954-11eb-812c-3b5938c4b67c.jpg)

**Comment by stevenverde** [comment]
![16039280482748327388158002759827](https://user-images.githubusercontent.com/73571384/97507880-8f79bf00-1954-11eb-821b-ddf8965edfd1.jpg)

**Comment by eliteSchwein** [comment]
Try it with 127.0.0.1:80

**Comment by UnchartedBull** [comment]
Also make sure that your printer is connected to OctoPrint and you haven't disabled the packed_client in OctoPrint.

**Comment by stevenverde** [comment]
Where would I go to disable the packed_client... Sorry I'm new to all this

**Comment by stevenverde** [comment]
Nevermind I got it working thankyou uncharted I'll and eliteschwein for all the help

**Comment by eliteSchwein** [comment]
No Problem, can you please close this issue?
