### ISSUE TITLE
TP smart plug

### ISSUE THREAD

**Issue by dimaknight1109** [UnchartedBull/OctoDash#1149]
**What doesn't work?**
The printer does not turn off as i have  TP Smart plugin programmed that after 120 seconds after my print is completed to turnt he plug off. 
Before i used octopi and it worked not with octodash it does not.

any ideas what i need to change?

**Comment by UnchartedBull** [comment]
Could you double check your configuration for TP-Link. Please also temporarily disable octodash (put a `#` before the `octodash` line in your `~/.xinitrc`) and check again.
