### ISSUE TITLE
Setting Up automatic update

### ISSUE THREAD

**Issue by kats-greg** [UnchartedBull/OctoDash#1152]
In the instructions for setting up the on screen update functionality it says to enter 
pi ALL=NOPASSWD: /home/pi/scripts/update-octodash

When I do that I get an error saying pi command not found.

I am logged into the machine as pi using ssh from windows command line.

Where am I supposed to enter that line?

Thanks

**Comment by FrankX0** [comment]
You should update the script (/etc/sudoers.d/update-octodash) with this line.
To edit use:
`sudo nano /etc/sudoers.d/update-octodash`

**Comment by UnchartedBull** [comment]
Thanks for jumping in @FrankX0.
