### ISSUE TITLE
Shell commands in custom actions

### ISSUE THREAD

**Issue by strangecalling** [UnchartedBull/OctoDash#1158]
**Is your feature request related to a problem? Please describe.**
No a problem, but a feature to add.

**Describe the solution you'd like**
I have written a python script to control a heater for a printer enclosure using a Meross smart switch and would like to be able to start it from Octodash.

Currently I ssh in an run the script from a screen session.

The program reads the enclosure temp and switches off/on the heater and has a timer function. I run a light in a similar way also but have not written a program yet.

**Link other projects**

**Additional context**

**Comment by xommified** [comment]
I think the feature request could be renamed to something more generic like "Run shell commands with Custom Actions", but seconding this feature request. Unsure of the security implications though?

**Comment by UnchartedBull** [comment]
I don't see a security risk here. Everything will be executed by the user that needs to automatically login anyways. So if someone is able to change the custom actions, they also could just exit out of OctoDash and have access to the console.

**Comment by davide-molino** [comment]
I use the action Commands plugins, it can link a shell command to a gcode command, so I've inserted the Gcode in the custom actions and it works.

**Comment by UnchartedBull** [comment]
@davide-molino that's great! Could you maybe post a screenshot of an example config here (just a GCode linking to a random script / command) so I can put it in the wiki?

Closing this here then since it is possible already.

**Comment by davide-molino** [comment]
I've installed Action Commands Plugin, created my own commands and inserted the GCODE in the config.json section for assign the commands to the custom actions in Octodash.
I use Klipper as firmware so for me the GCODE command look like this:

"RESPOND TYPE=command MSG=action: ..."

For Marlin the command is something ilke:

"M118 //action: ..."

![Screenshot_1](https://user-images.githubusercontent.com/72444290/99400547-5dba9f00-28e7-11eb-9a39-7798f18abe5f.png)

![Screenshot_2](https://user-images.githubusercontent.com/72444290/99400567-64491680-28e7-11eb-9541-7a2557ba5479.png)

**Comment by UnchartedBull** [comment]
great. thanks!

**Comment by strangecalling** [comment]
@davide-molino Thank you for showing an excellent solution and @UnchartedBull Thank you for taking the time to look into my query.
