### ISSUE TITLE
Looping error tab saying "Can't retrieve layer progress! 

### ISSUE THREAD

**Issue by k0riz0n** [UnchartedBull/OctoDash#1169]
Hi there,

i've installed Octodash freshly to my Pi. After setup i'm getting continuous the error tab saying "Can't retrieve layer progress! Http failure response for http://.....". Right after tabbing the card to close it, it shows again after a couple of seconds.
While setup Octodash i did not select to use the Display Layer Progress plugin and i didn't have installed it within Octoprint.

Octodash version:  v2.1.1
OctoPrint version: 1.4.2
OctoPi version: 0.17.0

**Comment by UnchartedBull** [comment]
As the docs state Display Layer Progress is mandatory until v2.2.0 is released. There is a custom fork available (have a look at issue #584) which does have a build available without DLP enabled. For the official release you have to have Display Layer Progress installed for now though.
