### ISSUE TITLE
octodash nad TFT 3.5 GPIO

### ISSUE THREAD

**Issue by jpokorny12** [UnchartedBull/OctoDash#1174]
Hi,
trying to install OCTODASH on raspberry. When I connect to  HDMI monitor, I see the OCTODASH interface. I would like them on a TFT connected via GPIO. Is there any way to get them there?
Thank you

**Comment by thegarbz** [comment]
You need to configure Xorg to only output on the TFT. Maybe the bottom of this forum post can help: https://www.raspberrypi.org/forums/viewtopic.php?t=96155

**Comment by jpokorny12** [comment]
Thank you for your help.
It didn't help me at all, or I don't know how to use it.
Can you please give me more detailed instructions?

**Comment by jpokorny12** [comment]
I use this driver 
https://www.waveshare.com/wiki/3.5inch_RPi_LCD_(A)?fbclid=IwAR0C7nUfBRI0UTPGu4QUbuTAZGrzi5yfBnaPNODXNplTzpPZPuMYnhnfp2k
-Install octodash
sudo apt-get install xserver-xorg-video-fbturbo

**Comment by jpokorny12** [comment]
I have octodash on screen.
But touch is mirrored :(

**Comment by thegarbz** [comment]
Mirrored or upside down?

I have that Waveshare display somewhere, it worked out of the box for me. But the input being upside down is a well known problem. There are a couple of fixes https://www.raspberrypi.org/forums/viewtopic.php?t=175100

What exactly are you trying to achieve?

**Comment by jpokorny12** [comment]
When i touch left top corner it recognise touch in right top corner

**Comment by thegarbz** [comment]
Try some of the fixes in the link I sent. Or try running the calibration as per Waveshare's wiki.  That's all I can suggest.

**Comment by jpokorny12** [comment]
Thanks. It works
I use this
```
git clone https://github.com/swkim01/waveshare-dtoverlays.git
sudo cp waveshare-dtoverlays/waveshare35a.dtbo /boot/overlays/
sudo nano /usr/share/X11/xorg.conf.d/40-libinput.conf
```

```
Section "InputClass"
        Identifier "libinput touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
 Option "TransformationMatrix" "1 0 0 0 -1 1 0 0 1"
```

```
Ctrl + o
Ctrl + x
Sudo reboot

```


https://raspberrypi.stackexchange.com/questions/60872/inverted-gpio-touchscreen-using-99-calibration-conf
https://raspberrypi.stackexchange.com/questions/60872/inverted-gpio-touchscreen-using-99-calibration-conf
