### ISSUE TITLE
Make the standby screen subscribe to PSU control

### ISSUE THREAD

**Issue by mikekscholz** [UnchartedBull/OctoDash#1177]
It would be nice if the PSU control integration worked both ways, and would connect back to the main screen when PSU control is triggered remotely from the web interface instead of from the touchscreen. Ive started tinkering and looking for a way to do this but with your deeper understanding of typescript you may find the solution way easier than I can.

**Comment by UnchartedBull** [comment]
I suppose this will be done in v2.2.0 once the web sockets are used. I just checked and there is actually a message being sent for connecting and the connected state. This would then easily enable OctoDash to switch between states in both directions without any interaction from the user.

`{"event": {"type": "Connecting", "payload": null}}`
`{"event": {"type": "Connected", "payload": {"port": "VIRTUAL", "baudrate": 115200}}}`

Just leaving these here for later :)

**Comment by DisasteR** [comment]
I would love to have my octodash waking up without the need to press on screen :D have you some ETA for this ?

**Comment by UnchartedBull** [comment]
Next release, so about ~2 weeks if everything goes to plan

**Comment by DisasteR** [comment]
Hi,

Are you going to release soon ?

Regards

**Comment by UnchartedBull** [comment]
Beta is still running, will probably a week or two.
