### ISSUE TITLE
Getting stuck with Xinit giving up and a server error

### ISSUE THREAD

**Issue by Doormat1** [UnchartedBull/OctoDash#1179]
I have octoprint 1.4.2 installed and have run the latest install script correctly, or at least putty says I have. I go to my pi with an 3.5inch LCD screen correctly installed. (I did have touch UI running on 1.3.12 fine but didnt like the look so I wanted a change)
Now this is what I get on my screen. I have tried the troubleshooter steps and this is what I get in Putty - 
![image](https://user-images.githubusercontent.com/68517771/99156372-4c3f8000-26b8-11eb-9cfa-fdf66408d5e6.png)

![IMG_20201114_193901](https://user-images.githubusercontent.com/68517771/99156328-fb2f8c00-26b7-11eb-961f-a7586bd81376.jpg)

**Comment by UnchartedBull** [comment]
It seems like something with an UI is starting up before OctoDash (thus the screen is already in use). Maybe something that is leftover from TouchUI? Could you please double check whether everything got removed properly? Please also post the contents of `~/.xinitrc` and `~/.bashrc` (only the line were xinit / startx is being called) here

**Comment by Doormat1** [comment]
Im sorry to waste your time but it seems that the mistake I made was to run
the installation script as sudo. Reinstalled without sudo and its working
fine now. I feel like an idiot.

**Comment by UnchartedBull** [comment]
No problem :) thanks for the follow-up!
