### ISSUE TITLE
movement in the control panel

### ISSUE THREAD

**Issue by mawi1986** [UnchartedBull/OctoDash#1180]
Is it possible to adjust the direction of movement in the control panel?
![control](https://user-images.githubusercontent.com/48965597/99187861-4ea5e680-2759-11eb-93c4-2d0795d7639f.png)

I would like to have the Y and Z axes controlled differently

When I push the button up for Y, the print head moves forward instead of backward.
When I press the button for Z down, the bed goes up.
I would love to have both reversed so that it matches the movements of the print head / bed.

**Comment by UnchartedBull** [comment]
You have two options here:

- Either reverse the axis in OctoPrint (which would also reverse the control in the OctoPrint WebUI but not for GCode AFAIK)
- Wait for #1098 (which will include all axis)

**Comment by mawi1986** [comment]
Thanks...
