### ISSUE TITLE
OctoDash Error

### ISSUE THREAD

**Issue by fireguy079** [UnchartedBull/OctoDash#1182]
i keep getting an error on my OctoDash about "Cant Retrieve layer progress" Http failure response for http://octopi.local:80/plugin/displaylayerprogress/values: 0 Unknown Error.

Running latest version of both OctoPi and OctoDash.

thanks,
Kevin
![Capture](https://user-images.githubusercontent.com/74558073/99283651-4efabc00-2803-11eb-804e-7d2678b01ca5.JPG)

**Comment by UnchartedBull** [comment]
error 0 means that OctoDash isn't connected to OctoPrint and can't reach OctoPrint either. please make sure that OctoPrint is up and running and that the URL configured in OctoDash is correct.

Which version of OctoDash are you running?

**Comment by fireguy079** [comment]
> error 0 means that OctoDash isn't connected to OctoPrint and can't reach OctoPrint either. please make sure that OctoPrint is up and running and that the URL configured in OctoDash is correct.
> 
> Which version of OctoDash are you running?

Hello,

Version is 2.1.1 and is it better you use static ip and use the in OctoDash URL?

**Comment by fireguy079** [comment]
issue fixed when i updated OctoDash to use the IP address of the pi.

**Comment by manipel** [comment]
Changing the url in config.json did not work (localhost, ip-adress). Removed and reinstalled DisplayLayerProgress pluging did do the trick. When removing from Octoprint also clear data.
