### ISSUE TITLE
Can not read Files with Octoprint 1.5rc3

### ISSUE THREAD

**Issue by seipekm** [UnchartedBull/OctoDash#1197]
I try now the newest version from Octoprint and Octodash say he can not find some File. Folder are empty. I go back to 1.4. Then he show all my files

OctoPi 0.18 64Bit
Octoprint 1.5rc3
OctoDash 2.1.2
Raspberry Pi 4 4GB

**Comment by komandrik** [comment]
I confirm. Only files in the root are visible, files are not displayed in folders.

**Comment by UnchartedBull** [comment]
Merging with issue #1184. This issue had a different (might not so obvious) title before but is essentially the same thing. I'll have a look at that.
