### ISSUE TITLE
Change Header Icon

### ISSUE THREAD

**Issue by toedtling** [UnchartedBull/OctoDash#1204]
Is there a way to change the Header Icon on an installed Octodash Installation? I do not find the OctoDash-master\src\app\main-menu/main-menu.component.html after Installation?

**Comment by UnchartedBull** [comment]
Not possible once packed due to a lot of optimisations that is going on while being packed (everything is condensed into only a handful of files).

You would need to adjust the header in the source code and then build OctoDash yourself.
