### ISSUE TITLE
screen saver: gray the screen when not in use

### ISSUE THREAD

**Issue by jpokorny12** [UnchartedBull/OctoDash#1207]
Instead of adjusting the backlight brightness, the screen may turn gray (change the color saturation)

When the printer is off, the screen saver is good. But when printing, the screen saver could also be good.

I support this project and in my opinion it is the best touch interface for octoprint. Big thanks

**Comment by UnchartedBull** [comment]
What would be the benefit of having the screen in greyscale colours? It doesn't prevent burn-in on OLEDs and won't have any affect on power consumption either. A more advanced screen saving is tracked in #410.
