### ISSUE TITLE
Driver for 3.5 Inch LCD HDMI The UCTRONICS Display does not seem to have a touch Driver for a 64bit Pi that I can find? I've seen others running the touch.

### ISSUE THREAD

**Issue by Liqi22** [UnchartedBull/OctoDash#1209]
**What doesn't work?**

**What did you already try?**
A clear and concise description of what you tried to make OctoDash work.

**General Information:**
 - Hardware [e.g. Raspberry Pi, if you have layout issues please also include your screen resolution]
 - OS Info [e.g. Raspbian Buster Lite, please also indicate if you used OctoPi]
 - OctoDash Version [e.g. v1.0.0]
 - OctoPrint Version [e.g. v1.0.0]

**Additional context**

**Comment by UnchartedBull** [comment]
Please check closed issues and Google. I usually don't recommend those cheap 3.5" screens, since drivers always seem to be a mess. I don't have one myself, so I can't provide any assistance here.
