### ISSUE TITLE
file sorting option to be saved automatically

### ISSUE THREAD

**Issue by Whitehawk2000** [UnchartedBull/OctoDash#1230]
The file sorting order always resets after leaving the filemanager. It would be great if octodash could remember the last option chosen by the user.

**Comment by UnchartedBull** [comment]
You can define a default sorting in the settings for now.

It's a a good idea to remember the sorting for the whole session though. Will be included in one of the next releases.

**Comment by Whitehawk2000** [comment]
> You can define a default sorting in the settings for now.

Just figured it out by accident yesterday evening. :-)

> It's a a good idea to remember the sorting for the whole session though. Will be included in one of the next releases.

I think so to, as it is more intuitive.

**Comment by thegarbz** [comment]
@UnchartedBull Question: Why only save it for the session? It would be quite intuitive to save it permanently and just get rid of the options in the settings altogether.

**Comment by UnchartedBull** [comment]
That probably is a good idea and should be fairly simple to do.
