### ISSUE TITLE
Print problem

### ISSUE THREAD

**Issue by g14nluc4** [UnchartedBull/OctoDash#1252]
Hi all, I had octodash installed on octoprint and it worked perfectly.  Now I had to change sd because it no longer read it.  I installed octoprint and then octodash, it shows and works, the only thing is that if I go to press on a file to print the print does not start, on the contrary, I noticed that if I do the preheating then on the monitor dedicated to octodash and I press  on print the heating values ​​are set to 0 and obviously the print does not start.  How can I solve?  Both octoprint and octodash are at their latest version.  all installed today

**Comment by UnchartedBull** [comment]
Please check your Octoprint web interface if any errors are displayed there. Most likely a plugin that is waiting for some input. If that doesn't solve this please provide the following:

- Does OctoPrint show any errors / messages
- Does OctoDash show any errors
- What does the text in the bottom right corner say (OctoDash)
- What have you changed compared to the working setup (except the SD card of course)
