### ISSUE TITLE
OctoPrint do not show up and the screen showing white lines...

### ISSUE THREAD

**Issue by arut16** [UnchartedBull/OctoDash#1261]
**What doesn't work?**
On a functionnal OctoPrint setup, I'm trying to install octodash with a 5" capacitive screen [from here](https://fr.aliexpress.com/item/4000285091974.html?spm=a2g0s.9042311.0.0.570d6c37bRDc6d).
Now Octoprint do not showUp and the screen do not show octodash but some mystical lines for me...
![image](https://user-images.githubusercontent.com/58274805/102917364-658cd680-4485-11eb-8a50-a4ea0bbe0e01.png)

**What did you already try?**
I tryed [this complete tutorial](https://induste.com/threads/tuto-installation-doctodash-sur-raspberry-pi-avec-ecran-local.635619/) when I'm tryed bash installation for automatic installation (bash <(wget -qO- https://github.com/UnchartedBull/OctoDash/raw/master/scripts/install.sh)

**General Information:**
 - Hardware : RPi 4 Go with 800x460 screen [from here](https://fr.aliexpress.com/item/4000285091974.html?spm=a2g0s.9042311.0.0.570d6c37bRDc6d)
 - OS Info : Raspbian Buster with OctoPi 0.17.0
 - OctoDash Version : 2.0.0 when 2.1.7 (?) with auto script ?
 - OctoPrint Version : 1.5.2

**Additional context**
![132666081_1092260787913296_3568344586117588559_n](https://user-images.githubusercontent.com/58274805/102917215-15ae0f80-4485-11eb-8260-8d7e93d6f495.jpg)

**Comment by UnchartedBull** [comment]
Hmm I can't really see anything from the picture you posted since it doesn't contain any errors. Have you enabled automatic login for Pi like described [here](https://github.com/UnchartedBull/OctoDash/wiki/Installation#autologin)? Have you checked the [troubleshooting guide](https://github.com/UnchartedBull/OctoDash/wiki/Troubleshooting)?

**Comment by arut16** [comment]
I ended up dropping this issue. And started again from the beginning with a fresh octroprint installation and everything installed correctly with bash auto script and works perfectly.
