### ISSUE TITLE
Octodash wont start after install, octoscreen starts by default

### ISSUE THREAD

**Issue by monukoshy** [UnchartedBull/OctoDash#1268]
**Describe the bug**
After I have installed octodash, on my rpi4 8gb, with hyperpixel rectagular screen, octodash wont start. I have to manally run these commands to start it on my screen.
export DISPLAY=:0
octodash

Can i automate this to start octodash, I do not want to go the chroma kiosk route, its complicated and I am sure there are easier methods out there.

**To Reproduce**

**Expected behavior**

**Screenshots**

**General Information:**
 - Hardware [e.g. Raspberry Pi, if you have layout issues please also include your screen resolution]
 - OS Info [e.g. Raspbian Buster Lite, please also indicate if you used OctoPi]
 - OctoDash Version [e.g. v1.0.0]
 - OctoPrint Version [e.g. v1.0.0]

**Additional context**

**Comment by UnchartedBull** [comment]
Please follow these steps if you haven't selected to auto start OctoDash during installation: https://github.com/UnchartedBull/OctoDash/wiki/Installation#start-octodash-automatic-on-boot. Also make sure to have auto login enabled.
