### ISSUE TITLE
Lost functionality

### ISSUE THREAD

**Issue by thezinger** [UnchartedBull/OctoDash#1270]
Rather odd; I rebooted my pi (which hosts both my OctoPi and OctoDash instances), and once it's come back up I have functionality within OctoDash to only change the temperature of the hot end, temperature of the bed, and fan speed.  Gone is the ability to select files, control, or settings.  In fact, those options don't even appear on the screen.  I should say first off that I am not using a touch screen, using a mouse with the -- -nocursor removed.

Thoughts?

**Comment by UnchartedBull** [comment]
Probably some assets that didn't get loaded. Please try and restart :)
