### ISSUE TITLE
Possibility to show when printer is virtual

### ISSUE THREAD

**Issue by k0riz0n** [UnchartedBull/OctoDash#1274]
Maybe it is possible to show when connected to the virtual port for the printer Octoprint can simulate.
A little text like "(v)" or a symbol on the main or sub page would be helpful.

Actual i wondered why my control over octodash does not move me printer in real until i realized i'm "connected" to the virtual printer.

**Comment by UnchartedBull** [comment]
Related to #922 and will be tracked over there. Thanks for the idea!
