### ISSUE TITLE
octodash

### ISSUE THREAD

**Issue by vipertech17** [UnchartedBull/OctoDash#1275]
**What doesn't work?**
changed ip address and rate to 5000 should have left it at 80. now it wont connect and cant find a way to change it back
**What did you already try?**
connection to octodash
**General Information:**
 - Hardware [e.g. Raspberry Pi, if you have layout issues please also include your screen resolution]
 - OS Info [e.g. Raspbian Buster Lite, please also indicate if you used OctoPi]
 - OctoDash Version [e.g. v1.0.0]
 - OctoPrint Version [e.g. v1.0.0]

**Additional context**

**Comment by UnchartedBull** [comment]
Please adjust your config manually: https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings#manually-adjusting-the-settings. Here is the default config: https://github.com/UnchartedBull/OctoDash/blob/master/src/app/config/config.default.ts
