### ISSUE TITLE
Action Commands / Shell Script

### ISSUE THREAD

**Issue by SaKiEQ** [UnchartedBull/OctoDash#1280]
**Is your feature request related to a problem? Please describe.**
Nope, but it would be nice to be able to customize the action command more then currently possible.

**Describe the solution you'd like**
Allow shell scripts or python scripts to be executed as actions.

**Link other projects**
Or inherit I/O functions defined in Enclosure Plugin... like light and fan switches.

**Additional context**
Ideally one or two action command buttons on home screen and print screen, so enclosure lights can be 
turned on / off easily.

**Comment by UnchartedBull** [comment]
To execute Shell Scripts please use the Action Commands plugin: https://plugins.octoprint.org/plugins/actioncommands/. You can the use simple GCode Custom Actions to trigger those via OctoDash. There was an issue already open for that and I decided not to have a separate CLI function in OctoDash, as this could be a possible security compromise. Enclosure Plugin will be extended further #1123.

Custom buttons on printing screen are tracked in #828.

Closing this as duplicate, please reopen if I missed something.
