### ISSUE TITLE
OctoDash Need API Key

### ISSUE THREAD

**Issue by BobAK1** [UnchartedBull/OctoDash#1289]
BiigtreeTech pitft50 with raspberry pi 4b. installed octodash, it requests API Key. Tried
http://localhost:5000
http://localhost:127.0.0.1
http://localhost:80

nothing working.

**Comment by UnchartedBull** [comment]
Neither of those are API Keys. API Key either needs to be copied from the settings from OctoPrint UI or requested via OctoDash.

**Comment by Christoph512** [comment]
You can find the API Key in the Octoprint Webinterface under: Octoprint settings -> functions -> API -> Global API Key.
