### ISSUE TITLE
Babystepping settings arent stored permanently

### ISSUE THREAD

**Issue by ChristianH99** [UnchartedBull/OctoDash#1293]
The save button doesn't execute M500 command to store the offset. It is only stored until the printer is restarted, so the save button has no use.

1. Start print
2. Go to adjust
3. Select babystepping
4. Adjust settings
5. Go back
6. Click save

**Expected behavior**
The adjusted offset is stored permanently using the M500 command.

**General Information:**
 - Raspberry Pi 3 B +
 - OctoDash V2.1.2

**Comment by UnchartedBull** [comment]
That currently is by design. Maybe I understand the functionality wrong here, but AFAIK Marlin doesn't save babystepping during printer either, but you rather have to send M500, or am I wrong here?

**Comment by ChristianH99** [comment]
I‘m not sure how marlin deals with this and I have disabled all that functions on my printer to save memory, but as far as I remember you have to click save to store the value permanently as well.

**Comment by UnchartedBull** [comment]
Oh I didn't read your last step properly. I'll probably include a separate safe button in the Babystepping screen. Using the save button on the adjust screen could lead to some problems (since you need to press that to save the adjustments).

**Comment by ChristianH99** [comment]
Yes that would be perfect
