### ISSUE TITLE
[FR] MoonRaker Support

### ISSUE THREAD

**Issue by ReubenBTalbott** [UnchartedBull/OctoDash#1307]
**Is your feature request related to a problem? Please describe.**
Trying to move away from OctoPrint. Klipper with MoonRaker and a WebUI client like Fluidd looks like a good alternative but there is no good touch screen UI option.

**Describe the solution you'd like**
Allow OctoDash to use OctoPrint or MoonRaker.

**Link other projects**
https://github.com/KevinOConnor/klipper
https://github.com/Arksine/moonraker
https://github.com/cadriel/fluidd

I would be happy to test anything I can!

**Comment by UnchartedBull** [comment]
Moonraker currently is not on my list unfortunately. There are a few people over on Discord who also would like to convert OctoDash over to Moonraker (One guy offered to do the coding part). I guess it's best to get in touch with them. I can help you guys with getting started but this isn't on my priority list. Sorry!
