### ISSUE TITLE
Scrolling text of print name

### ISSUE THREAD

**Issue by Jeggo65** [UnchartedBull/OctoDash#1338]
Hello,

I just started to use OctoDash, which seems to be the nicest UI for Octoprint.
I use a Prusa i3 MK3S with MMU2S. The Prusa slicer produces quite long filenames (which is OK).
It would be nice to have either a scrolling text line on the top or a second text line for the print model name (I use a 3,5" display).

Regards

Jens

**Comment by UnchartedBull** [comment]
duplicate of #627.
