### ISSUE TITLE
Trying to add mouse to use with my computer monitor.

### ISSUE THREAD

**Issue by slicerFPV** [UnchartedBull/OctoDash#1353]
So I tried to follow the directions on one of the threads already out there about how to add the mouse to use on a monitor but when I enter the command (nano ~/.bashrc) I end up getting a screen that doesn’t have anything saying (xinit — -no cursor) for me to edit. Is there something else I have to do to get to the section with this information so I can edit it out to add the mouse cursor?
im a total noob with this stuff still sorry and
Thank you!!!

**Comment by UnchartedBull** [comment]
Please try the steps outlined in the other issue you commented on
