### ISSUE TITLE
connection to octoprint timed out!!

### ISSUE THREAD

**Issue by jec0709** [UnchartedBull/OctoDash#1356]
hello
After the octodash installation was complete, the initial setup was performed.
I changed the ip, but the message like the image keeps coming out and I can't connect.
192.168.0.18:80 -> octopi.local:80

How do I get back to the initial setup [screen?[](url)](url
![1](https://user-images.githubusercontent.com/50090531/106227013-cbf6d880-622b-11eb-8f1c-0f2556a073f3.JPG)
)

**Comment by UnchartedBull** [comment]
Delete the config file `rm ~/.config/octodash/config.json`.
