### ISSUE TITLE
Subdirectories showing 0 files

### ISSUE THREAD

**Issue by pirate008** [UnchartedBull/OctoDash#1357]
**Describe the bug**
Subdirectories created through Octoprint web interface show 0 files in OctoDash interface
even when there are files there. I'm uploading .ufp files. Have not tried .gcode files.

**To Reproduce**
1. Create folder in Octoprint
2. Upload .ufp file to the newly created folder
3. Go to OctoDash files section. Folder shows 0 files inside
4. Open folder and the file is there

**Expected behavior**
Show number of files in folder

**Screenshots**
![IMG_4174](https://user-images.githubusercontent.com/78198565/106248282-70235400-6219-11eb-81fb-a799c1ff0a7f.JPG)

**General Information:**
 - Hardware Raspberry Pi 3B with official 7" touchscreen
 - OS Info OctoPi 0.18.0
 - OctoDash Version 2.1.2
 - OctoPrint Version ? Latest at the time of writing

**Comment by UnchartedBull** [comment]
Octoprint removed this information from the API response with v1.5.0. OctoDash will replace the 0 files with folder size in mb (which really is the only somewhat useful metric left in the API response).
