### ISSUE TITLE
Problem after update DisplayLayerProgress to 1.25.1

### ISSUE THREAD

**Issue by nettunoroberto** [UnchartedBull/OctoDash#1361]
After update DisplayLayerProgress to 1.25.1 i have the error on display  : 500 internal server error.

**Comment by CaptainSweatpants** [comment]
Im having problems with DisplayLayerProgress as well. Seems others are too after the update on their git page. Issue [#205](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/205)

**Comment by nettunoroberto** [comment]
SOLVE, now is out new version of DisplayLayerProgress 1.25.2 without any problems whit API on Octodash.
