### ISSUE TITLE
Delay start plugins Encloser and DisplayLayerProgress

### ISSUE THREAD

**Issue by nettunoroberto** [UnchartedBull/OctoDash#1374]
Good evening, I would like to know if it is possible to delay the start of the enclosure and display layer progress plugins on boot until octodash has changed the status to "operational". I have octodash with Klipper firmware and often I have communication errors of the two plugins until octodash recognizes the connection of octoprint with klipper. 

Thank you all

**Comment by UnchartedBull** [comment]
Not with the current version. The next version will rely on the OctoPrint socket, which pushes data instead of pulling it, which should get rid of your error (at least for DLP). I'll make sure to include the delay for the enclosure plugin as well.

**Comment by nettunoroberto** [comment]
Tnx bro.

**Comment by UnchartedBull** [comment]
Keeping this open, just so I don't forget it :) Will be closed with the correct PR.
