### ISSUE TITLE
Installing failed

### ISSUE THREAD

**Issue by kekko7072** [UnchartedBull/OctoDash#1388]
**What doesn't work?**
I tried to install using all the guides I found official and unofficial but it always shows this error on starting.

xauth:  file /root/.Xauthority does not exist

X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
Current Operating System: Linux octopi 5.10.11+ #1399 Thu Jan 28 12:02:28 GMT 2021 armv6l
Kernel command line: coherent_pool=1M snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
Build Date: 15 January 2021  02:03:57PM
xorg-server 2:1.20.4-1+rpt2+deb10u3 (https://www.debian.org/support) 
Current version of pixman: 0.36.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sat Feb  6 18:35:33 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
modprobe: FATAL: Module g2d_23 not found in directory /lib/modules/5.10.11+

or without desktop downloaded it shows screen not found.

 I dont this is linked to octodash but maybe to missing diriver or Server installation. I tried installing also desktop but nothing works, always this error and black Screen. The lcd is correctly installed in fact Raspbian desktop correctly works also using touchscreen

**What did you already try?**
A clear and concise description of what you tried to make OctoDash work.

**General Information:**
 - Raspberry Pi 3 model B, LCD https://www.waveshare.com/wiki/5inch_HDMI_LCD 
 - OctoPi and desktop support
OctoPrint version : 1.5.2
OctoPi version    : 0.18.0

**Comment by kekko7072** [comment]
ERROR LOG

[    52.577] 
X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
[    52.578] Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
[    52.578] Current Operating System: Linux octopi 5.10.11+ #1399 Thu Jan 28 12:02:28 GMT 2021 armv6l
[    52.579] Kernel command line: coherent_pool=1M snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
[    52.588] Build Date: 15 January 2021  02:03:57PM
[    52.588] xorg-server 2:1.20.4-1+rpt2+deb10u3 (https://www.debian.org/support) 
[    52.588] Current version of pixman: 0.36.0
[    52.589] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    52.589] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    52.597] (==) Log file: "/var/log/Xorg.0.log", Time: Sat Feb  6 18:48:21 2021
[    52.627] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    52.660] (==) No Layout section.  Using the first Screen section.
[    52.660] (==) No screen section available. Using defaults.
[    52.660] (**) |-->Screen "Default Screen Section" (0)
[    52.661] (**) |   |-->Monitor "<default monitor>"
[    52.684] (==) No device specified for screen "Default Screen Section".
	Using the first device section listed.
[    52.684] (**) |   |-->Device "Allwinner A10/A13 FBDEV"
[    52.685] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[    52.685] (==) Automatically adding devices
[    52.685] (==) Automatically enabling devices
[    52.685] (==) Automatically adding GPU devices
[    52.686] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    52.715] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    52.715] 	Entry deleted from font path.
[    52.715] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    52.715] 	Entry deleted from font path.
[    52.716] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    52.716] 	Entry deleted from font path.
[    52.716] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    52.716] 	Entry deleted from font path.
[    52.716] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    52.717] 	Entry deleted from font path.
[    52.717] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    52.717] 	Entry deleted from font path.
[    52.717] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	built-ins
[    52.717] (==) ModulePath set to "/usr/lib/xorg/modules"
[    52.717] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    52.718] (II) Loader magic: 0x1fdf80
[    52.718] (II) Module ABI versions:
[    52.718] 	X.Org ANSI C Emulation: 0.4
[    52.718] 	X.Org Video Driver: 24.0
[    52.719] 	X.Org XInput driver : 24.1
[    52.719] 	X.Org Server Extension : 10.0
[    52.765] (++) using VT number 7

[    52.765] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    52.767] (II) no primary bus or device found
[    52.767] (II) LoadModule: "glx"
[    52.787] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    52.922] (II) Module glx: vendor="X.Org Foundation"
[    52.922] 	compiled for 1.20.4, module version = 1.0.0
[    52.922] 	ABI class: X.Org Server Extension, version 10.0
[    52.923] (II) LoadModule: "fbturbo"
[    52.952] (II) Loading /usr/lib/xorg/modules/drivers/fbturbo_drv.so
[    52.962] (II) Module fbturbo: vendor="X.Org Foundation"
[    52.963] 	compiled for 1.20.3, module version = 0.5.1
[    52.963] 	Module class: X.Org Video Driver
[    52.963] 	ABI class: X.Org Video Driver, version 24.0
[    52.963] (II) FBTURBO: driver for framebuffer: fbturbo
[    52.985] (WW) Falling back to old probe method for fbturbo
[    52.985] (II) Loading sub module "fbdevhw"
[    52.985] (II) LoadModule: "fbdevhw"
[    52.986] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    53.025] (II) Module fbdevhw: vendor="X.Org Foundation"
[    53.025] 	compiled for 1.20.4, module version = 0.0.2
[    53.026] 	ABI class: X.Org Video Driver, version 24.0
[    53.027] (II) FBTURBO(0): using /dev/fb0
[    53.027] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[    53.028] (II) FBTURBO(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[    53.028] (==) FBTURBO(0): Depth 24, (==) framebuffer bpp 32
[    53.028] (==) FBTURBO(0): RGB weight 888
[    53.028] (==) FBTURBO(0): Default visual is TrueColor
[    53.029] (==) FBTURBO(0): Using gamma correction (1.0, 1.0, 1.0)
[    53.029] (II) FBTURBO(0): hardware: BCM2708 FB (video memory: 1500kB)
[    53.029] (DB) xf86MergeOutputClassOptions unsupported bus type 0
[    53.029] (**) FBTURBO(0): Option "fbdev" "/dev/fb0"
[    53.050] (**) FBTURBO(0): Option "SwapbuffersWait" "true"
[    53.051] (II) FBTURBO(0): processor: ARM1176
[    53.052] (II) FBTURBO(0): checking modes against framebuffer device...
[    53.052] (II) FBTURBO(0): checking modes against monitor...
[    53.052] (II) FBTURBO(0): Virtual size is 800x480 (pitch 800)
[    53.053] (**) FBTURBO(0):  Built-in mode "current"
[    53.053] (==) FBTURBO(0): DPI set to (96, 96)
[    53.053] (II) Loading sub module "fb"
[    53.053] (II) LoadModule: "fb"
[    53.055] (II) Loading /usr/lib/xorg/modules/libfb.so
[    53.107] (II) Module fb: vendor="X.Org Foundation"
[    53.107] 	compiled for 1.20.4, module version = 1.0.0
[    53.107] 	ABI class: X.Org ANSI C Emulation, version 0.4
[    53.161] (II) FBTURBO(0): using backing store heuristics
[    53.390] (II) FBTURBO(0): can't load 'g2d_23' kernel module
[    53.391] (II) FBTURBO(0): failed to enable the use of sunxi display controller
[    53.391] (II) FBTURBO(0): No sunxi-g2d hardware detected (check /dev/disp and /dev/g2d)
[    53.391] (II) FBTURBO(0): G2D hardware acceleration can't be enabled
[    53.392] (II) FBTURBO(0): enabled fbdev copyarea acceleration
[    53.392] (==) FBTURBO(0): Backing store enabled
[    53.420] (==) FBTURBO(0): DPMS enabled
[    53.420] (II) FBTURBO(0): failed to enable hardware cursor
[    53.421] (II) FBTURBO(0): no 3D acceleration because the driver has been compiled without libUMP
[    53.421] (II) FBTURBO(0): if this is wrong and needs to be fixed, please check ./configure log
[    53.432] (II) Initializing extension Generic Event Extension
[    53.436] (II) Initializing extension SHAPE
[    53.439] (II) Initializing extension MIT-SHM
[    53.484] (II) Initializing extension XInputExtension
[    53.492] (II) Initializing extension XTEST
[    53.495] (II) Initializing extension BIG-REQUESTS
[    53.498] (II) Initializing extension SYNC
[    53.532] (II) Initializing extension XKEYBOARD
[    53.545] (II) Initializing extension XC-MISC
[    53.555] (II) Initializing extension SECURITY
[    53.581] (II) Initializing extension XFIXES
[    53.584] (II) Initializing extension RENDER
[    53.587] (II) Initializing extension RANDR
[    53.622] (II) Initializing extension COMPOSITE
[    53.631] (II) Initializing extension DAMAGE
[    53.634] (II) Initializing extension MIT-SCREEN-SAVER
[    53.637] (II) Initializing extension DOUBLE-BUFFER
[    53.680] (II) Initializing extension RECORD
[    53.683] (II) Initializing extension DPMS
[    53.686] (II) Initializing extension Present
[    53.689] (II) Initializing extension DRI3
[    53.689] (II) Initializing extension X-Resource
[    53.703] (II) Initializing extension XVideo
[    53.716] (II) Initializing extension XVideo-MotionCompensation
[    53.716] (II) Initializing extension SELinux
[    53.716] (II) SELinux: Disabled on system
[    53.716] (II) Initializing extension GLX
[    53.733] (II) AIGLX: Screen 0 is not DRI2 capable
[    58.191] (II) IGLX: Loaded and initialized swrast
[    58.192] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[    58.192] (II) Initializing extension XFree86-VidModeExtension
[    58.195] (II) Initializing extension XFree86-DGA
[    58.198] (II) Initializing extension XFree86-DRI
[    58.220] (II) Initializing extension DRI2
[    61.797] (II) config/udev: Adding input device ADS7846 Touchscreen (/dev/input/event5)
[    61.797] (**) ADS7846 Touchscreen: Applying InputClass "evdev touchscreen catchall"
[    61.798] (**) ADS7846 Touchscreen: Applying InputClass "evdev touchscreen catchall"
[    61.798] (**) ADS7846 Touchscreen: Applying InputClass "calibration"
[    61.798] (II) LoadModule: "evdev"
[    61.799] (II) Loading /usr/lib/xorg/modules/input/evdev_drv.so
[    61.874] (II) Module evdev: vendor="X.Org Foundation"
[    61.874] 	compiled for 1.20.3, module version = 2.10.6
[    61.874] 	Module class: X.Org XInput Driver
[    61.874] 	ABI class: X.Org XInput driver, version 24.1
[    61.874] (II) Using input driver 'evdev' for 'ADS7846 Touchscreen'
[    61.875] (**) ADS7846 Touchscreen: always reports core events
[    61.875] (**) evdev: ADS7846 Touchscreen: Device: "/dev/input/event5"
[    61.876] (--) evdev: ADS7846 Touchscreen: Vendor 0 Product 0
[    61.877] (--) evdev: ADS7846 Touchscreen: Found absolute axes
[    61.877] (--) evdev: ADS7846 Touchscreen: Found x and y absolute axes
[    61.877] (--) evdev: ADS7846 Touchscreen: Found absolute touchscreen
[    61.877] (**) Option "SwapAxes" "0"
[    61.878] (II) evdev: ADS7846 Touchscreen: Configuring as touchscreen
[    61.878] (**) Option "EmulateThirdButton" "1"
[    61.879] (**) Option "EmulateThirdButtonTimeout" "1000"
[    61.879] (**) Option "EmulateThirdButtonMoveThreshold" "300"
[    61.920] (**) evdev: ADS7846 Touchscreen: YAxisMapping: buttons 4 and 5
[    61.920] (**) evdev: ADS7846 Touchscreen: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    61.921] (**) Option "config_info" "udev:/sys/devices/platform/soc/20204000.spi/spi_master/spi0/spi0.1/input/input5/event5"
[    61.921] (II) XINPUT: Adding extended input device "ADS7846 Touchscreen" (type: TOUCHSCREEN, id 6)
[    61.922] (II) evdev: ADS7846 Touchscreen: initialized for absolute axes.
[    61.925] (**) ADS7846 Touchscreen: (accel) keeping acceleration scheme 1
[    61.925] (**) ADS7846 Touchscreen: (accel) acceleration profile 0
[    61.926] (**) ADS7846 Touchscreen: (accel) acceleration factor: 2.000
[    61.926] (**) ADS7846 Touchscreen: (accel) acceleration threshold: 4
[    62.003] (II) config/udev: Adding input device ADS7846 Touchscreen (/dev/input/mouse1)
[    62.004] (**) ADS7846 Touchscreen: Applying InputClass "calibration"
[    62.004] (II) No input driver specified, ignoring this device.
[    62.004] (II) This device may have been added with another device file.
[    62.111] (II) config/udev: Adding input device MOSART Semi. 2.4G Wireless Mouse (/dev/input/event0)
[    62.122] (**) MOSART Semi. 2.4G Wireless Mouse: Applying InputClass "evdev pointer catchall"
[    62.122] (**) MOSART Semi. 2.4G Wireless Mouse: Applying InputClass "evdev pointer catchall"
[    62.122] (II) Using input driver 'evdev' for 'MOSART Semi. 2.4G Wireless Mouse'
[    62.122] (**) MOSART Semi. 2.4G Wireless Mouse: always reports core events
[    62.123] (**) evdev: MOSART Semi. 2.4G Wireless Mouse: Device: "/dev/input/event0"
[    62.123] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Vendor 0x3938 Product 0x1031
[    62.124] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Found 9 mouse buttons
[    62.124] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Found scroll wheel(s)
[    62.124] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Found relative axes
[    62.124] (--) evdev: MOSART Semi. 2.4G Wireless Mouse: Found x and y relative axes
[    62.124] (II) evdev: MOSART Semi. 2.4G Wireless Mouse: Configuring as mouse
[    62.125] (II) evdev: MOSART Semi. 2.4G Wireless Mouse: Adding scrollwheel support
[    62.125] (**) evdev: MOSART Semi. 2.4G Wireless Mouse: YAxisMapping: buttons 4 and 5
[    62.125] (**) evdev: MOSART Semi. 2.4G Wireless Mouse: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    62.125] (**) Option "config_info" "udev:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:3938:1031.0001/input/input0/event0"
[    62.126] (II) XINPUT: Adding extended input device "MOSART Semi. 2.4G Wireless Mouse" (type: MOUSE, id 7)
[    62.127] (II) evdev: MOSART Semi. 2.4G Wireless Mouse: initialized for relative axes.
[    62.171] (**) MOSART Semi. 2.4G Wireless Mouse: (accel) keeping acceleration scheme 1
[    62.171] (**) MOSART Semi. 2.4G Wireless Mouse: (accel) acceleration profile 0
[    62.172] (**) MOSART Semi. 2.4G Wireless Mouse: (accel) acceleration factor: 2.000
[    62.172] (**) MOSART Semi. 2.4G Wireless Mouse: (accel) acceleration threshold: 4
[    62.258] (II) config/udev: Adding input device MOSART Semi. 2.4G Wireless Mouse (/dev/input/mouse0)
[    62.258] (II) No input driver specified, ignoring this device.
[    62.258] (II) This device may have been added with another device file.
[    62.335] (II) config/udev: Adding input device MOSART Semi. 2.4G Wireless Mouse (/dev/input/event1)
[    62.336] (II) No input driver specified, ignoring this device.
[    62.336] (II) This device may have been added with another device file.
[    62.436] (II) config/udev: Adding input device SEM USB Keyboard (/dev/input/event2)
[    62.437] (**) SEM USB Keyboard: Applying InputClass "evdev keyboard catchall"
[    62.437] (**) SEM USB Keyboard: Applying InputClass "evdev keyboard catchall"
[    62.437] (II) Using input driver 'evdev' for 'SEM USB Keyboard'
[    62.437] (**) SEM USB Keyboard: always reports core events
[    62.438] (**) evdev: SEM USB Keyboard: Device: "/dev/input/event2"
[    62.439] (--) evdev: SEM USB Keyboard: Vendor 0x1a2c Product 0x2124
[    62.439] (--) evdev: SEM USB Keyboard: Found keys
[    62.439] (II) evdev: SEM USB Keyboard: Configuring as keyboard
[    62.439] (**) Option "config_info" "udev:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/0003:1A2C:2124.0002/input/input2/event2"
[    62.462] (II) XINPUT: Adding extended input device "SEM USB Keyboard" (type: KEYBOARD, id 8)
[    62.462] (**) Option "xkb_rules" "evdev"
[    62.463] (**) Option "xkb_model" "pc105"
[    62.463] (**) Option "xkb_layout" "gb"
[    63.894] (II) config/udev: Adding input device SEM USB Keyboard Consumer Control (/dev/input/event3)
[    63.895] (**) SEM USB Keyboard Consumer Control: Applying InputClass "evdev keyboard catchall"
[    63.895] (**) SEM USB Keyboard Consumer Control: Applying InputClass "evdev keyboard catchall"
[    63.895] (II) Using input driver 'evdev' for 'SEM USB Keyboard Consumer Control'
[    63.896] (**) SEM USB Keyboard Consumer Control: always reports core events
[    63.896] (**) evdev: SEM USB Keyboard Consumer Control: Device: "/dev/input/event3"
[    63.897] (--) evdev: SEM USB Keyboard Consumer Control: Vendor 0x1a2c Product 0x2124
[    63.897] (--) evdev: SEM USB Keyboard Consumer Control: Found 1 mouse buttons
[    63.897] (--) evdev: SEM USB Keyboard Consumer Control: Found scroll wheel(s)
[    63.897] (--) evdev: SEM USB Keyboard Consumer Control: Found relative axes
[    63.897] (II) evdev: SEM USB Keyboard Consumer Control: Forcing relative x/y axes to exist.
[    63.898] (--) evdev: SEM USB Keyboard Consumer Control: Found absolute axes
[    63.898] (II) evdev: SEM USB Keyboard Consumer Control: Forcing absolute x/y axes to exist.
[    63.898] (--) evdev: SEM USB Keyboard Consumer Control: Found keys
[    63.898] (II) evdev: SEM USB Keyboard Consumer Control: Configuring as mouse
[    63.898] (II) evdev: SEM USB Keyboard Consumer Control: Configuring as keyboard
[    63.899] (II) evdev: SEM USB Keyboard Consumer Control: Adding scrollwheel support
[    63.899] (**) evdev: SEM USB Keyboard Consumer Control: YAxisMapping: buttons 4 and 5
[    63.899] (**) evdev: SEM USB Keyboard Consumer Control: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    63.927] (**) Option "config_info" "udev:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.4/1-1.4:1.1/0003:1A2C:2124.0003/input/input3/event3"
[    63.927] (II) XINPUT: Adding extended input device "SEM USB Keyboard Consumer Control" (type: KEYBOARD, id 9)
[    63.927] (**) Option "xkb_rules" "evdev"
[    63.928] (**) Option "xkb_model" "pc105"
[    63.928] (**) Option "xkb_layout" "gb"
[    63.941] (II) evdev: SEM USB Keyboard Consumer Control: initialized for relative axes.
[    63.941] (WW) evdev: SEM USB Keyboard Consumer Control: ignoring absolute axes.
[    63.944] (**) SEM USB Keyboard Consumer Control: (accel) keeping acceleration scheme 1
[    63.945] (**) SEM USB Keyboard Consumer Control: (accel) acceleration profile 0
[    63.945] (**) SEM USB Keyboard Consumer Control: (accel) acceleration factor: 2.000
[    63.945] (**) SEM USB Keyboard Consumer Control: (accel) acceleration threshold: 4
[    64.046] (II) config/udev: Adding input device SEM USB Keyboard System Control (/dev/input/event4)
[    64.053] (**) SEM USB Keyboard System Control: Applying InputClass "evdev keyboard catchall"
[    64.055] (**) SEM USB Keyboard System Control: Applying InputClass "evdev keyboard catchall"
[    64.056] (II) Using input driver 'evdev' for 'SEM USB Keyboard System Control'
[    64.056] (**) SEM USB Keyboard System Control: always reports core events
[    64.056] (**) evdev: SEM USB Keyboard System Control: Device: "/dev/input/event4"
[    64.057] (--) evdev: SEM USB Keyboard System Control: Vendor 0x1a2c Product 0x2124
[    64.057] (--) evdev: SEM USB Keyboard System Control: Found keys
[    64.057] (II) evdev: SEM USB Keyboard System Control: Configuring as keyboard
[    64.058] (**) Option "config_info" "udev:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.4/1-1.4:1.1/0003:1A2C:2124.0003/input/input4/event4"
[    64.058] (II) XINPUT: Adding extended input device "SEM USB Keyboard System Control" (type: KEYBOARD, id 10)
[    64.058] (**) Option "xkb_rules" "evdev"
[    64.058] (**) Option "xkb_model" "pc105"
[    64.059] (**) Option "xkb_layout" "gb"

**Comment by UnchartedBull** [comment]
Have you tried the fix mentioned in this post: https://superuser.com/questions/806637/xauth-not-creating-xauthority-file? Also if Raspbian Desktop is working fine you can also start OctoDash from there via autostart.

**Comment by kekko7072** [comment]
Thank you so much 
now I'll try that solution. But for the moment can you tell me how to start octodash using auto start ? Because I tried using the standard command ./octodash but it says permission denied. And if I try using sudo it says the command doesn't exist.

**Comment by UnchartedBull** [comment]
just have a look at the installer script here: https://github.com/UnchartedBull/OctoDash/blob/main/scripts/install.sh#L749. There does seem to be an issue when starting via `octodash` due to a segfault, which is a known thing with electron apps.

**Comment by Snip3rita** [comment]
I have problems with the same screen. I tried hundreds of tutorial now.. :(

**Comment by kekko7072** [comment]
@UnchartedBull can you suggest some screen because this isn't working with OctoDash.

**Comment by UnchartedBull** [comment]
https://github.com/UnchartedBull/OctoDash/wiki/Supported-Devices#recommended-screens

**Comment by Snip3rita** [comment]
> @UnchartedBull can you suggest some screen because this isn't working with OctoDash.

In the end worked fine for me..I'm using a 5" Waveshare hdmi display :)

**Comment by kekko7072** [comment]
> > @UnchartedBull can you suggest some screen because this isn't working with OctoDash.
> 
> 
> 
> In the end worked fine for me..I'm using a 5" Waveshare hdmi display :)

Can you explain if you did something differente from the installation guide?

**Comment by kekko7072** [comment]
I still have this problem

**Comment by kekko7072** [comment]
![image](https://user-images.githubusercontent.com/32552589/112873148-8e92b800-90c1-11eb-83d9-c340e62719d9.jpeg) ANY IDEA?
