### ISSUE TITLE
Display sleep(on every menu and print screen)

### ISSUE THREAD

**Issue by GoldenGorilla123** [UnchartedBull/OctoDash#1432]
**Describe the solution you'd like**
an option to toggle display sleeping to be on every screen/menu etc

the same feature as when the printer isn't connected just on every screen

**Comment by UnchartedBull** [comment]
Not something I'll be working on. It would clutter up the UI. Feel free to create your own fork and add the buttons there (there is a function available to put the screen into sleep mode)
