### ISSUE TITLE
Use OctoDash on a regular monitor

### ISSUE THREAD

**Issue by sonic8101** [UnchartedBull/OctoDash#1450]
Hi,

 Is there any way to use OctoDash on a regular monitor for displaying things like remaining print time, temp, or any other useful info? 

Thank you,
Cristian

**Comment by mzilly02** [comment]
I'm using It right now on a 24 inch monitor.
You Just Need to remove "-- -nocursor" in ./.bashrc .
Removing this option the cursor can be viewed and you can use mouse click to interact with the interface.

**Comment by UnchartedBull** [comment]
You can also disable the touchscreen option in OctoDash to get a limited subset of functionality that does not require any user input at all.
