### ISSUE TITLE
Mhs 4 Inch Touchscreen doesnt work

### ISSUE THREAD

**Issue by Nickybroke** [UnchartedBull/OctoDash#1474]
Hey 
I have an Mhs 4.0 Inch Touchscreen. [Link](http://www.lcdwiki.com/MHS-4.0inch_Display-B) 
But it wont Show ne octodash. 
I do all you say in Troubleshooting 
And i usw Google no 3 hours. 
But all i do, nothing works. 
If i use an HDMI Screen ist works. 
![IMG_20210224_173605](https://user-images.githubusercontent.com/51791916/109035004-80b7d480-76c8-11eb-8bf0-ec4893b17bbc.jpg)

**Comment by UnchartedBull** [comment]
I think you posted the same thing over on discord and received a couple of answers. You also don't seem to have installed any drivers for your screen. If you still have Problems please reopen this issue.
