### ISSUE TITLE
Camera Preveiw

### ISSUE THREAD

**Issue by dirkvranckaert** [UnchartedBull/OctoDash#1498]
It would be useful to me (and I think many others) that you can easily preview all of your camera's.
Some guys use this outside of an enclosure and then it would be really useful to me to check the printer is ready before I launch my next print with Octodash. Also when setting up the printer (after maintenance for instance) it would be a nice feature to check the camera if it's positioned and focussing correctly.

I know that we can set up custom buttons but it would be nice to have direct button to access all of the camera's that are configured in Octoprint already (also with multicam support off course).

Even nicer would be to have the camera available during print (saw another ticker for custom buttons during print as well) for me personally that is less interesting atm.

**Comment by UnchartedBull** [comment]
Opening cameras will probably always be a custom action. There is #918 which will improve this functionality and then the custom actions on print screen which will also enable you to open the camera while printing. With the latest update you can define as many custom actions as you like, so you would be able to open multiple cameras from there.
