### ISSUE TITLE
multiple predefined actions at one button press?

### ISSUE THREAD

**Issue by DaStivi** [UnchartedBull/OctoDash#1505]
is there ah way allready to trigger more then one predefined action? (https://github.com/UnchartedBull/OctoDash/wiki/Custom-Actions#predefined-actions)

I'd like to send the poweroff command (M81) and also the pi-shutdown command.. so either there is some poll if the m81 has allready finished and poweroff is done, because the m81 command might wait until temp has cooled down.. but even then it would be ok, as marlin would do this on its own, even if octoprint isnt running any more i guess...

**Comment by UnchartedBull** [comment]
It's currently only possible to chain GCode commands. I've added it to the list of possible features for a future version
