### ISSUE TITLE
Allow OctoDash to wake when printer is not connected

### ISSUE THREAD

**Issue by strangecalling** [UnchartedBull/OctoDash#1507]
No issue found, just a feature request,

I would like to be able to access the control menu in order to shutdown the pi, either when setting up a new pi or when the printer is off.

(currently I have found a "special feature", tapping the screen repeatedly the screen wakes to show the OctoDash screen, it is displayed for a few seconds, not enough time to access the control menu and shut down the pi.)

I would like for the screen to wake for 10 seconds to allow shutdown, or open a prompt to shutdown when printer is not connected.

**Comment by UnchartedBull** [comment]
Already done with #1299. This will allow you to pull up the custom actions while sleeping. Will be included in the next release.
