### ISSUE TITLE
Disable "Cant Retrieve Folder" notification if "Back" button is pressed, or if folder data is successfully retrieved

### ISSUE THREAD

**Issue by scottmudge** [UnchartedBull/OctoDash#1520]
**Is your feature request related to a problem? Please describe.**
Often OctoDash cannot retrieve folder information from OctoPrint. Usually this happens around the time a file is sent via ethernet to OctoPrint, so perhaps OctoPrint is just busy parsing or reading the file, so it doesn't return folder data.

In any case, if I hit "back" and try again in OctoDash, it generally can view the files after the 2nd or 3rd retry. 

However, a few seconds after hitting the back button and successfully retrieving the folder data, OctoDash will still show a "Failed to retrieve folder" error notification from the prior attempts that timed out (I guess it's still trying to retrieve the folder data on a separate thread, even though I backed out in the UI). This error still shows up even if I've already backed out of them and successfully retried and started printing a file.

**Describe the solution you'd like**
Can this "Failed to Retrieve Folder" error be disabled if the back button is pressed, or if OctoDash successfully retrieves folder data in-between when the first failed attempt is made, and when the timeout occurs?

**Comment by UnchartedBull** [comment]
Should hopefully be fixed with #1438. If the error comes up again reopen this issue please.
