### ISSUE TITLE
The automatic installation doesn`t work..

### ISSUE THREAD

**Issue by lijiajian1994** [UnchartedBull/OctoDash#1526]
RaspberryPi 4B+Octopi v1.8 system.
Execute the automatic installation script,and after 2 seconds,it pops up directly.
May I ask why?
![微信截图_20210306181013](https://user-images.githubusercontent.com/50439415/110204023-e582e400-7eab-11eb-831e-dd8ee77383eb.png)

**Comment by lijiajian1994** [comment]
> 您的控制台屏幕截图未显示任何有用的信息，请发布正在发生的错误。

The first command is an error, after entering the automatic installation instruction, there is no error, can not continue to install, but directly jump back to the state of the input instruction.

**Comment by UnchartedBull** [comment]
please follow the manual installation instructions then: https://github.com/UnchartedBull/OctoDash/wiki/Installation#manual-installation. Could you please post the output of `echo $TERM` here as well?
