### ISSUE TITLE
Octodash screen is completely white

### ISSUE THREAD

**Issue by Michael1331-crypto** [UnchartedBull/OctoDash#1528]
Hello,
Today I set up my OctoDash. It worked completely fine for about 20 times. But then I turned it off and on again and now the screen stays completely white! 

I hope I don't have to disassemble everything again to flash it new :/

I use a Raspberry Pi 3B
elegoo 3,5" Touch display
newest OctoPrint version
newest OctoDash version

I was so happy it is working and now this ... I hope somebody can help me :)
thanks in advance :)

**Comment by UnchartedBull** [comment]
Is the console showing up during the boot or is the screen always white?

**Comment by Michael1331-crypto** [comment]
It is always white!

**Comment by UnchartedBull** [comment]
Then it's most likely a hardware issue. Please double check your wiring and try a different screen.
