### ISSUE TITLE
OctoDash does not boot

### ISSUE THREAD

**Issue by krisiks-jpg** [UnchartedBull/OctoDash#1582]
Hi, I have gone through many guides and similar threads, my problems is that OctoDash does not boot at all.

Xorg.0.log

> [    32.806] 
X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
[    32.809] Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
[    32.810] Current Operating System: Linux octopi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l
[    32.810] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=640 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=tty1 console=ttyAMA0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
[    32.816] Build Date: 15 January 2021  02:03:57PM
[    32.817] xorg-server 2:1.20.4-1+rpt2+deb10u3 (https://www.debian.org/support) 
[    32.818] Current version of pixman: 0.36.0
[    32.819] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    32.819] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    32.827] (==) Log file: "/var/log/Xorg.0.log", Time: Sat Mar 20 17:23:46 2021
[    32.840] (==) Using config directory: "/etc/X11/xorg.conf.d"
[    32.842] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    32.848] (==) No Layout section.  Using the first Screen section.
[    32.848] (==) No screen section available. Using defaults.
[    32.848] (**) |-->Screen "Default Screen Section" (0)
[    32.848] (**) |   |-->Monitor "<default monitor>"
[    32.854] (==) No device specified for screen "Default Screen Section".
	Using the first device section listed.
[    32.854] (**) |   |-->Device "Allwinner A10/A13 FBDEV"
[    32.854] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[    32.854] (==) Automatically adding devices
[    32.854] (==) Automatically enabling devices
[    32.854] (==) Automatically adding GPU devices
[    32.861] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    32.863] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    32.864] 	Entry deleted from font path.
[    32.864] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    32.864] 	Entry deleted from font path.
[    32.864] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    32.864] 	Entry deleted from font path.
[    32.864] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    32.864] 	Entry deleted from font path.
[    32.864] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    32.864] 	Entry deleted from font path.
[    32.864] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    32.864] 	Entry deleted from font path.
[    32.864] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	built-ins
[    32.864] (==) ModulePath set to "/usr/lib/xorg/modules"
[    32.864] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    32.864] (II) Loader magic: 0x1fdf80
[    32.864] (II) Module ABI versions:
[    32.864] 	X.Org ANSI C Emulation: 0.4
[    32.864] 	X.Org Video Driver: 24.0
[    32.864] 	X.Org XInput driver : 24.1
[    32.864] 	X.Org Server Extension : 10.0
[    32.866] (--) using VT number 2
[    32.866] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    32.867] (II) no primary bus or device found
[    32.867] (II) LoadModule: "glx"
[    32.869] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    32.931] (II) Module glx: vendor="X.Org Foundation"
[    32.931] 	compiled for 1.20.4, module version = 1.0.0
[    32.931] 	ABI class: X.Org Server Extension, version 10.0
[    32.931] (II) LoadModule: "fbturbo"
[    32.932] (II) Loading /usr/lib/xorg/modules/drivers/fbturbo_drv.so
[    32.936] (II) Module fbturbo: vendor="X.Org Foundation"
[    32.936] 	compiled for 1.20.3, module version = 0.5.1
[    32.936] 	Module class: X.Org Video Driver
[    32.936] 	ABI class: X.Org Video Driver, version 24.0
[    32.936] (II) FBTURBO: driver for framebuffer: fbturbo
[    32.944] (WW) Falling back to old probe method for fbturbo
[    32.944] (II) Loading sub module "fbdevhw"
[    32.944] (II) LoadModule: "fbdevhw"
[    32.944] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    32.947] (II) Module fbdevhw: vendor="X.Org Foundation"
[    32.947] 	compiled for 1.20.4, module version = 0.0.2
[    32.947] 	ABI class: X.Org Video Driver, version 24.0
[    32.947] (II) FBTURBO(0): using /dev/fb0
[    32.947] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[    32.947] (II) FBTURBO(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[    32.947] (==) FBTURBO(0): Depth 24, (==) framebuffer bpp 32
[    32.947] (==) FBTURBO(0): RGB weight 888
[    32.947] (==) FBTURBO(0): Default visual is TrueColor
[    32.947] (==) FBTURBO(0): Using gamma correction (1.0, 1.0, 1.0)
[    32.947] (II) FBTURBO(0): hardware: BCM2708 FB (video memory: 1200kB)
[    32.947] (DB) xf86MergeOutputClassOptions unsupported bus type 0
[    32.947] (**) FBTURBO(0): Option "fbdev" "/dev/fb0"
[    32.947] (**) FBTURBO(0): Option "SwapbuffersWait" "true"
[    32.948] (II) FBTURBO(0): processor: Unknown
[    32.948] (II) FBTURBO(0): checking modes against framebuffer device...
[    32.948] (II) FBTURBO(0): checking modes against monitor...
[    32.948] (II) FBTURBO(0): Virtual size is 640x480 (pitch 640)
[    32.948] (**) FBTURBO(0):  Built-in mode "current"
[    32.948] (==) FBTURBO(0): DPI set to (96, 96)
[    32.948] (II) Loading sub module "fb"
[    32.948] (II) LoadModule: "fb"
[    32.948] (II) Loading /usr/lib/xorg/modules/libfb.so
[    32.954] (II) Module fb: vendor="X.Org Foundation"
[    32.955] 	compiled for 1.20.4, module version = 1.0.0
[    32.955] 	ABI class: X.Org ANSI C Emulation, version 0.4
[    32.974] (II) FBTURBO(0): using backing store heuristics
[    32.983] (II) FBTURBO(0): can't load 'g2d_23' kernel module
[    32.984] (II) FBTURBO(0): failed to enable the use of sunxi display controller
[    32.984] (II) FBTURBO(0): No sunxi-g2d hardware detected (check /dev/disp and /dev/g2d)
[    32.984] (II) FBTURBO(0): G2D hardware acceleration can't be enabled
[    32.984] (II) FBTURBO(0): enabled fbdev copyarea acceleration
[    32.984] (==) FBTURBO(0): Backing store enabled
[    32.992] (==) FBTURBO(0): DPMS enabled
[    32.992] (II) FBTURBO(0): failed to enable hardware cursor
[    32.992] (II) FBTURBO(0): no 3D acceleration because the driver has been compiled without libUMP
[    32.992] (II) FBTURBO(0): if this is wrong and needs to be fixed, please check ./configure log
[    32.994] (II) Initializing extension Generic Event Extension
[    32.994] (II) Initializing extension SHAPE
[    32.995] (II) Initializing extension MIT-SHM
[    32.996] (II) Initializing extension XInputExtension
[    33.000] (II) Initializing extension XTEST
[    33.001] (II) Initializing extension BIG-REQUESTS
[    33.002] (II) Initializing extension SYNC
[    33.003] (II) Initializing extension XKEYBOARD
[    33.004] (II) Initializing extension XC-MISC
[    33.004] (II) Initializing extension SECURITY
[    33.005] (II) Initializing extension XFIXES
[    33.006] (II) Initializing extension RENDER
[    33.007] (II) Initializing extension RANDR
[    33.008] (II) Initializing extension COMPOSITE
[    33.010] (II) Initializing extension DAMAGE
[    33.011] (II) Initializing extension MIT-SCREEN-SAVER
[    33.012] (II) Initializing extension DOUBLE-BUFFER
[    33.013] (II) Initializing extension RECORD
[    33.013] (II) Initializing extension DPMS
[    33.014] (II) Initializing extension Present
[    33.015] (II) Initializing extension DRI3
[    33.015] (II) Initializing extension X-Resource
[    33.016] (II) Initializing extension XVideo
[    33.016] (II) Initializing extension XVideo-MotionCompensation
[    33.017] (II) Initializing extension SELinux
[    33.017] (II) SELinux: Disabled on system
[    33.017] (II) Initializing extension GLX
[    33.018] (II) AIGLX: Screen 0 is not DRI2 capable
[    34.408] (II) IGLX: Loaded and initialized swrast
[    34.409] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[    34.409] (II) Initializing extension XFree86-VidModeExtension
[    34.411] (II) Initializing extension XFree86-DGA
[    34.412] (II) Initializing extension XFree86-DRI
[    34.415] (II) Initializing extension DRI2
[    34.693] (II) config/udev: Adding input device ADS7846 Touchscreen (/dev/input/event0)
[    34.693] (**) ADS7846 Touchscreen: Applying InputClass "evdev touchscreen catchall"
[    34.693] (**) ADS7846 Touchscreen: Applying InputClass "evdev touchscreen catchall"
[    34.693] (**) ADS7846 Touchscreen: Applying InputClass "calibration"
[    34.693] (II) LoadModule: "evdev"
[    34.693] (II) Loading /usr/lib/xorg/modules/input/evdev_drv.so
[    34.707] (II) Module evdev: vendor="X.Org Foundation"
[    34.707] 	compiled for 1.20.3, module version = 2.10.6
[    34.707] 	Module class: X.Org XInput Driver
[    34.707] 	ABI class: X.Org XInput driver, version 24.1
[    34.707] (II) Using input driver 'evdev' for 'ADS7846 Touchscreen'
[    34.707] (**) ADS7846 Touchscreen: always reports core events
[    34.708] (**) evdev: ADS7846 Touchscreen: Device: "/dev/input/event0"
[    34.708] (--) evdev: ADS7846 Touchscreen: Vendor 0 Product 0
[    34.708] (--) evdev: ADS7846 Touchscreen: Found absolute axes
[    34.708] (--) evdev: ADS7846 Touchscreen: Found x and y absolute axes
[    34.708] (--) evdev: ADS7846 Touchscreen: Found absolute touchscreen
[    34.708] (**) Option "SwapAxes" "1"
[    34.708] (II) evdev: ADS7846 Touchscreen: Configuring as touchscreen
[    34.708] (**) evdev: ADS7846 Touchscreen: YAxisMapping: buttons 4 and 5
[    34.708] (**) evdev: ADS7846 Touchscreen: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    34.708] (**) Option "config_info" "udev:/sys/devices/platform/soc/3f204000.spi/spi_master/spi0/spi0.1/input/input0/event0"
[    34.708] (II) XINPUT: Adding extended input device "ADS7846 Touchscreen" (type: TOUCHSCREEN, id 6)
[    34.708] (II) evdev: ADS7846 Touchscreen: initialized for absolute axes.
[    34.709] (**) ADS7846 Touchscreen: (accel) keeping acceleration scheme 1
[    34.709] (**) ADS7846 Touchscreen: (accel) acceleration profile 0
[    34.709] (**) ADS7846 Touchscreen: (accel) acceleration factor: 2.000
[    34.709] (**) ADS7846 Touchscreen: (accel) acceleration threshold: 4
[    34.712] (II) config/udev: Adding input device ADS7846 Touchscreen (/dev/input/mouse0)
[    34.712] (**) ADS7846 Touchscreen: Applying InputClass "calibration"
[    34.712] (II) No input driver specified, ignoring this device.
[    34.712] (II) This device may have been added with another device file.

Entering `ratpoison` says 
> Can't open display

Console says
`
(EE)
Fatal server error:
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE)
`
Deleted .X0-lock, didnt't change anything.

Startx and console says

> X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
Current Operating System: Linux octopi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l
Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=640 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=tty1 console=ttyAMA0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
Build Date: 15 January 2021  02:03:57PM
xorg-server 2:1.20.4-1+rpt2+deb10u3 (https://www.debian.org/support)
Current version of pixman: 0.36.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Sat Mar 20 17:42:02 2021
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
modprobe: FATAL: Module g2d_23 not found in directory /lib/modules/5.10.17-v7+
[13540:0320/174202.526054:FATAL:electron_main_delegate.cc(254)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap
xinit: connection to X server lost
waiting for X server to shut down XIO:  fatal IO error 4 (Interrupted system call) on X server ":1"
after 157 requests (157 known processed) with 0 events remaining.
(II) Server terminated successfully (0). Closing log file.

Have done many other manipulations, install, reinstalls and updates, did not help at all. Can anyone say in which direction to go? Thank You!

**Comment by krisiks-jpg** [comment]
Tried 
`export DISPLAY=:0`
And then 
`ratpoison`
Console says: 
> ratpoison: There can be only ONE.

LCD is 3.5inch GoodTFT display.

**Comment by Will-wastelander** [comment]
Did you install the LCD drivers ?

https://github.com/goodtft/LCD-show

**Comment by pciavald** [comment]
@krisiks-jpg  it seems you're somehow launching X twice. Can you please post all the commands you run to get there ?

**Comment by JeremyProffitt** [comment]
This is identical to my issue.  https://github.com/UnchartedBull/OctoDash/issues/1632

my testing was done with octopi, there are not two copies of x running, review the above ticket, this is a chromium issue with a newer release.
