### ISSUE TITLE
File sort by date and thumbnails

### ISSUE THREAD

**Issue by mpalm0508** [UnchartedBull/OctoDash#1583]
**Describe the bug**
I am running a local build from merge cb70bc4.  When files are sorted by date month is reversed.  For instance a file from February 20th shows in the list before a file from March 10 when being sorted by descending.  If you sort by Ascending it is the exact reverse.  I can get correct sort by modifying line 59 in files.octoprint.services.ts to the following.  However I do not know what all affect that has.  

date: this.conversionService.convertDateToString(new Date(fileOrFolder.date * 1)),

The second issue is while printing files with thumbnails the thumbnail is of the next file in the list.  So If I print file "A" the thumbnail for file "B" is shown.

I know there were a lot of changes to get websockets running.  I just wanted to bring up a couple bugs I have found. 

Mike

**Comment by UnchartedBull** [comment]
Thanks for this! Your fix does seem to work and I didn't saw anything that got broken with it :)
