### ISSUE TITLE
Add control for E axis

### ISSUE THREAD

**Issue by pciavald** [UnchartedBull/OctoDash#1591]
**Is your feature request related to a problem? Please describe.**

We need to be able to move the E axis from the dashboard, which is the extruder motor moving the filament.

**Describe the solution you'd like**

We can implement in the Control screen a second vertical jog like for Z, but for E. Should it be made in the component directly or in an additional module ? (i did not check the modules structure yet, maybe it's not possible).

**Comment by UnchartedBull** [comment]
I think extruder axis movement should be done via Custom Actions. It will just clutter up the control UI (which already has quite a lot going on). If you want to implement this in your custom fork the control component is the place to do it.
