### ISSUE TITLE
octodash values not updating since websocket update

### ISSUE THREAD

**Issue by pciavald** [UnchartedBull/OctoDash#1592]
**Describe the bug**

hotend, bed and fan values not updating, print status not updating.

**To Reproduce**

- clone latest main (c26a901)
- package app
- install deb
- start and connect
- click hotend, set temperature
- temperature is set correctly and appears in octoprint, but octodash is not updated
- start a print from octoprint, print view does not show up in octodash

**Expected behavior**

- hotend, bed and fan values should be updated on octodash screen when they change on the machine
- octodash should show the print screen when a print is running

**General Information:**
 - pi3B+, pi4 (armv7l)
 - raspios
 - octodash revision: c26a901
 - OctoPrint Version 1.5.3

**Comment by UnchartedBull** [comment]
Known bug on the latest master, will have a look at a fix later.

**Comment by pciavald** [comment]
Do you have an ETA ? need help ?

**Comment by UnchartedBull** [comment]
Will be fixed eod.
