### ISSUE TITLE
specify nodejs and npm versions

### ISSUE THREAD

**Issue by pciavald** [UnchartedBull/OctoDash#1617]
**Is your feature request related to a problem? Please describe.**

it seems we've encountered errors because we're using npm 6.14.11 and you're probably using npm 7 as the package-lock.json says `lockfileVersion: 2`

**Describe the solution you'd like**

in CONTRIBUTING.md, could you please add the npm and nodejs versions you are using to do the builds ?

**Comment by pciavald** [comment]
I still have a difference from your setup i think, see the difference of package-lock.json in #1610

**Comment by UnchartedBull** [comment]
Which os are you using? Different operating systems can cause differences in the package-lock iirc.

**Comment by pciavald** [comment]
Fedora 33 workstation

**Comment by UnchartedBull** [comment]
I'm using a Mac so that is probably why there are still some differences. I think we can safely ignore those though.

**Comment by pciavald** [comment]
until we find out, i think it's best that when you merge a PR that modifies package.json, you run `npm install` and commit package-lock.json before merging

**Comment by UnchartedBull** [comment]
Sounds like a plan 👍
