### ISSUE TITLE
Prusa Printer new firmware OctoPrint compatibility additions

### ISSUE THREAD

**Issue by Photogad** [UnchartedBull/OctoDash#1619]
I'm not sure if you've seen it, but the latest Prusa Printer firmware adds a lot of new functions and support for OctoPrint prints, such as

- Long Filenames
- New GCode Commands for all sorts of things
- New information can be displayed
- etc

https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.10.0-RC1

I'm not sure if this needs to be added on the octoprint side, the octodash side, or what. But just some ideas for new features in v3 of octodash.

**Comment by UnchartedBull** [comment]
Needs to be implemented in OctoPrint first and most of the stuff will then automatically apply to OctoDash as well (i.e. longer filenames on SD Card). Closing this here for now, if there is a specific issue your're looking for and it is already implemented in OctoPrint please open a new issue :) Thanks for the info!
