### ISSUE TITLE
Dual Nozzle hotend control needed to make this a great plugin

### ISSUE THREAD

**Issue by Jasontwd** [UnchartedBull/OctoDash#1625]
HI,
Im needing to show 2 nozzles and control there of for this plugin.
Has There been any further updates on this.
Im working on a farm of printers that run on octodash and need that control.

cheers
jason

**Comment by UnchartedBull** [comment]
duplicate of #779. There wasn't any work done on this issue so far though.

**Comment by mattydboom** [comment]
Shame, I (and many others) have dual nozzle printers, and being able to load, unload, and preheat specific nozzles would be a great addition. Before researching this post I thought it was bound to already exist, but seems not. Gets a vote from me!
