### ISSUE TITLE
Rotation of iframe for example webcam

### ISSUE THREAD

**Issue by hawkeyexp** [UnchartedBull/OctoDash#1643]
if possible it would be nice if the iframe can be rotated - in my casre i have a nozzle cam which needs a rotation of 90° but on cam side it is not possible

PS: for sure it's used via custom command

**Comment by UnchartedBull** [comment]
Not possible, at least not dynamically, so I won't be able to merge this into main, since most people rely on the webpage being in the normal orientation.

Are you using mjpeg streamer? Because that actually does support rotation of the image.
