### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by kekko7072** [UnchartedBull/OctoDash#1647]
**What doesn't work?**
I have tried several times to install octodash in my raspberry pi. 3 but I have alwais problem. Pleas help me.

**What did you already try?**
A clear and concise description of what you tried to make OctoDash work.

**General Information:**
Raspberry Pi 3 model B, LCD https://www.waveshare.com/wiki/5inch_HDMI_LCD
OctoPi and desktop support
OctoPrint version : 1.5.2
OctoPi version : 0.18.0

**Comment by kekko7072** [comment]
https://github.com/UnchartedBull/OctoDash/issues/1388#issuecomment-809548547

**Comment by kekko7072** [comment]
![image](https://user-images.githubusercontent.com/32552589/113509160-59201b80-9554-11eb-8528-55334c5f2fd1.jpeg)

**Comment by kekko7072** [comment]
I tried all the guide online but nothing works, I use a completely fresh distro of octopi but with no results.

**Comment by tobsiyo** [comment]
Looks like it's the same problem like i had. Octodash isn't compatible with this RPi -> illegal instruction.

**Comment by kekko7072** [comment]
> Looks like it's the same problem like i had. Octodash isn't compatible with this RPi -> illegal instruction.

Did you changed monitor? So what monitor fidi you buy. @UnchartedBull this should be added to the info of the project that RPi monitor are incompatible.

**Comment by tobsiyo** [comment]
Your Raspberry Pi, not your Screen.

**Comment by kekko7072** [comment]
But it's new? What should I buy? It pi 3 model b

**Comment by pciavald** [comment]
@kekko7072 can you please detail how you installed octodash ? illegal instructions looks like you're trying to run the wrong version of octoprint, ie not the armv7l version.

**Comment by kekko7072** [comment]
I downloaded from website, installed, logged in, enabled in settings auto login, run apt upgrade & update the install octodash using command. then to fix I tried to install x init and x server

**Comment by kekko7072** [comment]
If you suggest me step by step I retry. Reilly glad to be helped

**Comment by pciavald** [comment]
@kekko7072 can you please post the output of `uname -a` ?

**Comment by kekko7072** [comment]
> @kekko7072 can you please post the output of `uname -a` ?
Yes ``Linux octopi 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux Linux octopi 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux Linux octopi 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux ``

**Comment by pciavald** [comment]
@UnchartedBull can confirm but i think there's no automated build for your architecture, `armv6l` (i'm guessing pi zero), so the installer [downloaded and installed](https://github.com/UnchartedBull/OctoDash/blob/main/scripts/install.sh#L676) the armv7l version instead.

After a quick research it seems electron, the base framework of octodash, does not offer builds for armv6 unfortunately. It seems OctoDash can thus not be installed on raspberry pi zero.

**Comment by pciavald** [comment]
I forgot you mentioned that you're using `Raspberry Pi 3 model B`, here's the list of armv6 devices that are incompatible while electron can't build for armv6:

![image](https://user-images.githubusercontent.com/3384097/113698556-e0949880-96d4-11eb-803c-586ec01317d6.png)

**Comment by kekko7072** [comment]
> @UnchartedBull can confirm but i think there's no automated build for your architecture, `armv6l` (i'm guessing pi zero), so the installer [downloaded and installed](https://github.com/UnchartedBull/OctoDash/blob/main/scripts/install.sh#L676) the armv7l version instead.
> 
> 
> 
> After a quick research it seems electron, the base framework of octodash, does not offer builds for armv6 unfortunately. It seems OctoDash thus can not be installed on armv6 devices.
> 
> 
> 
> Here's a list of raspberry pi armv6 devices:
> 
> ![image](https://user-images.githubusercontent.com/3384097/113698818-23567080-96d5-11eb-8ac2-e208736034fb.png)
> 
> 
> 
> You mention that you use raspberry 3B, are you sure about the model? It's written on the top of the board. The table seems to tell that Raspberry 3B should be armv8.
> 
> 

Yes it is a Raspberry pi model B+ v1.2

![image](https://user-images.githubusercontent.com/32552589/113701454-77168900-96d8-11eb-89b4-efa1685abdfe.jpeg)

**Comment by pciavald** [comment]
Your board is a `RPi 1 Model B+` armv6 from 2014, not a `RPi 2 Model B v1.2` nor a `RPi 3 Model B` from 2016.

I'm sorry, but i think OctoDash is currently incompatible with your hardware. It should probably be noted in the documentation.

**Comment by kekko7072** [comment]
Now I understand why a month ago I also tried installing on raspberry pi zero and didn't work. In fact it is not officially supported by octopi but it works (the problem is when you use webcam stream), but as you show me is not compatible with electron and so with OctoDash, correct? 

What should I do with Raspberry Pi Model B +?
Should I purchase another hardware to make it work or try reinstall?

**Comment by pciavald** [comment]
The incompatibility is in that OctoDash uses Electron to create the window that shows the app, and Electron can build for most platforms, but it seems not for armv6. Any device on the table that is armv7 or armv8 will work.

**Comment by kekko7072** [comment]
Ok clear thank you so much for the patience and knowledge. I will purchase the new hardware. Witch do you think is better? This issue can be closed.

**Comment by pciavald** [comment]
I think it should be documented before closing.

RPi 4 is the best of the line currently, RPi 3B+ will do very fine too.

**Comment by UnchartedBull** [comment]
Was already in the wiki (second paragraph): https://github.com/UnchartedBull/OctoDash/wiki/Supported-Devices. Just updated the text a little to make it more clear.
