### ISSUE TITLE
Octodash with mutliple octoprint instances

### ISSUE THREAD

**Issue by strangecalling** [UnchartedBull/OctoDash#1651]
Feature inqury

Can Octodash switch between Octoprint instances if it has been setup for two or more printers?

Following on from Chris' basement video "OctoPi 0.18 - Multi Printers & Cameras On 1 Pi - Chris's Basement".

It would be nice if OctoDash could switch from one octoprint instance to another without rebooting.

**Comment by UnchartedBull** [comment]
duplicate of #1148.
