### ISSUE TITLE
problem installing octodash

### ISSUE THREAD

**Issue by odygr** [UnchartedBull/OctoDash#1655]
i'm trying to install the octodash on my raspberry pi3 using the command

bash <(wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/install.sh)

and i get the following

The following packages will be upgraded:
  libx11-6
1 upgraded, 154 newly installed, 0 to remove and 178 not upgraded.
Need to get 0 B/63.0 MB of archives.
After this operation, 291 MB of additional disk space will be used.
apt-listchanges: Reading changelogs...
debconf: Perl may be unconfigured (vars.pm did not return a true value at /usr/share/perl/5.24/base.pm line 5.
BEGIN failed--compilation aborted at /usr/share/perl/5.24/base.pm line 5.
Compilation failed in require at /usr/share/perl5/Debconf/Log.pm line 7.
BEGIN failed--compilation aborted at /usr/share/perl5/Debconf/Log.pm line 7.
Compilation failed in require at (eval 1) line 4.
BEGIN failed--compilation aborted at (eval 1) line 4.
) -- aborting
Selecting previously unselected package fontconfig.
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'python-dev' contains empty filename
E: Sub-process /usr/bin/dpkg returned an error code (2)

**Comment by pciavald** [comment]
Hi @odygr, is this a fresh installation ? It seems the issue is not with OctoDash but with your package manager. Can you please run these commands:

```bash
sudo apt update
sudo apt dist-upgrade
sudo dpkg reconfigure -a
```
