### ISSUE TITLE
"feedrate" unclear, should be "speed"

### ISSUE THREAD

**Issue by pciavald** [UnchartedBull/OctoDash#1662]
**Is your feature request related to a problem? Please describe.**

in the in-print controls, "feedrate" does control the feedrate, but in a way that is linked to movement speed, ie it does adapt the movement of the machine to the selected feedrate, keeping the original movement/feed ratio. A real "feedrate" control would be expected to change this ratio and the amount of plastic being extruded for the same movement, as this command changes the speed of print (and thus the feedrate), not the amount of plastic being extruded for that movement.

**Describe the solution you'd like**

Change the denomination of the setting from "feedrate" to "speed".

**Comment by UnchartedBull** [comment]
I tried using the OctoPrint jargon there. In an early version there was feedrate and flowrate accessible in the adjust screen, so ti was more clear what did what. I think with the new approach of distancing OctoDash from OctoPrint a little and making it open for other Printer Softwares it might make sense to also simplify the terminology here.
