### ISSUE TITLE
Constantly get 403 Forbidden on start-up

### ISSUE THREAD

**Issue by hawker800mech** [UnchartedBull/OctoDash#1724]
**Describe the bug**
Get 403 FORBIDDEN on start-up for Can't Retrieve: Layer Progress, Retrieve Jobs, Print Status. Sometimes rebooting clears it, and sometimes it doesn't. Octoprint still functions from my laptop, but the Pi touchscreen does not. If I remove and reinstall OctoDash it works for a little while, but ultimately starts with the 403 Forbidden messages again.

**General Information:**
Current Octoprint and OctoDash versions.

**Comment by UnchartedBull** [comment]
Will be fixed with v3.0.0.
