### ISSUE TITLE
How to update to get the language files

### ISSUE THREAD

**Issue by GCYR3278** [UnchartedBull/OctoDash#1725]
Hello,

How can I update OctoDash with the language files? I tried a manual update (2.1.2) but it seems that these files were not installed? Have I forgotten something?

I tried uninstalling and reinstalling OctoDash, no change.

General Information:
 - Hardware: Raspberry Pi 4
 - OctoDash Version 2.1.2
 - OctoPrint - OctoPi Version 0.18.0
 - My location is defined on fr_FR.UTF-8, my OS is in french.

Thanks

**Comment by pciavald** [comment]
Hi,

The multilanguage feature will be released in v3.0.0. If you want to give it a try before, you can clone and build the main branch of this repo.

**Comment by GCYR3278** [comment]
OK, I misunderstood.  I will wait for v3.  I've only been using a raspberry for 2 weeks, I don't have the skills to do more yet now. Thanks.
