### ISSUE TITLE
Can add Traditional Chinese(Taiwan)~

### ISSUE THREAD

**Issue by lift6542** [UnchartedBull/OctoDash#1733]
Can add Traditional Chinese(Taiwan)~?

I need to translate the language for other users' hobbies,Let more people use. If need help,can tell me. 

discord id :YayYay

**Comment by UnchartedBull** [comment]
Hi, that would be great! Please have a look at this file to learn how to create the translation files: https://github.com/UnchartedBull/OctoDash/blob/main/CONTRIBUTING.md. Feel free to open a PR once you feel ready :)
