### ISSUE TITLE
At the end of a print, display print report instead of home screen

### ISSUE THREAD

**Issue by pciavald** [UnchartedBull/OctoDash#1750]
**Is your feature request related to a problem? Please describe.**

When a print is done, there's no way to see the total real print time.

**Describe the solution you'd like**

At the end of the print, stay on the print screen or display a new screen with print stats. It could eventually feature the number of errors or temperature graph or the such.

**Comment by UnchartedBull** [comment]
Merging with #693, since the print summary could also over a "print again" button.
