### ISSUE TITLE
Disable scrollbars for iframes

### ISSUE THREAD

**Issue by hawkeyexp** [UnchartedBull/OctoDash#1781]
it would be nice of you can disable the scrollbars for iframes - for example my cam image is shown with a vetical scrollbar - i tried to resize my cam image but no change - i think generally disabling scollbars is ok for embedded content :-)

**Comment by jneilliii** [comment]
I know you ar eusing a remote OctoDash Install, but if you have OctoDash Companion plugin installed it includes a webcam view that will auto-size your camera to fit the page, so you don't get scrollbars at all. You just have to use the ifram address `http://ip or name of pi/plugin/octodashcompanion/webcam`

**Comment by hawkeyexp** [comment]
You are right - it could be a solution if you implement multicam support :-) I wan't to use my nozzle cam which is the second one not the default :-)

**Comment by jneilliii** [comment]
What is the other plugin that you use to enable multicam support within the OctoPrint UI. I could detect that and allow for selecting the stream possibly...feel free to open a Feature Request on the plugin repo for that.

**Comment by UnchartedBull** [comment]
This might break the integration for some people that rely on the scrolling features. For camera views this will be tracked in #918 (which should offer a better experience than opening the mjpeg website and no scrollbars), a general option to disable scrollbars won't be useful IMHO.
