### ISSUE TITLE
Add optional fixed position for filament change

### ISSUE THREAD

**Issue by hawkeyexp** [UnchartedBull/OctoDash#1793]
I'm using the filament change without M600. Caused by my case it's sometimes not really comfortable to change the filament and reaching the clamb of the extruder if the printhead is not liftet up to a special level etc. to reach the extruder clamb during the portal.
It would be nice if you can add the option for a fixed xyz position to change the filament.

**Comment by UnchartedBull** [comment]
This seems like a good idea. Defining a fixed position probably is not feasible though, since this could cause issue when the printer is not homed. I'm thinking more of some Custom G-Code that could be triggered if the user clicks on an icon in the heating screen.

**Comment by hawkeyexp** [comment]
yes i agree - i think best solution should be starting the process with an g28 to ensure correct positions.

By the way: if pausing a print printhead stays on last position and is melting the printed parts - possible a second point where an action is needed th lift and move the head - in this step it could interact with the filament change option but for such a behaviour last position must be saved to ensure restart is on same position etc. - a bit complex to handle this correctly

**Comment by jneilliii** [comment]
If the firmware supports position reporting you could utilize the on after pause and before resume gcode scripts possibly? The docs have a good example of this. 

https://docs.octoprint.org/en/master/features/gcode_scripts.html#more-nifty-pause-and-resume

**Comment by hawkeyexp** [comment]
@jneilliii you ae right - forgot this option :-) Trying out...

**Comment by hawkeyexp** [comment]
working ...

**Comment by mwilgar** [comment]
I see this in the release notes as part of 2.3.0, but I can't find anywhere to set the position coordinates.
