### ISSUE TITLE
Cant retrieve Job Status

### ISSUE THREAD

**Issue by Kodiak437** [UnchartedBull/OctoDash#1797]
Im Tring to get OctoDash working on my FlashForge Creator and am seeing 2 issues.  

From octoprint everything works fine, job status, control etc.   When i print, i get cant retrieve job status.  For the Flashforge i know it only supports printing from the SD card via octoprint.  Im also fine with it not showing the status in octodash as i use it more for local control, preheating.  Is there away to get it to stop showing this message?

I did try octoscreen it it was able to show the job status, so not sure if i have something configure wrong for dash..

The other issue i have is it is only showing the 1 toolhead.  I understand the it does not show both.  But is there a way to switch to show the other?  It looks like it just select the first one (0) and my primary is (1)

Hardware - pi4
OctoPrint version : 1.6.1
OctoPi version    : 0.18.0

Thanks in advance for any help.

**Comment by UnchartedBull** [comment]
Please try the beta (in the discord) or wait for v2.2.0 release (should be released later today). If the issue still persists with those version please reopen.
