### ISSUE TITLE
OctoDash autoconnect on load

### ISSUE THREAD

**Issue by Qualith** [UnchartedBull/OctoDash#1845]
**What doesn't work?**
I cannot make that octodash autoconnects to the printer after power mi Pi on, but later just by touching the screen works flawlesly.

**What did you already try?**
Look for some timeout params to make it higger or any other params without any success.

**General Information:**
 - Raspi 3B
 - OctoPrint 1.6.1 Python 2.7.16 OctoPi 0.17.0
 - OctoDash 2.2.0

**Additional context**
Via web, octoprint is connected without problem, I just cannot make OctoDash to connect on load, it enters on Sleep mode.
Then I touch the screen and OctoDash connects without any problem.

I'm sorry if it is already answered but I could't find anything about it.

Thank you.

**Comment by UnchartedBull** [comment]
Usually OctoDash should automatically connect once the printer connection is established. This is the first time I'm hearing that this isn't working properly. You are 100% sure that everything is connected in OctoPrint?

You could try adding a delay to your `~/.xinitrc` with `sleep 10` (for a 10s delayed start, can be any other number) and check whether that fixes your issue. The sleep command should be placed before `octodash of course`

**Comment by Qualith** [comment]
Thanks!
