### ISSUE TITLE
Link in install instructions

### ISSUE THREAD

**Issue by treymd** [UnchartedBull/OctoDash#1847]
It appears that the install instructions contain an outdated URL being passed to wget.  I guess github switched up how to access raw files maybe?

new version:  bash <(wget -qO - https://raw.githubusercontent.com/UnchartedBull/OctoDash/main/scripts/install.sh)

**Comment by thegarbz** [comment]
This could possibly have been a temporary problem with Github. Are you able to reproduce it now?
wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/install.sh works just fine here and wget correctly follows the redirect to the URL you listed.

**Comment by treymd** [comment]
Yup, works now.  Must have been a issue with github last night
