### ISSUE TITLE
After Update to 2.2.0  Fan-speed not displayed

### ISSUE THREAD

**Issue by Sabifabi** [UnchartedBull/OctoDash#1855]
Command send via octoprint or printer or otodash fan starts turning on but always 0% are displayed. Works fine before updating

**Comment by komandrik** [comment]
I confirm. I am getting the same error.

**Comment by jneilliii** [comment]
This is because DisplayLayerProgress plugin is either not installed, or doesn't have the websocket option enabled.

**Comment by komandrik** [comment]
> This is because DisplayLayerProgress plugin is either not installed, or doesn't have the websocket option enabled.

If I turn off DisplayLayerProgress then there is a dash on the screen instead of the fan speed percentage. When DisplayLayerProgress is on, the screen is always 0. It doesn't matter if the fan is on or not.

**Comment by Sabifabi** [comment]
> This is because DisplayLayerProgress plugin is either not installed, or doesn't have the websocket option enabled.

Enable the websocket option worked fine. Thanks for your fast support

**Comment by UnchartedBull** [comment]
Check #1827.
