### ISSUE TITLE
Controll manual extrusion - "feature request"

### ISSUE THREAD

**Issue by dumbozo** [UnchartedBull/OctoDash#1883]
Next to controlling x, y an z-axis it would be nice if extrusion could be manual controlled.
Easy to clean hot-end when swapping color and also when checking e-steps.
Icon buttons could be next to Z-axis buttons.

**Comment by Jozer99** [comment]
Definitely!  I would like to be able to manually control temperatures and extrusion outside of a print job or filament change.  This could be added easily to the "Control" section on the home page, there is plenty of screen real estate left for it.

**Comment by UnchartedBull** [comment]
#1623
