### ISSUE TITLE
Octodash not found / Xinit: connection to server lost

### ISSUE THREAD

**Issue by N3orun** [UnchartedBull/OctoDash#1884]
Hi, 

I successfully installed, verified each step 3 times again, tried the troubleshooting hints. Still stuck after reboot. 

Raspi Pi 3 modell: [https://philipp.d.pr/QaGLbF/IHGowhOAUd](url)

Error Screenshot. [https://philipp.d.pr/rv9ZLh/sh82fvvKjl](url)

Using with a BIGTREETECH PI TFT50 Touch Display

HDMI is only showing a rainbow after boot. 
 
Any Ideas? 
![IMG_0751 (1)](https://user-images.githubusercontent.com/67067179/120222153-c8a64480-c23f-11eb-9b98-79dcee861920.jpg)
![image](https://user-images.githubusercontent.com/67067179/120227841-42dbc680-c24a-11eb-8d7a-9c0dce3cf8fe.jpeg)

**Comment by N3orun** [comment]
![IMG_0751 (1)](https://user-images.githubusercontent.com/67067179/120222072-af9d9380-c23f-11eb-8fe6-2152bb71cfb2.jpg)

**Comment by UnchartedBull** [comment]
It says that `octodash` isn't installed. Please manually install the `.deb` file from the release page with `dpkg`. Last two steps from here: https://github.com/UnchartedBull/OctoDash/wiki/Installation#manual-installation

**Comment by N3orun** [comment]
seems like updating octopi to the latest version before running the script caused an issue. ran again on a fresh sd and without configuring or updating octopi before and it seems to boot at the moment. Thanks anyway! 

Keep up the great work! Danke!

**Comment by EmEiBee** [comment]
Problem is back:
Same here with the actual stuff from today on PI4b-4gb
