### ISSUE TITLE
Can't install update (cannot change locale)

### ISSUE THREAD

**Issue by WouterVanGoey** [UnchartedBull/OctoDash#1911]
**What doesn't work?**
Connecting over VNC to my Pi and trying to install the update to v2.2.0 gives me this error;

![Screenshot 2021-06-04 111817](https://user-images.githubusercontent.com/6655152/120779094-03052f80-c527-11eb-946f-e56351b3bda1.png)

**General Information:**
 - Raspberry Pi 3B+
 - OctoPi
 - OctoDash Version v2.1.2

**Comment by jneilliii** [comment]
Check this pinned issue... there are fixes described. 

https://github.com/UnchartedBull/OctoDash/issues/1818
