### ISSUE TITLE
Update doesn't work

### ISSUE THREAD

**Issue by mouse100** [UnchartedBull/OctoDash#1979]
**What doesn't work?**
I've tried to update octodash to v2.2.0 through the Green Install button on my touchscreen. It downloads the update but gives me an error.

**General Information:**
 - Hardware: Raspberry Pi 4
 - OctoDash Version 2.1.2
 - OctoPrint Version 1.6.1

**Additional context**
Screenshot attached
![IMG_20210624_120509](https://user-images.githubusercontent.com/35471262/123247190-e8e7bd00-d4e6-11eb-972a-dcade50c2af3.jpg)

**Comment by Jack77777777** [comment]
https://github.com/UnchartedBull/OctoDash/issues/1818
