### ISSUE TITLE
Layer Count different on OctoDash versus Octoprint's gcode viewer.

### ISSUE THREAD

**Issue by sonjamichelle** [UnchartedBull/OctoDash#1981]
**Describe the bug**
I noticed while doing a print, OctoDash will report layer 4 when Octoprints gcode viewer is reporting layer 4.

Also Octodash will say something like "Layer 5 of 53" and gcode viewer is reporting "Layers with Extrusion: 55"

**Screenshots**

![gcode-viewer](https://user-images.githubusercontent.com/8279771/123375761-f33da180-d54e-11eb-886d-1c872b69c201.png)

![PXL_20210625_054512204](https://user-images.githubusercontent.com/8279771/123375771-f8025580-d54e-11eb-9628-8e1bd400ae3e.jpg)

**General Information:**
 - Hardware Raspberry Pi 4 4GB
 - OS Info OctoPi from the raspberry pi imager
 - OctoDash Version: installed from pip with url: `bash <(wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/install.sh)`
 - OctoPrint Version 1.6.1

UPDATE:

I also noticed that when I start a print, OD reports layer 0 out of whatever and OP states layer 1 out of whatever.

I am also using the current custom css: (https://github.com/UnchartedBull/OctoDash/tree/main/themes/theGarbz/Glanceable)

`/**** Job-Info Resizes ****/

app-job-status ~ app-printer-status .printer-status{
    position:absolute!important;
    top: 42vh!important;
    left: 0vw!important;
}

app-job-status ~ app-printer-status .printer-status__set-value {
    margin-top: -2vh!important;
    font-size: 3.9vw!important;
}

/**** Job-Info Layer Progress ****/

.height-indication{
    position:absolute!important;
    top: 66vh!important;
    left: 0vw!important;
    font-size: 3vw!important;
}

.height-indication__current-height{
    font-size: 6vh!important;
}

.height-indication__total-height{
    font-size: 5vh!important;
}

/**** Job-Info Progress ****/

.job-info__progress-bar {
    height: 8vh!important;
    border-radius: 1.7vw!important;
}

.job-info__progress-bar__wrapper {
    position:fixed!important;
    top: 77vh!important;
    left: 3vw!important;
    width: 92vw!important;
    height: 8vh!important;
    border-radius: 2vw!important;
    background-color: rgba(38, 44, 53, 1);
    border-style: solid!important;
    border-color: rgb(121, 121, 121);
    border-width: 2px!important;
}

#progress-preview-bar + .job-info__progress-percentage {
    margin-top: -0.3vh!important;
    margin-left: 0vw!important;
    font-size: 6.7vh!important;
    font-weight: 500!important;
    display:block!important;
    position:fixed!important;
    left: 43.4vw!important;
    top: 77vh!important;
    z-index:1!important;
    color:white!important;
    text-shadow: 1px 1px 4px black;
    visibility: visible!important;
}
`

**Comment by sonjamichelle** [comment]
Watching the print I noticed that on the sidebar under state, the layer count matched OctoDash but the times were wildly different.

OctoDash reported an elapsed time of 2h 13m and a remaining time of 3h 12m. You can see in the screenshot that those times are very different

![Capture](https://user-images.githubusercontent.com/8279771/123408679-e2068c00-d572-11eb-9c76-82885c086ecb.PNG)

**Comment by sonjamichelle** [comment]
Towards the end of the print the layer reporting was off by 2.  OctoDash reported 53 of 53 and Octoprint reported 55 of 55.

I may have been mistaken about the time reporting. A while after my post I noticed the time was relatively spot on.

I'm not a programmer so I have no clue at was is going on, I can only report what I observe to the best of my ability.

**Comment by sonjamichelle** [comment]
Doing another print, the time reporting is correct. Not sure what I was seeing earlier. Could be my mistake.

Though the layer reporting is still off by 2.

![2nd_time](https://user-images.githubusercontent.com/8279771/123481461-5f5ceb80-d5c9-11eb-8f02-51e5798955a8.PNG)

On OctoDash the current print is reporting 17 of 58, the State section of OctoPrint's sidebar reports 17 of 58 too. However, the gcode viewer reports 19 of 60.

Not really sure which one is the correct one now. Could be the gcode viewer.

The Pretty GCode plugin also reports the same as OctoDash and the Sidebar, so it may be looking as if it is the gcode viewer panel. That is the panel distributed with octoprint, not a plug -in, correct?

I hope that I'm not spamming too much, I just want to report as much as possible and be helpful.

**Comment by UnchartedBull** [comment]
OctoDash uses the Layer Progress Information provided by DisplayLayerProgress and doesn't have any access to the GCode Viewer.  I think all your screenshots point to something funky going on with the layer count in the GCode Viewer. Probably best to check whether that is natively integrated or a preinstalled plugin and then check that with their devs.

Regarding the print times, I don't see too much discrepancy between the times (only like 2 minutes for each). Does the time difference still happen?

**Comment by sonjamichelle** [comment]
I agree, was sort of my thinking too as I explored a bit further. I believe the gcode viewer is native to Octoprint. I'll look there..

As far as the time, that may have been my mistake. I was a bit distracted with another project at the time, so I believe the time reporting is working as intended.

**Comment by UnchartedBull** [comment]
Ok, closing this here then. Thanks for all the info!
