### ISSUE TITLE
Octodash has gone green!

### ISSUE THREAD

**Issue by fizzyade** [UnchartedBull/OctoDash#1995]
I've just powered up my Pi this morning, the Pi boots as normal and octodash started normally, at least at first.  I got the correct "Octodash is initialising" and it flipped to the "connected" screen after octoprint connected to the printed, but almost instantly after that, the octodash screen background turned green.

It's now happily running away and is fully functional, just with a green screen.

I'm running on a Raspberry Pi 3 B+ with a hyperpixel display.  Everything is the latest version of the software, Octodash, Octoprint and so on.

The screen is behaving right up until Octodash switches to the connected screen, where it shows the dashboard, I also briefly see that in the correct colours.  The boot-up until that point is all in the correct colours.

![IMG_1605](https://user-images.githubusercontent.com/55795671/123507078-7d752b00-d65f-11eb-8467-51170c8f618b.jpg)

**Comment by fizzyade** [comment]
Humn, it seems this may be an issue with the hyperpixel, the printer is busy at the moment so I will take a look when it's done.

**Comment by UnchartedBull** [comment]
Yeah this looks like a loose cable / connection or something. Closing this here. If it actually is OctoDash please reopen.

**Comment by fizzyade** [comment]
I created a fresh installation of octopi, installed the hyper pixel driver, and then onto-dash and it's back working now.  

If I switch back to the other SD card then I get the same screen issue.

The issue started when I changed the screen sleep setting in octodash, but I'm unsure of whether it was a coincidence or something else.

**Comment by sonypsx** [comment]
I got exactly the same issue, but with a fresh install. RP4 , Bullseye 64 Bit, Octoprint 1.8.3
Took me hours to figure out how to get the rotation correct (thanks to @alison-gravley in https://github.com/UnchartedBull/OctoDash/issues/2944), stumbled over the missing appindicator3-1 and some more issues. But finally got it working. But it is very greenish. However -> the Display (Hyperpixel4) is 100% OK, as before i was able to run the automatic install script from octodash i had a color correct desktop on my display.
Are there any hints how to get rid of this?

**Comment by fizzyade** [comment]
> I got exactly the same issue, but with a fresh install. RP4 , Bullseye 64 Bit, Octoprint 1.8.3
> 
> Took me hours to figure out how to get the rotation correct (thanks to @alison-gravley in https://github.com/UnchartedBull/OctoDash/issues/2944), stumbled over the missing appindicator3-1 and some more issues. But finally got it working. But it is very greenish. However -> the Display (Hyperpixel4) is 100% OK, as before i was able to run the automatic install script from octodash i had a color correct desktop on my display.
> 
> Are there any hints how to get rid of this?

I wiped and reinstalled as nothing else worked, I have no idea why it did it and it hasn't happens since.

**Comment by supawiz6991** [comment]
> I got exactly the same issue, but with a fresh install. RP4 , Bullseye 64 Bit, Octoprint 1.8.3 Took me hours to figure out how to get the rotation correct (thanks to @alison-gravley in #2944), stumbled over the missing appindicator3-1 and some more issues. But finally got it working. But it is very greenish. However -> the Display (Hyperpixel4) is 100% OK, as before i was able to run the automatic install script from octodash i had a color correct desktop on my display. Are there any hints how to get rid of this?

I'm going to guess that this is a screen specific issue since I'm running the raspberry pi offical 7" touch display and having had this problem under Raspberry pi OS Bullseye on a Rasperry Pi 4. 

Are you loading the driver for that specific display in /boot/config.txt?

If you did go through that then it may be that the driver is not compatible with Bullseye. Here is the github I'm referencing:
https://github.com/pimoroni/hyperpixel4

Also, this issue from their github page in reference to Bullseye may be of some interest: https://github.com/pimoroni/hyperpixel4/issues/177

In this issue others have had problems with display irregularities similar to yours so maybe it will set you on the right route,
