### ISSUE TITLE
Is there any way to make octodash work on Rasperry Pi Zero W now? Why is the xserver keep crashing, is there a workaround?

### ISSUE THREAD

**Issue by marco123445** [UnchartedBull/OctoDash#1996]
Is there any way to make octodash work on Rasperry Pi Zero W now? Why is the xserver keep crashing, is there a workaround?
Thanks for your help

_Originally posted by @marco123445 in https://github.com/UnchartedBull/OctoDash/issues/462#issuecomment-868992678_

**Comment by UnchartedBull** [comment]
Please either comment on and old issue or open a new one. Doing both just creates unnecessary notifications. The Raspberry Pi Zero W is and (probably never will be) supported by OctoDash. This is a limitation of the framework that OctoDash is using, plus the User Experience on the Pi Zero W will be rather bad I think.
