### ISSUE TITLE
Print Percentage incorrect on octodash

### ISSUE THREAD

**Issue by SeekaMartin** [UnchartedBull/OctoDash#2022]
showing correct both on printer and octoprint but not OctoDash
![image](https://user-images.githubusercontent.com/13934390/124337606-83d34c00-dbf7-11eb-9d23-163dbc91e93e.png)
![image](https://user-images.githubusercontent.com/13934390/124337611-8d5cb400-dbf7-11eb-8f08-41551745585a.png)

**Comment by UnchartedBull** [comment]
You do have Print Time Genius insatlled right? PTG will update the percentage in the UI, the percentage that is being send to OctoDash isn't updated though. I'm currently looking into ways to solve this. Current idea is to calculate the percentage on my own based on time elapsed and time remaining, as this should be the most useful percentage from my pov.

**Comment by SeekaMartin** [comment]
> You do have Print Time Genius insatlled right? PTG will update the percentage in the UI, the percentage that is being send to OctoDash isn't updated though. I'm currently looking into ways to solve this. Current idea is to calculate the percentage on my own based on time elapsed and time remaining, as this should be the most useful percentage from my pov.

I do but the issue is there with it enabled and disabled, your way to calculate seems best
