### ISSUE TITLE
Webcam not showing when connected to printer

### ISSUE THREAD

**Issue by leewilko** [UnchartedBull/OctoDash#2027]
Hi,

Thanks for Octodash its awesome.

I have a slight problem which is weird.

The webcam has been added as a custom action using the Webcam selection option. This works fine when the printer is not turned on.

If I turn on the printer and it connects to Octodash then select controls and push the button again the webcam does not show. I am not printing when I try this, it just accepts the button press but then returns to the main screen. No iframe is shown with the camera stream.

I saw another user had this issue but it could not be re-created so the issue was closed.

I'm happy to test this to see if it can be resolved?

Cheers

Lee

**Comment by jneilliii** [comment]
The webcam stream is supplied by the plugin to allow octodash to load it as an iframe. If the page isn't loading in OD at all that would be an octodash issue, but if it's loading the frame, but not loading the content that could be a plugin related issue. Can you share the text that you configured in the custom action button?
