### ISSUE TITLE
Multiple Cameras

### ISSUE THREAD

**Issue by CamoJackson** [UnchartedBull/OctoDash#204]
Please, add support for multiple camera streams into full screen and tab view

**Comment by hessius** [comment]
I think you might be on the wrong repo, this repository is not for the dashboard plugin but rather a dashboard to be displayed on an external screen.

**Comment by UnchartedBull** [comment]
OctoDash already supports Camera Views actually (kind off). You can open an iFrame with Custom Actions: https://github.com/UnchartedBull/OctoDash/wiki/Custom-Actions which could show your webcam stream (see command [WEB]). Is that sufficient?

**Comment by CamoJackson** [comment]
Sorry,  your right wrong repo

**Comment by Swap-File** [comment]
I'd like to say that camera support is one of the primary reasons I switched to OctoDash.  It might be useful to make that ability more prominent.

**Comment by UnchartedBull** [comment]
I never thought that so many people are looking for that feature. I'll make sure to make it more prominent :) Thanks for the info!
