### ISSUE TITLE
Community T-shirts

### ISSUE THREAD

**Issue by mano1979** [UnchartedBull/OctoDash#2043]
Hi, i'm a big fan of Octodash and i wondered if you'd mind if i use the logo for making community t-shirts. I would like to offer them on discord, maybe  a link here on github? Please let me know what your thoughts are about this.

**Comment by UnchartedBull** [comment]
HI, as I already wrote you on the discord server: Feel free to do so, please include the LICENSE / Link to the project somewhere. Please also share a link if you like :)
