### ISSUE TITLE
Top Half of Screen is Missing

### ISSUE THREAD

**Issue by kats-greg** [UnchartedBull/OctoDash#2058]
I did a new install of Octopi, on a new raspberry pi 4b, and a new install of OctoDash on top of that.

But when it boots, the top set of icons are missing so new File, Filament, or control icons, and new "Gear" icon in the upper right corner.
Picture attached.

![Octodash](https://user-images.githubusercontent.com/50823804/126050842-d23ecfdc-b6c0-41bf-aa98-3ea746210ce8.jpg)

I have several others that I installed previously and didn't have this issue.

Thanks

**Comment by UnchartedBull** [comment]
It looks like you setup that instance with the touchscreen option disabled, that's why it's not showing the top half. Please set the touchscreen value to `true` in your config.json. https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings#manually-adjusting-the-settings
