### ISSUE TITLE
Initializing... forever

### ISSUE THREAD

**Issue by sergioiker** [UnchartedBull/OctoDash#2069]
**What doesn't work?**
Updated Octodash to 2.2.1 And after rebooting, is initializing without success.

**What did you already try?**
I check and uncheck the CORS  option. still not working

**General Information:**
 - Hardware Raspberry pi 4b 
 - OS Info raspi octopi
 - OctoDash Version 2.2.1
 - OctoPrint Version 1.6.1

**Additional context**
help!

**Comment by UnchartedBull** [comment]
Did you reboot after checking the CORS checkbox?

**Comment by Jack77777777** [comment]
Is Octodash 2.2.1 released ?

**Comment by UnchartedBull** [comment]
Not yet, do you think that this would have an impact on this issue?

**Comment by mustang5269** [comment]
I had the same issue and had to delete my config and redo it.

**Comment by gale9010** [comment]
Same problem. 

I try to connect, unconnect, restart, change api key... 

Any solution?

**Comment by jiveman** [comment]
After trying to manually edit the ~/.config/octodash/config.json file with a few different local hostnames, I gave up and uninstalled wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/remove.sh | bash then reinstalled (no-reboot required) bash <(wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/install.sh) which did make me setup again, but it did work after. CORS was enabled on my instance, and did try disabling/re-enabling.
