### ISSUE TITLE
setting up my configs without keyboard ?

### ISSUE THREAD

**Issue by ARCH-3D** [UnchartedBull/OctoDash#207]
Hello, I need some help. after installing OctoDash how can i setting up my configs on my raspberry tft screen without keyboard?
Thanks in advance :)

**Comment by UnchartedBull** [comment]
You can either copy the sample.config.json from this repo to ‚~/.config/octodash/config.json‘ and adjust it to your needs or use xdotool (more info here: https://github.com/UnchartedBull/OctoDash/wiki/Installation) to emulate a keyboard.
