### ISSUE TITLE
OctoDash dont read/show files

### ISSUE THREAD

**Issue by ARCH-3D** [UnchartedBull/OctoDash#210]
Hello, 
When i touch in "files" dont show the files that i have to print. Appears a screen with a pacman "loading" but dont show anything else. What can i do? Thanks in advance

**General Information:**
 - Raspberry Pi
 - OctoPi
 - OctoDash Version [last update]

**Comment by UnchartedBull** [comment]
Do you have lots of files? Are there any errors showing up or is it just stuck at the loading screen? How long have you waited?

It would be great if you could send me the output of the API. You can do this easily via Postman:

GET <octoprint-url>:<octoprint-port>/api/files and make sure to include your API Key in the Header Field `X-Api-Key`. If you need any more help to retrieve this item let me know. You can also send the output to my email (timon.gaebelein@icloud.com) if you don't want to share the output here. Thanks!

**Comment by ARCH-3D** [comment]
Thanks for your answer UnchartedBull. Maybe 50 files. I waited more than 10 minutes, with no errors, just stuck at the loading screen.

**Comment by UnchartedBull** [comment]
Ok then there probably went something wrong while trying to parse the files. I would need to get the output from that API in order for me to fix this problem, as I never faced something similar. Sorry.

**Comment by ARCH-3D** [comment]
Ok Thanks. I sent you an email. You received?

**Comment by UnchartedBull** [comment]
Yeah I've already replied :)
