### ISSUE TITLE
Add a clock to the top of the screen

### ISSUE THREAD

**Issue by eblieb** [UnchartedBull/OctoDash#2138]
I am running Octodash on remote Raspberry PI 2 with a 3.5 inch screen that has a broken touch screen so I am running it without touch enabled. Is it possible to add a clock to the top of the screen?

**Comment by UnchartedBull** [comment]
That's not on my todo list unfortunately. Focusing on touch first for now. Feel free to add this yourself and create a PR though!. https://github.com/UnchartedBull/OctoDash/blob/main/src/app/job-status/job-status.component.html#L121 this is the line that needs to be changed.
