### ISSUE TITLE
GUI missalinments

### ISSUE THREAD

**Issue by DigiVore-Programing** [UnchartedBull/OctoDash#2143]
**Describe the bug**
Filament change screen has misaligned GUI

**To Reproduce**
1. Begin filament change
2. See error on all steps except the 1st

**Expected behavior**
Proper GUI

**Screenshots**
![20210809_182418](https://user-images.githubusercontent.com/38924918/128810785-7d80c3c3-f653-4000-909c-71acbe9fe346.jpg)

**General Information:**
 - Hardware Raspberry Pi B 1.2 800x480
 - OS Info OctoPi
 - OctoDash Version v2.2.0
 - OctoPrint Version v1.6.1

**Comment by UnchartedBull** [comment]
Already fixed with #1997. Will be released with next version.
