### ISSUE TITLE
Flow rate adjustment not available in adjust sub menu after update to 2.2.0

### ISSUE THREAD

**Issue by p17blo** [UnchartedBull/OctoDash#2183]
Since updating octodash to v2.2.0 the option to adjust the flow rate  appears to have been removed and replaced with a “SPEED” option instead. Can flow rate be reinstated?

**Comment by UnchartedBull** [comment]
There isn't enough space to add flow rate back into the menu, so flow rate probably won't come back. You can always create a custom fork and add the flow rate back into OctoDash. Alternatively you can create custom actions for the flow rate (v2.3.0 will support custom actions during printing).
