### ISSUE TITLE
Confirmation Dialog for some custom commands/actions?

### ISSUE THREAD

**Issue by spiff72** [UnchartedBull/OctoDash#225]
**Is your feature request related to a problem? Please describe.**
Somewhat...
Some of the commands in the custom commands/actions are "dangerous" - e.g. Shutdown, Kill). 

**Describe the solution you'd like**
Could there be a simple confirmation dialog that could be implemented in cases where a command could be harmful to the system?  (Maybe just add a flag to the config file that adds the confirmation dialog for certain commands?)

**Comment by UnchartedBull** [comment]
Great idea. I'll definitely make sure to include that.

I'm currently trying to do some kind of a Feature Stop for OctoDash v2 so it finally gets released. Therefore I'll move this issue to after the release of OctoDash. Sorry for the wait. It will be one of the first issues taken care off after the v2 release :)

**Comment by spiff72** [comment]
No problem. Your responsiveness on this program is exceptional!

**Comment by UnchartedBull** [comment]
Thank you :)

**Comment by UnchartedBull** [comment]
Was introduced in 1.4.0, can be adjusted in the settings
