### ISSUE TITLE
Touch Screen Triggering Multiple Buttons

### ISSUE THREAD

**Issue by wattsie** [UnchartedBull/OctoDash#2275]
Hi All,
  Any suggestions or pointers.
  Many thanks in advance.

  BTW: Going to start again with fresh install on a spare SD card to see if same thing happens.

**Describe the bug**
So I have a RPI3b+ with a DFR0550 5" DSI screen.
GUI works well and has very accurate pointing.
Installed OctoDash as per standard procedure and configured.

When using the OctoDash GUI, no matter how I try to press the buttons, I keep getting random multiple buttons activating.

Was wondering if there could be an issue with multi-touch?

PS: I had no touch issues on desktop GUI, before installing OctoDash.
Even selecting really small menus were accurately triggered with fingers.
(No mouse or kbd connected)

**To Reproduce**
Install OctoPi
Upgrade to latest OctoPrint
Install OctoDash
Configure
Reboot
Issue

**Expected behavior**
Buttons pressed with finger only selecting single button

**Screenshots**
Have attached a small video showing how multiple buttons fire when touching the screen.

**General Information:**
 - RPI 3B+, DFR0500 Screen
 - OctoPi 0.18.0 with all current updates
 - OctoDash as per (https://github.com/UnchartedBull/OctoDash/raw/main/scripts/install.sh)
 - OctoPrint 1.7.0rc3

https://user-images.githubusercontent.com/5244866/134142790-8b5073d8-9d7f-42e9-8619-63642a904245.mp4

**Comment by UnchartedBull** [comment]
Have you tried that screen with a different application? I've had a similar issue with the official touchscreen and once I've added a separate PSU for the touchscreen it completely went away. I think it was called "Ghost touches" and was discussed in the raspberry forum.

I unfortunately have absolutely no control over how touches are handled by the application. I can just define the spaces you can click on. Closing this here, but feel free to ask for more input regarding ghost touches if you need some. Sorry!
