### ISSUE TITLE
Makerbot Replicator 2X running Sailfish can't see left extruder

### ISSUE THREAD

**Issue by fridayshoes** [UnchartedBull/OctoDash#2424]
**What doesn't work?**
Octodash only seems to see only the right extruder and not the left one. Does anybody know a way to enable it?

**What did you already try?**
Looked in octodash settings, couldn't see any options

**General Information:**
 - RPI2B
 - Octodash latest version
 - Octoprint v1.6.1
 - Genuine Makerbot Replicator 2X Experimental Printer with Sailfish firmware
 - 

**Additional context**

**Comment by UnchartedBull** [comment]
Not supported atm. Will be tracked in #779.
