### ISSUE TITLE
Support for ollis SpoolManager plugin

### ISSUE THREAD

**Issue by DerKnerd** [UnchartedBull/OctoDash#2425]
I really like OctoDash, but one thing I am missing is support for Ollis SpoolManager plugin. Can you add support for that as well? Or maybe give me a point in the right direction, I used this plugin in a desktop app I developed for Octoprint, so I know the api fairly well.

Here is the plugin https://github.com/OllisGit/OctoPrint-SpoolManager

**Comment by UnchartedBull** [comment]
Beta support already added as part https://github.com/UnchartedBull/OctoDash/pull/2147. Will be released in the next couple of days hopefully.
