### ISSUE TITLE
Octodash only connectie once

### ISSUE THREAD

**Issue by Rotil66** [UnchartedBull/OctoDash#2515]
Hello all,
I have been reinstalling Octopi and octodash more than 10 times now on my raspberry PI4. But I can't get Octodash to connect when the PI has rebooted once. After installation of octodash it starts and I can setup the inital setting (API etc) after that it connects and is running. But as soon as I reboot the PI or Octodash. Octodash is hanging in initiallizing or not connecting to my computer.
The PI is connected to the network (Wired or WiFi)
I can acces the PI with putty. If I reinstall Octodash everything is starting over again. (Also did a fress install of octopi update etc,etc)
But it's constantly doing the same.

What is going wrong ??
Thanksñ

**Comment by UnchartedBull** [comment]
Did you enable CORS in the API Section of Octoprint? If this doesn't fix your issue please reopen.
