### ISSUE TITLE
On wiki pages, links to source code file like update.sh are not working because link to branch master are no longer supported

### ISSUE THREAD

**Issue by Mauxx91** [UnchartedBull/OctoDash#2540]
Just change the link everywhere from example this

`wget -qO- https://github.com/UnchartedBull/OctoDash/raw/master/scripts/update.sh | bash`

to this

`wget -qO- https://github.com/UnchartedBull/OctoDash/blob/main/scripts/update.sh | bash`

**Comment by UnchartedBull** [comment]
Updated the wiki. If you find anymore outdated links please let me know

**Comment by Mauxx91** [comment]
Thank you for your great job!
