### ISSUE TITLE
1.3.2 sometimes touches arent registered correctly

### ISSUE THREAD

**Issue by mvoss96** [UnchartedBull/OctoDash#258]
Thank you very much for the update 1.3.2 i really like the new touch animation.
However, I noticed that sometimes when i touch f.e. the control icon  the touch animation will play but it will not enter the control menu. This happens very rarely and i haven't found a way to reliably reproduce it. 
Another issue I found is that when you hold to long on an item it  sometimes gets a yellow border and not enter the menu

**Comment by UnchartedBull** [comment]
Ok the outline got fixed. I can't reproduce the issue you are having with touches not being recognized. Please open a new issue if you have steps to reproduce. Maybe also try to recalibrate your touchscreen.
