### ISSUE TITLE
OctoDash keeps reconnecting if API key is incorrect

### ISSUE THREAD

**Issue by queengooborg** [UnchartedBull/OctoDash#2608]
After replacing my old OctoPrint username with a new account (and revoking all the prior API keys), I noticed that OctoDash kept saying that it was attempting to reconnect to OctoPrint.  It would be great to instead get an on-screen message indicating that the API key is invalid, with instructions on how to correct it (or a one-tap fix).

**Comment by UnchartedBull** [comment]
This would require quite a lot of work and I don't think that this feature will be used by many users. Won't work on this, sorry.

**Comment by queengooborg** [comment]
Forgive me for my ignorance as I am not as familiar with Octodash's inner workings, but is it really that difficult to implement?  I mean, shouldn't Octodash return some form of error indicating an authorization failure, like an HTTP 401?

**Comment by UnchartedBull** [comment]
This was mostly related to the one-tap fix. I've added a notification if 403 is returned which should make debugging a lot easier.
