### ISSUE TITLE
Where to edit to inject command for sleep and wake for touchscreen display

### ISSUE THREAD

**Issue by kibbycabbit** [UnchartedBull/OctoDash#2611]
**What doesn't work?**
I tried editing .json file (the one that launches OctoDash after logging in Pi user) by changing xset for managing power saving and screen blanking. It didn't use the .json

**What did you already try?**
I entered the commands manually in terminal and it worked.

**General Information:**
 - Raspberry Pi 4B with Waveshare 4.3" DSI display; connected using DSI ribbon
 - Using OctoPi
 - Recent OctoDash Version (installed a few days ago)

**Additional context**
I am not sure which file to edit that allows me to specify command line that does: no blank, disable screen blanking while printing..  After printing, activate screen blanking with my defined minute.

I saw your .json with Wake and Sleep lines. I don't think they are doing anything. As a temp workaround, I had to execute the command lines every time I reboot Raspberry Pi.

**Comment by UnchartedBull** [comment]
Did you make sure that your changes got saved correctly? I recommend using the OctoDash companion app from jneillli and try again. Please reopen if this issue persists.
