### ISSUE TITLE
Pause/Resume Print issue

### ISSUE THREAD

**Issue by ARCH-3D** [UnchartedBull/OctoDash#265]
During the print job, if i press the button pause, the print job pauses (normal) ...but if i want to resume the print job i have no button to press and i cant continue. When i pause, the screen looks like the image sent.
![IMG_1636](https://user-images.githubusercontent.com/51092049/67709595-287aa080-f9b6-11e9-8733-f9ff6ea765bb.jpg)

**Comment by UnchartedBull** [comment]
I  confirmed that bug, will be fixed in the next release. There currently is no workaround other than starting it again from the OctoPrint Webinterface. Sorry!
