### ISSUE TITLE
Can't load Electron library when accessing dev environment throught localhost in Chrome

### ISSUE THREAD

**Issue by fauxvelocity** [UnchartedBull/OctoDash#2712]
**What doesn't work?**
The Octodash window on my PC loads up just fine, but as soon as I try to open the OctoDash interface through chrome (using localhost), it presents an error saying that it "Can't load Electron library", and to restart my system, and make a GitHub issue if the problem persists.

**Already tried**
Restarting my system, and looking up potential answers

**General Information:**
 - Using Windows 10
 - OctoDash Version 2.3.0
 - OctoPrint Version 1.7.3

**Additional context**
Sorry if this is a bad question, or if the answer is obvious, I'm very new to this and just now trying to get into it to create a custom CSS theme.

**Comment by UnchartedBull** [comment]
It's not supported to run OctoDash in the browser (last supported version was the initial release v1.0.0). If you want to run OctoDash in a browser you'd need to do a lot of monkey patching to get all the electron libraries out of the way.
