### ISSUE TITLE
Javascript Error when trying to update to 2.3.1

### ISSUE THREAD

**Issue by kats-greg** [UnchartedBull/OctoDash#2727]
I have the red dot on the gear indicating an update is available, but when I click on the update to 2.3.1 button, I get a javascript error message saying something about got is not a function.

**Comment by BigJoy75** [comment]
I also got the same error message

**Comment by kennethnilssen** [comment]
> I also got the same error message Finally I managed to update using script

Could you please share how?

**Comment by fredlex3dprints** [comment]
I get same error trying to update from 2.3.0 to 2.3.1

**Comment by LaPe63** [comment]
Same error here trying to update from 2.3.0 to 2.3.1 from the GUI (app.asar Type error: got is not a function)
I had to run the install script to update: 
bash <(wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/install.sh)

**Comment by BigJoy75** [comment]
> > I also got the same error message Finally I managed to update using script
> 
> Could you please share how?

You can see in how to do it in [https://github.com/UnchartedBull/OctoDash/wiki/Update](url)
 

wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/update.sh | bash

**Comment by spiff72** [comment]
same issue here - but using the script update after SSH into the pi worked fine.  Last update I did via the UI worked fine, but this one failed with the javascript error.

**Comment by SaKiEQ** [comment]
same here.. SSH'ing my way into it right now :)

**Comment by SaKiEQ** [comment]
the wget method worked flawless on one machine with a Pi4, on a Pi1A+ it fried the X Server....  I guess it was about time to setup this Pi from scratch anyway. 

[Xorg.0.log](https://github.com/UnchartedBull/OctoDash/files/8178596/Xorg.0.log)

**Comment by RichardvanGestel** [comment]
the 'wget' command also worked fine here on a pi3:

pi@octopi3:~ $ wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/update.sh | bash
Updating OctoDash
octodash.deb        100%[===================>]  59.89M  4.73MB/s    in 13s
[sudo] password for pi:
(Reading database ... 93823 files and directories currently installed.)
Preparing to unpack octodash.deb ...
Unpacking octodash (2.3.1) over (2.3.0) ...
Setting up octodash (2.3.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Done. Restart your Raspberry Pi to start the newest version!

**Comment by morphias2004** [comment]
Same Java error.

**Comment by bolsoncerrado** [comment]
Same error here. A screencap:
![20220307_080542](https://user-images.githubusercontent.com/10992914/157023964-1050e97f-40d9-4e93-b846-3e30876674e2.jpg)

**Comment by SW0rden** [comment]
It would seem that using the script no longer works.  Tried a couple of times and nothing is updated and get the same JS error as the above post.

**Comment by jneilliii** [comment]
what happens when you run the command 

```
wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/update.sh | bash
```

**Comment by SW0rden** [comment]
Thanks, got it!  I had left off the "| bash". Without it, it seemed as if it was working and asked about rebooting, but just fell back to the prompt and nothing was updated.

**Comment by bolsoncerrado** [comment]
> wget -qO- https://github.com/UnchartedBull/OctoDash/raw/main/scripts/update.sh | bash

On a working environment with 2.3.0 if I ssh the above, I get:

Updating OctoDash
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
dpkg: error: cannot access archive 'octodash.deb': No such file or directory
rm: cannot remove 'octodash.deb': No such file or directory
Done. Restart your Raspberry Pi to start the newest version!


Any c ues?

**Comment by bolsoncerrado** [comment]
OIC [](https://github.com/UnchartedBull/OctoDash/wiki/Troubleshooting#fix)You've most likely exceeded the GitHub Rate Limit, therefore the newest release can't be retrieved from the server.

Used manual method.

**Comment by ckoren** [comment]
same here
