### ISSUE TITLE
Scrolling long names? 

### ISSUE THREAD

**Issue by bolsoncerrado** [UnchartedBull/OctoDash#2728]
**Is your feature request related to a problem? Please describe.**
I find it problematic to know which file i'm printing as we use long names in our files in our farm...

**Describe the solution you'd like**
Scroll long filenames or find a way to show the full filename of a gcode file. 

**Additional context**
Like Prusa MK3/Mini screen do for example?

**Comment by sleake** [comment]
I second this. Or maybe just have it wrap in someway so you can see the full name. I use long names to contain some info that makes a difference if there are multiples:

`<object name> -<printer> -<location on the bed> -<other key details> -<print duration>`

So they would look something like:
`PI_TFT 5_0 Case -CR10 -C -60s -filchg3 -3h42m.gcode`
`Big vase v4 -E3v2 -FL -195c -50s -vase -5h2m.gcode`

Do you have any plans on when 3.0 will be released? Is there a list of what things you plan on adding in 3.0? (Great work on this BTW. Very useful/helpful!)

**Comment by bolsoncerrado** [comment]
@sleake I ended up using the suggested theme here: https://github.com/UnchartedBull/OctoDash/issues/3178
