### ISSUE TITLE
Octodash not starting

### ISSUE THREAD

**Issue by curtboyles** [UnchartedBull/OctoDash#2757]
I have installed octodash and a 7 in touch screen on my Raspberry pi 400.  After installing and rebooting octodash does not come up on the touchscreen attached to the rpi.  I am using 
OctoPrint 1.7.3 Python 3.7.3 OctoPi 0.18.0.
During install I choose to have octodash autostart.
Thank you for any suggestions or help you can provide me with.

**Comment by UnchartedBull** [comment]
Mh than that should work. Probably best to try again with a clean octopi / raspbian install. Ideally on a second SD Card to check whether this related to some hardware / octodash bug or a config error in your current firmware
