### ISSUE TITLE
Can't uninstall (or disable via Companion Octoprint plugin) the OctoDash plugins

### ISSUE THREAD

**Issue by bolsoncerrado** [UnchartedBull/OctoDash#2792]
**Describe the bug**
I'm facing some screen issues with some of the plugins I added when I installed Octodash so I want to either disable or remove such plugins

**Expected behavior**
Plugins to be disabled or removed.
For example, I installed Octodash companion but no matter if I uncheck the plugins and reboot, the plugins are still there.

So i either missed the documentation about uninstalling plugins or the Companion is not working as expected!?

**Screenshots**

<img width="1164" alt="Captura de pantalla 2022-03-25 a las 11 45 25" src="https://user-images.githubusercontent.com/10992914/160106551-2355c117-b560-48f0-b7c3-e13c821e1a2e.png">
<img width="1182" alt="Captura de pantalla 2022-03-25 a las 11 45 20" src="https://user-images.githubusercontent.com/10992914/160106563-e865039e-1fdf-436e-b01e-2ff172e62f96.png">

**General Information:**
 - RasPi 3B+ on OctoPi image 0.18
 - OctoDash Version 2.3.1
 - OctoPrint Version 1.7.8

**Comment by jneilliii** [comment]
This is not the companion plugin repo, I manage that separately in its own repo. However, I'd you disable the plugin in plugin manager and restart octoprint it should go away. In very rare instances you may need to reboot the pi completely or force refresh your browser using shift+f5 if any plugin isn't doing right.

**Comment by bolsoncerrado** [comment]
@jneilliii you mean the octoprint plugins menu installs an outdated version of the companion? how do I install yours?

Thanks!

**Comment by jneilliii** [comment]
Pretty sure the installation script installs the latest version of my plugin.

**Comment by bolsoncerrado** [comment]
OK then I missunderstood you. What did you mean by "This is not the companion plugin repo, I manage that separately in its own repo. "?

**Comment by bolsoncerrado** [comment]
And this is as ridiculous as it gets. I went ahead and completelly uninstalled Octodash.

Then I reinstalled it with ONLY Companion+Preheat plugins.

Not only the same Companion version shows up that it's also DIFFERENT from the one I posted above this morning AND the Layer plugin is still there and not gone!

WTH?

<img width="528" alt="Captura de pantalla 2022-03-25 a las 20 15 12" src="https://user-images.githubusercontent.com/10992914/160187144-268f0b11-5d8f-463c-8683-3aa5a2e47bc2.png">


<img width="511" alt="Captura de pantalla 2022-03-25 a las 20 15 54" src="https://user-images.githubusercontent.com/10992914/160187159-d87fb3ec-9bd5-454d-9be4-7617a0f4c307.png">

**Comment by bolsoncerrado** [comment]
Besides the CANT UNINSTALL PLUGINS issue, I think the companion from the install script and the companion from the octoprint plugins list ARE different.

That or @jneilliii updated it between this morning's post and this one above :?

**Comment by jneilliii** [comment]
I have not made any updates today for the plugin.

**Comment by bolsoncerrado** [comment]
Awesome then.

**Comment by jneilliii** [comment]
Are you just trying to get rid of the plugins? That's done from the octoprint plugin manager settings.

**Comment by bolsoncerrado** [comment]
No way, really!? LOL I thought octodash plugins were exclusively handled via octodash companion/octodash command line

**Comment by jneilliii** [comment]
No, those are all in octoprint. The install script is just doing command line installs in octoprint as a convenience.

**Comment by bolsoncerrado** [comment]
No clue then why I got two different plugin views on the companion then.

Thanks tho.
