### ISSUE TITLE
xinit refused

### ISSUE THREAD

**Issue by 1achy** [UnchartedBull/OctoDash#2793]
Hardware : raspberry 3 b+
Touh 3.5 kuman (driver show3.5)

In touch screen  i see : 
****

X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System: Linux 5.4.0-72-generic armv8l Raspbian
Current Operating System: Linux octopi 5.10.103+ #1529 Tue Mar 8 12:19:18 GMT 2022 armv6l
Kernel command line: coherent_pool=1M snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=480 bcm2708_fb.fbheight=320 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  console=ttyAMA0,115200 console=tty1 root=PARTUUID=509d0db1-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
Build Date: 04 January 2022  10:05:34AM
xorg-server 2:1.20.4-1+rpt4+deb10u4 (https://www.debian.org/support)
Current version of pixman: 0.36.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sun Mar 27 15:45:43 2022
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
modprobe: FATAL: Module g2d_23 not found in directory /lib/modules/5.10.103+
xinit: Unable to run program "xterm": No such file or directory
Specify a program on the command line or make sure that /usr/bin
is in your path.

xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.

**in the log file there is :**

[  1206.201] X.Org X Server 1.20.4 X Protocol Version 11, Revision 0
[  1206.207] Build Operating System: Linux 5.4.0-72-generic armv8l Raspbian
[  1206.210] Current Operating System: Linux octopi 5.10.103+ #1529 Tue Mar 8 12:19:18 GMT 2022$
[  1206.212] Kernel command line: coherent_pool=1M snd_bcm2835.enable_compat_alsa=0 snd_bcm2835$
[  1206.229] Build Date: 04 January 2022  10:05:34AM
[  1206.230] xorg-server 2:1.20.4-1+rpt4+deb10u4 (https://www.debian.org/support)
[  1206.232] Current version of pixman: 0.36.0
[  1206.236]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[  1206.237] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  1206.259] (==) Log file: "/var/log/Xorg.0.log", Time: Sun Mar 27 15:37:02 2022
[  1206.274] (==) Using config directory: "/etc/X11/xorg.conf.d"
[  1206.275] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  1206.279] (==) No Layout section.  Using the first Screen section.
[  1206.279] (==) No screen section available. Using defaults.
[  1206.287] (**) |-->Screen "Default Screen Section" (0)
[  1206.287] (**) |   |-->Monitor "<default monitor>"
[  1206.294] (==) No device specified for screen "Default Screen Section".
        Using the first device section listed.

[  1206.294] (**) |   |-->Device "Allwinner A10/A13/A20 FBDEV"
[  1206.295] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[  1206.295] (==) Automatically adding devices
[  1206.295] (==) Automatically enabling devices
[  1206.296] (==) Automatically adding GPU devices
[  1206.296] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  1206.297] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  1206.297]    Entry deleted from font path.
[  1206.297] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  1206.297]    Entry deleted from font path.
[  1206.297] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  1206.298]    Entry deleted from font path.
[  1206.298] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  1206.298]    Entry deleted from font path.
[  1206.298] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  1206.299]    Entry deleted from font path.
[  1206.299] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  1206.299]    Entry deleted from font path.
[  1206.299] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        built-ins
[  1206.310] (==) ModulePath set to "/usr/lib/xorg/modules"
[  1206.310] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[  1206.311] (II) Loader magic: 0x1fdf80
[  1206.311] (II) Module ABI versions:
[  1206.311]    X.Org ANSI C Emulation: 0.4
[  1206.311]    X.Org Video Driver: 24.0
[  1206.311]    X.Org XInput driver : 24.1
[  1206.312]    X.Org Server Extension : 10.0

[  1206.294] (**) |   |-->Device "Allwinner A10/A13/A20 FBDEV"
[  1206.295] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[  1206.295] (==) Automatically adding devices
[  1206.295] (==) Automatically enabling devices
[  1206.296] (==) Automatically adding GPU devices
[  1206.296] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  1206.297] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  1206.297]    Entry deleted from font path.
[  1206.297] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  1206.297]    Entry deleted from font path.
[  1206.297] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  1206.298]    Entry deleted from font path.
[  1206.298] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  1206.298]    Entry deleted from font path.
[  1206.298] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  1206.299]    Entry deleted from font path.
[  1206.299] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  1206.299]    Entry deleted from font path.
[  1206.299] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        built-ins
[  1206.310] (==) ModulePath set to "/usr/lib/xorg/modules"
[  1206.310] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[  1206.311] (II) Loader magic: 0x1fdf80
[  1206.311] (II) Module ABI versions:
[  1206.311]    X.Org ANSI C Emulation: 0.4
[  1206.311]    X.Org Video Driver: 24.0
[  1206.311]    X.Org XInput driver : 24.1
[  1206.312]    X.Org Server Extension : 10.0
[  1206.343] (--) using VT number 2

[  1206.343] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not pro$
[  1206.345] (II) no primary bus or device found
[  1206.346] (II) LoadModule: "glx"
[  1206.348] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so

[  1206.402] (II) Module glx: vendor="X.Org Foundation"
[  1206.402]    compiled for 1.20.4, module version = 1.0.0
[  1206.402]    ABI class: X.Org Server Extension, version 10.0

[  1206.294] (**) |   |-->Device "Allwinner A10/A13/A20 FBDEV"
[  1206.295] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[  1206.295] (==) Automatically adding devices
[  1206.295] (==) Automatically enabling devices
[  1206.296] (==) Automatically adding GPU devices
[  1206.296] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  1206.297] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  1206.297]    Entry deleted from font path.
[  1206.297] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  1206.297]    Entry deleted from font path.
[  1206.297] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  1206.298]    Entry deleted from font path.
[  1206.298] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  1206.298]    Entry deleted from font path.
[  1206.298] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  1206.299]    Entry deleted from font path.
[  1206.299] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  1206.299]    Entry deleted from font path.
[  1206.299] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        built-ins
[  1206.310] (==) ModulePath set to "/usr/lib/xorg/modules"
[  1206.310] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[  1206.311] (II) Loader magic: 0x1fdf80
[  1206.311] (II) Module ABI versions:
[  1206.311]    X.Org ANSI C Emulation: 0.4
[  1206.311]    X.Org Video Driver: 24.0
[  1206.311]    X.Org XInput driver : 24.1
[  1206.312]    X.Org Server Extension : 10.0
[  1206.343] (--) using VT number 2

[  1206.343] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not pro$
[  1206.345] (II) no primary bus or device found
[  1206.346] (II) LoadModule: "glx"
[  1206.348] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  1206.402] (II) Module glx: vendor="X.Org Foundation"
[  1206.402]    compiled for 1.20.4, module version = 1.0.0
[  1206.402]    ABI class: X.Org Server Extension, version 10.0
[  1206.403] (II) LoadModule: "fbturbo"

[  1206.403] (II) LoadModule: "fbturbo"
[  1206.404] (II) Loading /usr/lib/xorg/modules/drivers/fbturbo_drv.so
[  1206.406] (II) Module fbturbo: vendor="X.Org Foundation"
[  1206.407]    compiled for 1.20.3, module version = 0.5.1
[  1206.407]    Module class: X.Org Video Driver
[  1206.407]    ABI class: X.Org Video Driver, version 24.0
[  1206.407] (II) FBTURBO: driver for framebuffer: fbturbo
[  1206.430] (WW) Falling back to old probe method for fbturbo
[  1206.431] (II) Loading sub module "fbdevhw"
[  1206.431] (II) LoadModule: "fbdevhw"
[  1206.432] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[  1206.434] (II) Module fbdevhw: vendor="X.Org Foundation"
[  1206.435]    compiled for 1.20.4, module version = 0.0.2
[  1206.435]    ABI class: X.Org Video Driver, version 24.0
[  1206.436] (II) FBTURBO(0): using /dev/fb0
[  1206.437] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[  1206.437] (II) FBTURBO(0): Creating default Display subsection in Screen section
        "Default Screen Section" for depth/fbbpp 24/32
[  1206.438] (==) FBTURBO(0): Depth 24, (==) framebuffer bpp 32
[  1206.438] (==) FBTURBO(0): RGB weight 888
[  1206.438] (==) FBTURBO(0): Default visual is TrueColor
[  1206.439] (==) FBTURBO(0): Using gamma correction (1.0, 1.0, 1.0)
[  1206.439] (II) FBTURBO(0): hardware: BCM2708 FB (video memory: 600kB)
[  1206.439] (DB) xf86MergeOutputClassOptions unsupported bus type 0
[  1206.488] (**) FBTURBO(0): Option "fbdev" "/dev/fb0"
[  1206.489] (**) FBTURBO(0): Option "SwapbuffersWait" "true"
[  1206.492] (II) FBTURBO(0): processor: ARM1176
[  1206.492] (II) FBTURBO(0): checking modes against framebuffer device...
[  1206.493] (II) FBTURBO(0): checking modes against monitor...
[  1206.493] (II) FBTURBO(0): Virtual size is 480x320 (pitch 480)
[  1206.493] (**) FBTURBO(0):  Built-in mode "current"
[  1206.493] (==) FBTURBO(0): DPI set to (96, 96)
[  1206.494] (II) Loading sub module "fb"
[  1206.494] (II) LoadModule: "fb"

[  1206.495] (II) Loading /usr/lib/xorg/modules/libfb.so
[  1206.498] (II) Module fb: vendor="X.Org Foundation"
[  1206.498]    compiled for 1.20.4, module version = 1.0.0
[  1206.498]    ABI class: X.Org ANSI C Emulation, version 0.4
[  1206.532] (II) FBTURBO(0): using backing store heuristics
[  1206.827] (II) FBTURBO(0): can't load 'g2d_23' kernel module
[  1206.842] (II) FBTURBO(0): failed to enable the use of sunxi display controller
[  1206.842] (II) FBTURBO(0): No sunxi-g2d hardware detected (check /dev/disp and /dev/g2d)
[  1206.842] (II) FBTURBO(0): G2D hardware acceleration can't be enabled
[  1206.843] (II) FBTURBO(0): enabled fbdev copyarea acceleration
[  1206.843] (==) FBTURBO(0): Backing store enabled
[  1206.846] (==) FBTURBO(0): DPMS enabled
[  1206.847] (II) FBTURBO(0): failed to enable hardware cursor
[  1206.847] (II) FBTURBO(0): no 3D acceleration because the driver has been compiled without l$
[  1206.847] (II) FBTURBO(0): if this is wrong and needs to be fixed, please check ./configure $
[  1206.848] (II) Initializing extension Generic Event Extension
[  1206.873] (II) Initializing extension SHAPE
[  1206.892] (II) Initializing extension MIT-SHM
[  1206.896] (II) Initializing extension XInputExtension
[  1206.912] (II) Initializing extension XTEST
[  1206.918] (II) Initializing extension BIG-REQUESTS
[  1206.934] (II) Initializing extension SYNC
[  1206.938] (II) Initializing extension XKEYBOARD
[  1206.952] (II) Initializing extension XC-MISC
[  1206.955] (II) Initializing extension SECURITY
[  1206.958] (II) Initializing extension XFIXES
[  1206.973] (II) Initializing extension RENDER
[  1206.977] (II) Initializing extension RANDR
[  1206.996] (II) Initializing extension COMPOSITE
[  1207.011] (II) Initializing extension DAMAGE
[  1207.015] (II) Initializing extension MIT-SCREEN-SAVER
[  1207.018] (II) Initializing extension DOUBLE-BUFFER
[  1207.055] (II) Initializing extension RECORD
[  1207.058] (II) Initializing extension DPMS
[  1207.068] (II) Initializing extension Present
[  1207.094] (II) Initializing extension DRI3
[  1207.094] (II) Initializing extension X-Resource

[  1207.106] (II) Initializing extension XVideo
[  1207.121] (II) Initializing extension XVideo-MotionCompensation
[  1207.121] (II) Initializing extension SELinux
[  1207.122] (II) SELinux: Disabled on system
[  1207.122] (II) Initializing extension GLX
[  1207.126] (II) AIGLX: Screen 0 is not DRI2 capable
[  1208.421] (II) IGLX: Loaded and initialized swrast
[  1208.421] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[  1208.421] (II) Initializing extension XFree86-VidModeExtension
[  1208.425] (II) Initializing extension XFree86-DGA
[  1208.431] (II) Initializing extension XFree86-DRI
[  1208.431] (II) Initializing extension DRI2
[  1209.513] (II) config/udev: Adding input device ADS7846 Touchscreen (/dev/input/event0)
[  1209.515] (**) ADS7846 Touchscreen: Applying InputClass "evdev touchscreen catchall"
[  1209.515] (**) ADS7846 Touchscreen: Applying InputClass "evdev touchscreen catchall"
[  1209.516] (**) ADS7846 Touchscreen: Applying InputClass "calibration"
[  1209.516] (II) LoadModule: "evdev"
[  1209.517] (II) Loading /usr/lib/xorg/modules/input/evdev_drv.so
[  1209.533] (II) Module evdev: vendor="X.Org Foundation"
[  1209.534]    compiled for 1.20.3, module version = 2.10.6
[  1209.534]    Module class: X.Org XInput Driver
[  1209.534]    ABI class: X.Org XInput driver, version 24.1
[  1209.534] (II) Using input driver 'evdev' for 'ADS7846 Touchscreen'
[  1209.535] (**) ADS7846 Touchscreen: always reports core events
[  1209.535] (**) evdev: ADS7846 Touchscreen: Device: "/dev/input/event0"
[  1209.537] (--) evdev: ADS7846 Touchscreen: Vendor 0 Product 0
[  1209.537] (--) evdev: ADS7846 Touchscreen: Found absolute axes
[  1209.537] (--) evdev: ADS7846 Touchscreen: Found x and y absolute axes
[  1209.538] (--) evdev: ADS7846 Touchscreen: Found absolute touchscreen
[  1209.548] (**) Option "SwapAxes" "1"
[  1209.551] (II) evdev: ADS7846 Touchscreen: Configuring as touchscreen
[  1209.552] (**) evdev: ADS7846 Touchscreen: YAxisMapping: buttons 4 and 5
[  1209.552] (**) evdev: ADS7846 Touchscreen: EmulateWheelButton: 4, EmulateWheelInertia: 10, E$
[  1209.552] (**) Option "config_info" "udev:/sys/devices/platform/soc/20204000.spi/spi_master/$
[  1209.553] (II) XINPUT: Adding extended input device "ADS7846 Touchscreen" (type: TOUCHSCREEN$
[  1209.554] (II) evdev: ADS7846 Touchscreen: initialized for absolute axes.
[  1209.558] (**) ADS7846 Touchscreen: (accel) keeping acceleration scheme 1
[  1209.558] (**) ADS7846 Touchscreen: (accel) acceleration profile 0
[  1209.559] (**) ADS7846 Touchscreen: (accel) acceleration factor: 2.000
[  1209.559] (**) ADS7846 Touchscreen: (accel) acceleration threshold: 4
[  1209.606] (II) config/udev: Adding input device ADS7846 Touchscreen (/dev/input/mouse0)
[  1209.607] (**) ADS7846 Touchscreen: Applying InputClass "calibration"
[  1209.607] (II) No input driver specified, ignoring this device.
[  1209.607] (II) This device may have been added with another device file.
[  1210.078] (II) evdev: ADS7846 Touchscreen: Close
[  1210.079] (II) UnloadModule: "evdev"
[  1210.201] (II) Server terminated successfully (0). Closing log file.

**Comment by UnchartedBull** [comment]
Please follow the Troubleshooting guide: https://github.com/UnchartedBull/OctoDash/wiki/Troubleshooting#cannot-open-display-xinit-failing-. I cannot provide any assistance on this as these issues are super specific to user setups. You can also try installing the desktop environment and setup OctoDash over there if that works for you. Otherwise try googling around for any errors / check other GItHub issues. Sorry!
