### ISSUE TITLE
Shutdown Button

### ISSUE THREAD

**Issue by FlyingT** [UnchartedBull/OctoDash#281]
Nothing fancy, just a Shutdown / Restart Button for the Raspberry Pi

**Comment by UnchartedBull** [comment]
https://github.com/UnchartedBull/OctoDash/wiki/Custom-Actions#predefined-actions. Already possible :)

**Comment by FlyingT** [comment]
Totally missed that, thanks!
I wrote an "popular" [guide ](https://github.com/FlyingT/OctoTouch/wiki/Complete-Setup-Guide) for Prusa Printers and Touchscreens while ago, I think I will scrap Octoprint-TFT and OctoScreen from it and replace it with your OctoDash. Just works like a charm on 3,5" GPIO screens!

**Comment by UnchartedBull** [comment]
That would be great! If you need any more information let me know :).

**Comment by I-like-stuff** [comment]
Personally I would prefer to have a dedicated shutdown button on the menu page, maybe in the bottom right hand corner.
