### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by nedla1969** [UnchartedBull/OctoDash#286]
Not sure whats happened. 

just restarted and this came up

![75233456_659324204594007_4720607454205837312_n](https://user-images.githubusercontent.com/21147114/68092644-40a26200-fe85-11e9-82be-841fa6301b5c.jpg)

**Comment by UnchartedBull** [comment]
You can either edit your config file with nano to match this file: https://github.com/UnchartedBull/OctoDash/blob/master/sample.config.json with `nano ~/.config/octodash/config.json`.

 Or just delete it `rm ~/.config/octodash/config.json` and restart your Pi and create a new config.

What did you do prior to this error showing up?

**Comment by nedla1969** [comment]
Many thanks,  i was trying to setup my DHT22 sensor, And must of deleted the config file some how..
