### ISSUE TITLE
Advice please

### ISSUE THREAD

**Issue by nedla1969** [UnchartedBull/OctoDash#291]
I have a dht22 sensor working perfectly showing the enclosure on octoprint, Is it suppose show on the touch scree to?, Thanks

**Comment by UnchartedBull** [comment]
Yes if it is configured. Currently you need to either set this up during startup or manually in the config file. The next update probably will include a way to this directly via the Interface ...

**Comment by nedla1969** [comment]
I set it up at start up,  
 `` "octodash": {
                        "touchscreen": true,
                        "temperatureSensor": {
                                "ambient": "dht22",
                                "filament1": null,
                                "filament2": null

**Comment by UnchartedBull** [comment]
Is that the name you gave the sensor? You don't enter the type there, but rather the name of the sensor. The name will be displayed in the very left column if you have the enclosure tab open. It works just fine for me ...

**Comment by nedla1969** [comment]
Thankyou all sorted
