### ISSUE TITLE
Dual Nozzel/Hotend temperature display

### ISSUE THREAD

**Issue by sint-vaffel** [UnchartedBull/OctoDash#332]
Would be nice to be able to see temprature of both nozzels for dual nozzle/idex machines

**Comment by UnchartedBull** [comment]
I do not have a printer with two nozzles, so there is no way for me to test this. This would also need some kind of redesign for the homescreen. I'll be happy to review any PRs on this, but I won't start working on this for now ...

**Comment by Protean-Man** [comment]
I know this has gone stale but I think adding an adaptive layout for multiple nozzles would be great.

**Comment by UnchartedBull** [comment]
Problem is, that I don't have a multi-nozzle printer to test this with. So it would be really hard for me to work on this.

**Comment by fridayshoes** [comment]
Would like to see dual nozzles too
