### ISSUE TITLE
touchscreen

### ISSUE THREAD

**Issue by PusheenCodes** [UnchartedBull/OctoDash#3792]
**What doesn't work?**

**What did you already try?**
A clear and concise description of what you tried to make OctoDash work.

**General Information:**
 - Hardware [e.g. Raspberry Pi, if you have layout issues please also include your screen resolution]
 - OS Info [e.g. Raspbian Buster Lite, please also indicate if you used OctoPi]
 - OctoDash Version [e.g. v1.0.0]
 - OctoPrint Version [e.g. v1.0.0]

**Additional context**

**Comment by Vaarlion** [comment]
This look like it was created by mistake and should be closed

**Comment by PusheenCodes** [comment]
Yes sorry, please close this.
