### ISSUE TITLE
black screen hyperpixel4

### ISSUE THREAD

**Issue by patritha** [UnchartedBull/OctoDash#4314]
**What doesn't work?**
the screen displays nothing when given power. 
**What did you already try?**
i *exactly* followed the instructions for installing octodash and the guide for the hyperpixel4 on a fresh install of octopi/octoprint. i also did `export DISPLAY=:0` and `ratpoison` where ratpoison gave a `Segmentation fault` as its output. 

**General Information:**
 - Raspberry Pi 4b with Hyperpixel4 rectangular screen.
 - octopi v1.0.0cam
 - OctoDash V2.3.1
 - OctoPrint V1.10.1 (new camera stack)

**Additional context**

**Comment by ItsCharged** [comment]
> **What doesn't work?** the screen displays nothing when given power. **What did you already try?** i _exactly_ followed the instructions for installing octodash and the guide for the hyperpixel4 on a fresh install of octopi/octoprint. i also did `export DISPLAY=:0` and `ratpoison` where ratpoison gave a `Segmentation fault` as its output.
> 
> **General Information:**
> 
> * Raspberry Pi 4b with Hyperpixel4 rectangular screen.
> * octopi v1.0.0cam
> * OctoDash V2.3.1
> * OctoPrint V1.10.1 (new camera stack)
> 
> **Additional context** Add any other context or screenshots about the feature request here.

So that means you also tried installing drivers?
Try to disable the v3d drivers in config.

**Comment by wangyao127** [comment]
![Uploading 微信图片_20240621005528.jpg…]()

**Comment by wangyao127** [comment]
Raspberry Pi 4b with Hyperpixel4 rectangular screen.
octopi v1.0.0cam
OctoDash V2.3.1
OctoPrint V1.10.1 (new camera stack)

**Comment by wangyao127** [comment]
Raspberry Pi 4b with Kedei LCD 35 HDMI screen.
octopi v1.0.0cam
OctoDash V2.3.1
OctoPrint V1.10.2 (new camera stack)

**Comment by patritha** [comment]
@ItsCharged how do i do that? sorry if thats a dumb question but im bot good with the pi

**Comment by ItsCharged** [comment]
SSH into your pi. Navigate to the config by `cd ~/boot/` 
Or `cd ..` and again `cd ..` and last time `cd ..` to make sure youre in the right Directory. Then do `cd boot` and `sudo nano config.txt`. Now search for a line that says `dtoverlay=vc4-kms-v3d` and put a hashtag in Front of it like this `#dtoverlay=vc4-kms-v3d` Press Ctrl + x press y press enter and execute `sudo reboot -f`. Youre welcome. Tell me if it works or doesent.

**Comment by patritha** [comment]
OMG it works thank you so much!!! im so happy now
