### ISSUE TITLE
Update message popping up even though I am on the latest version

### ISSUE THREAD

**Issue by spiff72** [UnchartedBull/OctoDash#445]
**Describe the bug**
The update notification message is popping up when I am using the newly released 1.4.0 version.

**Expected behavior**
Since I am current, I wouldn't expect to see this notification.

**Screenshots**
![20200221_074841](https://user-images.githubusercontent.com/11482743/75039914-aabc3280-5487-11ea-98ed-b9fa7e645352.jpg)

**Additional context**
This may be a special case, as I updated over top of the modified version you posted [here](https://github.com/UnchartedBull/OctoDash/issues/411#issuecomment-587042382) when you were working on a fix for the saving of settings black screen of death.

**Comment by spiff72** [comment]
I updated by downloading the deb file from the assets section of the Release 1.4 tab, and used the dpkg command to perform the update. 

I did this because I wasn't sure if the update script would work correctly with my "modified" version of the package.

**Comment by evannadeau** [comment]
I see this same behavior, however I also had a little bit of a strange upgrade. I was following the upgrade instructions from the wiki and blindly posted in end download line that pulled down version 1.0.0. so I went from 1.3.3 to 1.0.0 and then up to 1.4.0

**Comment by DeviousPenguin** [comment]
Getting the same thing also:

[pic](https://i.imgur.com/uP9yuFFl.jpg)

**Comment by UnchartedBull** [comment]
I think I messed up something with the version check there ... Will update once I get back home. Sorry for that!

**Comment by UnchartedBull** [comment]
Well, I did something really stupid this time around. Accidentally labeled the GitHub release v.1.4.0, see that point in front of the 1. That is what threw everything off. Good thing is, that this is now fixed, just needed to update the GitHub Release name, no update needed for OctoDash. Thanks for pointing this out!
