### ISSUE TITLE
Stopping a print abruptly causes OctoDash to wake up in a broken/bugged state

### ISSUE THREAD

**Issue by MatthewCroughan** [UnchartedBull/OctoDash#453]
If you kill a print, OctoDash will go to sleep. Upon waking it up again, it will be left in a state that requires a full restart of the app to recover from, where it claims there is no job running, whilst reporting the last layer the previous print job was ended on.

[Here is a video demonstration of the issue.](https://files.catbox.moe/l6xrgv.mp4)

**Comment by UnchartedBull** [comment]
Thanks fo adding the video. I'm closing this in favour of #433, as this describes the same issue. Will be definitely fixed with the next release!
