### ISSUE TITLE
Markdown or user-programmable info screen to assist new users.

### ISSUE THREAD

**Issue by MatthewCroughan** [UnchartedBull/OctoDash#454]
It would be very nice if it were possible to have a question mark or help button at the bottom right of the display that the user/deployer could program. The reason for this is so that people that are new to the Makerspace I'm provisioning my printers at can tap this to be informed about the printer in a custom way. Bonus points for allowing us to make multiple pages, embed images, etc, via markdown. Perhaps a vertically scrollable markdown page would suffice, since that would allow one to embed images anyway. One such image could be a QR code which points to a wiki document somewhere on the internet that teaches someone how to use the machine.

**Comment by UnchartedBull** [comment]
Sounds like a neat idea. Maybe I can put a tutorial there on how to use OctoDash, which could be then replaced by the user if he/she likes to do :) Will work on this once v2 is released.
