### ISSUE TITLE
XDOTOOL CLICK LOCATIONS

### ISSUE THREAD

**Issue by jneilliii** [UnchartedBull/OctoDash#463]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the button positions of the initial set-up wizard documented somewhere so that we could use `xdotool click` commands for scripting the initial setup.

**Describe the solution you'd like**
Updated wiki page documenting the set-up wizard's button positions, and potentially an example script for showing how to use xdotool over SSH.

**Link other projects**
N/A

**Additional context**
I realize that the config file could just be copied to the pi for quick install, but just thought it would be nice to be able to script the initial setup.

**Comment by UnchartedBull** [comment]
https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings#click-locations added to the wiki.
