### ISSUE TITLE
no start   -bach: xinit: command not found

### ISSUE THREAD

**Issue by jortec** [UnchartedBull/OctoDash#479]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General Information:**
 - Hardware [e.g. Raspberry Pi, if you have layout issues please also include your screen resolution]
 - OS Info [e.g. Raspbian Buster Lite, please also indicate if you used OctoPi]
 - OctoDash Version [e.g. v1.0.0]
 - OctoPrint Version [e.g. v1.0.0]

**Additional context**

**Comment by UnchartedBull** [comment]
I can't really help without more information. What is your setup? Did you run the automatic start script?

Also this looks like a problem with your Pi, please make sure xinit is installed and functioning.

**Comment by evannadeau** [comment]
If I were to guess, I think your usual is not complete due to missing dependencies. Check out the manual install information in the wiki.

[download-and-install-octodash](https://github.com/UnchartedBull/OctoDash/wiki/Installation#download-and-install-octodash)
