### ISSUE TITLE
Current layer display offset config

### ISSUE THREAD

**Issue by evilbobbins** [UnchartedBull/OctoDash#480]
Adding of a layer offset option I.E. on my printer octoprint starts on layer 0 on the octoprint display but layer 1 on Octodash.
Fixing this with an off set in Octoprint offsets Octodash to start on layer 2

Could a layer offset option be added so keep them in sync when this is the case?

**Comment by UnchartedBull** [comment]
OctoDash currently always adds 1 to the layer count - I didn't know that DisplayLayerProgress supports an offset. The OctoDash offset will be removed in the next version, so everything is in sync. Thanks for the info!

**Comment by evilbobbins** [comment]
That's great thanks for the speedy reply :) amazing work btw :)
