### ISSUE TITLE
Unable to view SD CARD files plugged into Prusa MK3S

### ISSUE THREAD

**Issue by Richardgriff** [UnchartedBull/OctoDash#481]
**Describe the bug**
Frist Off i would liek to say what a wonderfull product. The UI i just amazing. However i am am having issue.

I am unable to view files that are on the SD CARD plugged into my prusa mk3s.

Launch the OCTOPRINT browser UI shows the SD CARD FILES listed. Octodash is unable to see these files.

send the command

octopi.local/api/files?recursive=true 
X-Api-Key: *************

Returns a json with all the files listed.

If i generate a folder from OCTOPI this is displayed correctly in OCTODASH

Running the get file command again gives back all files. This time however it shows  the TEST folder as having a origin as "local".

This would suggest that files with origin of "sdcard" are unable to be seen by octodash.

**Expected behavior**
SD files should show in octodash as they do in octoprint

**Screenshots**
![image](https://user-images.githubusercontent.com/4070138/76245741-50b3bf00-6234-11ea-82cb-c730b41e663f.png)

**General Information:**
Rasberry PI 3B+ with Offical 7 inch Touch screen
Octoprint Version 1.4.0
Octopi version 0.17.0
Octodash version 1.4.0

**Comment by UnchartedBull** [comment]
SD Card files aren‘t supported right now. Not all info is available for SD Card files, thus they are omitted. Feel free to open a PR to include these, I don‘t have the time currently. Sorry!

**Comment by daddiomattyb** [comment]
I am not sure what you mean by SD card files.

**Comment by Richardgriff** [comment]
Thanks for the quick response. if you can point me in the direction of the file handler I can maybe take a look. Not promising anything as my programming skills are basic but willing to help.

**Comment by UnchartedBull** [comment]
src/app/files/* (should be .ts / .scss and .html file) and src/app/files.component.ts are the relevant files for this :)
