### ISSUE TITLE
OctoDash installed but not working

### ISSUE THREAD

**Issue by daddiomattyb** [UnchartedBull/OctoDash#483]
**Describe the bug**
After installing OctoPrint, connecting to the network and installing OctoDash it shows on my LCD, and Touch works, however I get the following errors every time.
Can’t retrieve layer progress : HTTP://localhost:5000/plugin/displaylayerprogress/values : 403 forbidden
Can’t retrieve printer status: HTTP://localhost:5000/api/printer : 403 forbidden
Can’t retrieve jobs: HTTP failure response for https://localhost:5000/api/job : 403 forbidden

**To Reproduce**
1. Install OctoPrint
2. Connect to the network wifi.
3. Install OctoDash via the script and reboot.

**Expected behavior**
OctoDash screen should show and touch interface work and be able to work normal.

**Screenshots**

**General Information:**
 - Hardware Raspberry Pi 3b+ - UCTronics 3.5 " TFT 480x320
 - OS Info Used the OctoPrint latest build
 - OctoDash Version latest available
 - OctoPrint Version 0.17.0

**Additional context**
The screen and touch interface work fine, but the errors keep showing over and over.

**Comment by UnchartedBull** [comment]
Probably an invalid access token. Please double check your token.

**Comment by daddiomattyb** [comment]
Not sure how to even get a token. Are we talking about the same OctoDash? I did not read anything about tokens.

**Comment by UnchartedBull** [comment]
It‘s called API Key in OctoDash I think. Here is the information on how to get it: http://docs.octoprint.org/en/master/api/general.html

**Comment by daddiomattyb** [comment]
Thank you. I found an API section, and it looks like it is blank. Do I copy an API from Octoprint settings under my user account and type it in there?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by daddiomattyb** [comment]
Thank you. I was able to have the errors go away long enough to get a screenshot. In this picture, is this where I put the API key, and if so, do I get it from Octoprint settings?
 [Image]

**Comment by UnchartedBull** [comment]
You need to copy the API Key from the Settings over to there. Should be a string with big characters and numbers.

**Comment by daddiomattyb** [comment]
That did it. Thank you all for your help. Its all up and running and I am printing again.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by floridaservices** [comment]
Just to add since this app is new for me, the API key IS case sensitive, in case anyone else comes across this in the future.

**Comment by ecarpenter2** [comment]
I am still getting this error.  I have the API correct, but it rotates between the errors mentioned above.

**Comment by UnchartedBull** [comment]
If you are also getting the 403 Forbidden:

Please check that the user you created the token from is allowed to use the API. Double check that the token is correct (case-sensitve, no leading or trailing spaces).

**Comment by ecarpenter2** [comment]
Thanks for your reply.  Yes the API is correct.  Where do I check and see
if the API can be used?

Everett E. Carpenter, PhD, MBA
804-723-1005

**Comment by Steve021171** [comment]
Well, there is NO WAY to add a API key into an existing Octodash....
Nowhere in the settings you have the capability to enter a API key. And this f*cking message never stops showing up.... so anoying.

So, HOW can I enter the API key in a running Octodash???

**Comment by UnchartedBull** [comment]
just like described in the wiki: https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings#inputs--settings-explained

**Comment by Steve021171** [comment]
Tried, no file found, it is an empty file....

Why no menu to enter settings like that? and the message should not come up every second. One time in the beginning is enough...

**Comment by Steve021171** [comment]
ok, you have to stop the service to get into that...

**Comment by Steve021171** [comment]
Even that didn't worked for me... I'm done, will switch to Octoscreen.
Thanx

**Comment by Steve021171** [comment]
Well, I tried Octoscreen, what works great.... but has no option to turn off screen while inactive.
Went to OctoBTT, what looks like Octodash but has no option to turn off screen either.

Went back to Octodash, still same Problem. Never accepted the API key. So I reinstalled Octoprint and OctoPi from scratch. Never get past the setup screen. 
API key was correct, but every time at the end of the setup process it shows error 403.

After hours of trying and cursing I figured out that LOCALHOST or the real IP does not work, but after I put 127.0.0.1 in it starts working.
So no clue why this makes a difference, but just i case somebody has the same problem : try 127.0.0.1 instead of localhost.

regards
