### ISSUE TITLE
 Cannot connect to octoprint

### ISSUE THREAD

**Issue by yaawl** [UnchartedBull/OctoDash#536]
Hi, 

I have a problem connecting my printer to octodash. It writes "Cant retrieve printer status" error for my url to octoprint. Does anyone have the same problem or could you please advise me? Thank you very much!

![IMG_7524](https://user-images.githubusercontent.com/60353945/78059517-46e03000-738a-11ea-8255-cbcc58208900.JPG)
![IMG_7523](https://user-images.githubusercontent.com/60353945/78059570-5d868700-738a-11ea-91c3-facdbf906030.JPG)
![IMG_7521](https://user-images.githubusercontent.com/60353945/78059637-77c06500-738a-11ea-9ee9-240c8fdfe2d7.JPG)

**Comment by UnchartedBull** [comment]
Somehow your config seems to be really messed up. Did you edit you config manually? Please go into the settings menu and adjust your config (Don‘t include your token anywhere except in the field that das say API Tolen). Host / IP should only include the IP of your Pi with no slashes etc.

**Comment by fafo17** [comment]
I've the same issue, did you solved that?

**Comment by UnchartedBull** [comment]
Please provide more information in either this issue or a new one. This way I, or someone else can help you. But deleting the config for OctoDash and starting from scratch again might be your best shot for now.
