### ISSUE TITLE
Explain ports and host in Troubleshooting guide

### ISSUE THREAD

**Issue by ChaosBlades** [UnchartedBull/OctoDash#560]
Unless I am mistaken the default OctoPrint port number will be 80 for 99% of installations. So that is what it should be during setup instead of 5000.

Edit: This is to avoid confusion during setup. Most users like I did assume the provided port is what a standard installation of OctoPrint would be set to.

**Comment by fruvous** [comment]
Port 5000 is the port that the API uses

**Comment by ChaosBlades** [comment]
Weird. It would not work for me. Only port 80 worked.

**Comment by nicwilson58** [comment]
5000 worked fine for me

**Comment by ChaosBlades** [comment]
Does 80 work for you?

**Comment by harleyg321** [comment]
The haproxy config in octopi just redirects port 80 to 127.0.0.1:5000, so in theory (assuming octodash and octoprint are running on the same pi) octodash should always work when pointed at 127.0.0.1:5000 (or localhost:5000) even if port 80 is also accessible.

Using port 80 would require haproxy set up to forward the port. Octopi may have this enabled by default (it looks like), but for example I just installed octoprint on raspbian so I don't have haproxy running.

**Comment by ChaosBlades** [comment]
Ah, so my problem is that I used the same IP as when I log in from my browser instead of localhost.

Can we add this information to the Wiki Troubleshooting section?

**Comment by UnchartedBull** [comment]
5000 is the default port. I‘ll add this info to the troubleshooting guide later. Thanks for the info!

**Comment by UnchartedBull** [comment]
Has been added to the troubleshooting guide alongside with a brief documentation about each setting.
