### ISSUE TITLE
Vertical Layout

### ISSUE THREAD

**Issue by fruvous** [UnchartedBull/OctoDash#561]
**Is your feature request related to a problem? Please describe.**
Using a screen on MP Select Mini and the best way to mount it is vertically.

**Describe the solution you'd like**
Option for a vertical layout

**Comment by UnchartedBull** [comment]
This would require some major rewrite of almost every screen. I don‘t think I‘ll have the time to work on this in the near future. But may be something interesting in the future.

**Comment by UnchartedBull** [comment]
This will need to be achieved via custom-styles. OctoDash won't support vertical screens out of the box natively. Sorry!
