### ISSUE TITLE
OctoScreen Rebooting Constanly

### ISSUE THREAD

**Issue by mbfab** [UnchartedBull/OctoDash#575]
Im new to OctoScreen and have encountered a problem, that Octoscreen rebooting, starts up and after a few seconds it reboots again in an endless loop. Do anyone have a solution for this problem?

Have a video of the problem that you could download if you think that might help.

https://www.dropbox.com/s/eg75plnxasj42yu/IMG_8245.MOV?dl=0

**Comment by harleyg321** [comment]
You might want to create an issue in the OctoScreen repo https://github.com/Z-Bolt/OctoScreen ;)
