### ISSUE TITLE
OctoPrint Printer Profiles

### ISSUE THREAD

**Issue by jaymcd** [UnchartedBull/OctoDash#607]
Love the interface and solution. It would be great if the printer name or details got pulled from Octoprint or if multiple printer names/profiles were supported. I swap out/change printers sometimes and it would be good to support this.

**Comment by UnchartedBull** [comment]
Is there even a Printer Name in OctoPrint? Do you know which API can be used to retrieve this, if there is an API available, it shouldn't be much work to switch that around.

**Comment by jaymcd** [comment]
There are printer profiles with the name, model, nozzle and filament size, axis travel settings, etc.

Not sure about the API. You could check with Gina or the wiki.

Jay McDonald

**Comment by Ga1j1n** [comment]
Gotta second this, I have multiple printers with multiple OctoPi setups if I could run octodash on on of them to act as a hub that would reduce would make this project even more fantastic as a touchscreen for each is a bit excessive. perhaps a home screen to select which instance to control?

**Comment by jaymcd** [comment]
I don’t need to have it support simultaneous connections but be able to swap them in and out when needed.

Octofarm can do the multiple printer thing but I don’t use it yet.


Jay McDonald

**Comment by UnchartedBull** [comment]
Will merge this with #922.
