### ISSUE TITLE
Support for Prusa Thumbnails plugin 

### ISSUE THREAD

**Issue by ruralaccent** [UnchartedBull/OctoDash#614]
A fairly new plugin for octoprint is 'Prusa Thumbnails'. It's been extremely well received and really adds a great deal to the system. It displays embedded thumbnails from STL files in the file list and also in the details about what's currently printing. Would it be at all possible to add support for thumbnails to ti's awesome dashboard, please? Thank you!

**Comment by noxhirsch** [comment]
It's already integrated (and should come live with the next release): https://github.com/UnchartedBull/OctoDash/pull/601

**Comment by ruralaccent** [comment]
Great! Thank you :)
