### ISSUE TITLE
Feature Request: Allow custom CSS

### ISSUE THREAD

**Issue by noxhirsch** [UnchartedBull/OctoDash#616]
**Is your feature request related to a problem? Please describe.**
I'd like to adjust the style of OctoDash to my needs. At the moment this is only possible by building it myself

**Describe the solution you'd like**
Allow the user to have a theme.css file in a specific folder which would allow "endless" styling possibilities with the "official" build app (and especially without building after every style change)

**Link other projects**
If you want OctoDash to include other OctoPrint plugins or similar please link them here.

**Additional context**

**Comment by UnchartedBull** [comment]
Makes sense. Will work on this after v2 release.

**Comment by UnchartedBull** [comment]
Good news: I decided to squeeze this in before the 2.0 release. So this will be available very soon! :)

**Comment by noxhirsch** [comment]
You're amazing! Thank you very much! 🎉

**Comment by Mearman** [comment]
Looking forward to it
