### ISSUE TITLE
screensaver with hyperpixel 4" (gpio) 

### ISSUE THREAD

**Issue by gsxrnoir2001** [UnchartedBull/OctoDash#617]
I want to use a screensaver on my PI3B +, octopi 0.17.0 octoprint 1.4.0 and octodash to save my screen, especially during long prints. screenblank has worked only once, but since it no longer works, do you have a solution?

**Comment by UnchartedBull** [comment]
Adjust your `~/.xinitrc` accordingly and disable turnOffScreenWhileSleeping. Then you can setup everything in the file mentioned above with `xset`. 

The Hyperpixel is AFAIK no OLED display, so it has virtually no burn-in.
