### ISSUE TITLE
Display network status icon with a current IP address

### ISSUE THREAD

**Issue by rafiki270** [UnchartedBull/OctoDash#622]
With multiple printers moving between locations I struggle figuring out what IP each printer has and if it's connected at all

A network icon indicating connection on the dashboard would be amazing with a modal info screen with IP or potentially other network details available on tap

**Comment by UnchartedBull** [comment]
I think this will also be related to the multi printer support, right? And you would like to see the current network status for each of the saved printers?

**Comment by rafiki270** [comment]
> I think this will also be related to the multi printer support, right? And you would like to see the current network status for each of the saved printers?

I am not sure I understand the question. I thought every RaspberryPi has it's own IP and settings, not each printer?

**Comment by UnchartedBull** [comment]
So you want to see the public IP of the OctoPrint instance, that OctoDash is currently connected to?

**Comment by rafiki270** [comment]
> So you want to see the public IP of the OctoPrint instance, that OctoDash is currently connected to?

Yes :)

**Comment by italocjs** [comment]
This is quite helpful if there are multiple printers and IP is not static

**Comment by UnchartedBull** [comment]
merging with #1148.
