### ISSUE TITLE
Model thumbnails for PrusaSlicer

### ISSUE THREAD

**Issue by radimsejk** [UnchartedBull/OctoDash#633]
There is option to generate model thumbnails into gcode from PrusaSlicer. Would it be possible to preview them on display of OctoDash?

Something similar as [this](https://plugins.octoprint.org/plugins/prusaslicerthumbnails/) but on the screen.

**Comment by thegarbz** [comment]
This is already implemented and will be published in the next release. Will depend on the PrusaSlicerThumbnails plugin.

**Comment by radimsejk** [comment]
That's great! Thank you.

**Comment by floridaservices** [comment]
the dev version(with DLP turned off) has this, it's neat!

**Comment by UnchartedBull** [comment]
should be released for productive version in a couple of hours together with the filament change process (if everything works)
