### ISSUE TITLE
Support Question: What are the ideal thumbnail dimensions?

### ISSUE THREAD

**Issue by thegarbz** [UnchartedBull/OctoDash#648]
Is there an ideal set of dimensions to generate thumbnails for use in OctoDash?
When setting up PrusaSlicer I have adopted the Prusa Mini settings of 16x16 and 220x124. In OctoPrint it simply crops its display. In OctoDash it doesn't.

The result is: https://imgur.com/a/OjnRVpl
Fine in the file selection, but absolutely pointless on the print progress display (7" 1024x600 display)

Does OctoDash benefit from a specific dimension of thumbnail?

**Comment by EPDCenter** [comment]
To me, it only appears from the file browser, but when printing, the thumbnail does not appear, I am using PrusaSlicer

**Comment by UnchartedBull** [comment]
Any Square aspect ratio should work fine. I think I did 256x256 and don’t have this problem.

@EPDCenter just tap the percentage and will switch around :)

**Comment by thegarbz** [comment]
Thanks, yes square ratios work a bit better. Possibly worth adding to the "Tips and Tricks" section.

**Comment by EPDCenter** [comment]
![IMG_20200516_221233](https://user-images.githubusercontent.com/8399211/82129386-aa9bac80-97c2-11ea-8701-15a173d3d993.jpg)
256x256 thumbnail :S any idea?

**Comment by thegarbz** [comment]
That circle doesn't look round, is there something janky with the resolution on your screen which is affecting the layout on the UI?

**Comment by EPDCenter** [comment]
Solved, many thanks !!!

**Comment by UnchartedBull** [comment]
Has been updated, thanks :)

**Comment by Dryphter** [comment]
> Solved, many thanks !!!

@EPDCenter What was the fix for this?   I have OctoDash running on a Pi 3, Adafruit 3.5" PiTFT display (480x320) and have the same issue that you posted above?  The circle on mine is round, but the thumbnail looks like the image you posted and there is a gap between the 'Layer x of x' line and the name of the printer.
