### ISSUE TITLE
Possible Issue with Scrolling

### ISSUE THREAD

**Issue by ruralaccent** [UnchartedBull/OctoDash#675]
Pi4/4GB
Hyperpixel 4 Screen
Octodash v1.5.0

I seem to have an issue on my two seperate Pi4 install, whereby the bottom item of the list of files does not appear on the screen, other than a small part of the top of the name:

![20200518_211506](https://user-images.githubusercontent.com/51720842/82708579-7fa7d180-9c76-11ea-97dd-ef93e17f52e8.jpg)

You can't really read the dir/filename, but you can tap it to select it. It won't scroll down any further.

Edit: Just to confirm, the full extent of the screen is shown - it's not clipped by the enclosure! 

I don't seem to have a scrolling issue with anything else on this screen, so I wonder if it may be Octodash. Does anyone else have this issue?

Many thanks :)

**Comment by UnchartedBull** [comment]
Does this only happen on the file screen or are there other things cut off as well, i.e. in the settings or the main screen?

And can you please confirm, that you've setup the resolution of your screen correctly?

**Comment by ruralaccent** [comment]
I've got a couple of prints running just now, so will double check those points later today. However, I'm pretty sure that the resolution is fine. Will report back...

**Comment by ruralaccent** [comment]
I checked the pi last night and I can confirm that the resolution is ok and the bottom entry is mainly off screen on all of the subdirs. I will try adding more dirs/files to the main menu to see if that is any different.

**Comment by UnchartedBull** [comment]
Ok ... Could you please check if the mainscreen (https://github.com/UnchartedBull/OctoDash/blob/master/screenshots/main-screen.png) and settings screen (https://github.com/UnchartedBull/OctoDash/blob/master/screenshots/settings.png) are cropped as well? Maybe also if the file details are fully visible?

The Hyperpixel 4.0 uses 800x480 resolution, doesn't it?

**Comment by ruralaccent** [comment]
I can't check the screens just now as both printers are running jobs, but looking at the image on my other open issue, it looks like the top of the screen is not cropped, but the bottom is slightly cropped on the main screen. I hadn't noticed that before.

![82824254-e8729200-9ea0-11ea-8aa1-ec6b890cf205](https://user-images.githubusercontent.com/51720842/82889866-4c4d9700-9f43-11ea-9cac-fc84c93ae747.jpg)

**Comment by UnchartedBull** [comment]
At least that image doesn't look cropped to me, this looks like the normal padding for 800x480 screen. I'll try to replicate this. It isn't happening on your other machine though?

**Comment by ruralaccent** [comment]
It occurs on both of my installations. Both use the same type of Hyperpixel screen.

**Comment by UnchartedBull** [comment]
Hi, sorry for my late response to this. I think I fixed the bug, please try the following build and report back, whether that fixed it: https://drive.google.com/file/d/13V0M-ddeYHP-DSQ1b4Da1Gv0XjXUT2kS/view?usp=sharing. Thanks for your patience!

**Comment by ruralaccent** [comment]
No worries on the delay. How do I update to that build?

**Comment by UnchartedBull** [comment]
Download that file to your raspberry (i.e. with wget) and then just run `sudo dpkg -i <downloaded-file>` and then reboot

**Comment by ruralaccent** [comment]
Sorry I didn't manage to test this. My wife went into labour! I'll update to the new version of Octodash and let you know if all is ok.

**Comment by ruralaccent** [comment]
Yes. The new version fixes the issue. Thank you!

**Comment by UnchartedBull** [comment]
That's definitely more important :) good luck to all of you and not so many sleepless nights ;)
