### ISSUE TITLE
Custom Actions: M0 not working + Not detecting M0 in regular GCODE

### ISSUE THREAD

**Issue by FlyingT** [UnchartedBull/OctoDash#677]
I encountered 2 problems related to the M0 Pause Print command.

**General Information:**
 - Hardware: Raspberry Pi 3B with Touchscreen
 - OctoPi 0.17.0
 - OctoDash Version NEWEST
 - OctoPrint Version V1.4.0

-------------- Problem 1 ------------------
**What doesn't work?**
I'am trying to set and Custom Action to level the bed. The printer goes to the location I set in GCODE, but it wont wait there, ignoring the M0 command.

**What did you already try?**
Different formatting, like M0;[SPACE] or M0[SPACE];[SPACE]

**Additional context**
Gcode I try to run:
M190 S60 ; G90 ; G28 ; G1 Z5 ; G1 X32 Y36 ; G1 Z0 ; M0 ; G1 Z10 ; G1 X32 Y206 ; G1 Z0 ; M0 ; G1 Z5 ; G1 X202 Y206 ; G1 Z0 ; M0 ; G1 Z5 ; G1 X202 Y36 ; G1 Z0 ; M0 ; G1 Z5 ; G1 X117 Y121 ; G1 Z0 ; M0 ; G1 Z5 ; G1 X32 Y206 ; G1 Z0 ; M0 ; G1 Z5 ; G1 X202 Y206 ; G1 Z0 ; M0 ; G1 Z5 ; G1 X202 Y36 ; G1 Z0 ; M0 ; G1 Z5 ; G1 X32 Y36 ; G1 Z0 ; M0 ; G28; M84 ;

Custom Action:
 "icon": "ruler-combined",
                                        "command": "[GCODE from above, all in one line] ; "
                                        "color": "#7f8fa6",
                                        "confirm": false,
                                        "exit": false

-------------- Problem 2  ------------------
**What doesn't work?**
Running the same GCode as an regular file works,  OctoDash even recognizes the print was paused, see the [Picture here](https://prnt.sc/smbfnr). But there is no buttom to continue the print. It will resume if I press on the screen, use the Pause Button from OctoDash and then press on resume [in this screen](https://prnt.sc/smbg9b). It should be displaying this screen after the print was paused (I guess?)

**Additional context**
GCode on [Pastebin](https://pastebin.com/exMjJpC0)

**Comment by UnchartedBull** [comment]
Does M0 work if you send it via OctoPrint directly? I think I saw some threads about OctoPrint and M0/M1. If M0 works fine with the OctoPrint GCode CLI then I can further investigate this.

Regarding the other issue, yeah it totally makes sense to automatically switch to the pause screen. Will work on this after v2 release.
