### ISSUE TITLE
Your config is Invalid ??

### ISSUE THREAD

**Issue by Thull3** [UnchartedBull/OctoDash#681]
I got invalid cconfig after update to latest version 

Tried to uninstall and install again but still the same message 
Im not to good at code so i cant find the config file ?
Dont know how to type in putty to get to file ??
i Have raspberry pi 3b with 7 inch touch display and octoprint on it

**Comment by UnchartedBull** [comment]
More info here: https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings#settings-file. You can either delete the file with `rm` and do the setup again or open it with a text editor `nano` for example to fix it.

**Comment by Thull3** [comment]
But the thing is I don’t know how to go to the config file .. what command to open it 

Skickat från min iPhone

**Comment by I-like-stuff** [comment]
You would use:
 `sudo nano /.config/octodash/config.json ` To edit it
or
 `sudo rm  /.config/octodash/config.json ` to remove it

If nano isn’t installed which it should install it with:
`sudo apt-get install nano`

**Comment by UnchartedBull** [comment]
Probably go with removing the config as @I-like-stuff has already posted. Using GNU Text editors takes some getting used to :)
