### ISSUE TITLE
Cannot run it. Nothing happened after reboot.

### ISSUE THREAD

**Issue by vkilin** [UnchartedBull/OctoDash#700]
I ran script from installation tab:
wget -qO- https://github.com/UnchartedBull/OctoDash/raw/master/scripts/install.sh | bash -s -- --ptg
Since I had TouchUI installed I did fully uninstall it by command:
sudo ~/TouchUI-autostart/helpers/uninstall

Now I have raspberry desktop on touchscreen. and if I  ran install Octodash command through Putty it says installed, but nothing changes on touch screen.
Please advice. Octoprint itself works fine through web console.
  

**General Information:**
 - Hardware Raspberry Pi with TFT 320x240 3.5 inch touch screen
 - OS Info OctoPi 4.19.97

As I understood OctoScreen is totally different, but there is a lot of guides how to set it up but there is 0 guides for Octodash

**Comment by UnchartedBull** [comment]
If you want to start OctoDash via putty please execute the following:

```
export DISPLAY=:0
octodash
```

If that works please add octodash to the automatically started applications in your desktop environment configuration (there should be plenty of tutorials for that, maybe search for Raspbian Chrome Kiosk Mode)

**Comment by vkilin** [comment]
Yes, I tried this as well. I have this massage:
"(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
"

**Comment by vkilin** [comment]
It works, since Putty showing some error massage:
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

On the touchscreen I see welcome screen for Octodash! Thanks!
One more question, what is Feed Lenght and Feed speed for Prusa i3 mk3s, maybe you know?

**Comment by UnchartedBull** [comment]
Great, that this works for you. Feed Length should be around 30-40mm and Feed Speed should be rather slow (you don't need the filament to travel that much). I use 30mm/s for my Titan Extruder.
