### ISSUE TITLE
DisplayLayerProgress causes high CPU load and printing stalls during small movements

### ISSUE THREAD

**Issue by chunter1** [UnchartedBull/OctoDash#718]
Is it possible to let OctoDash run without the need of having the DisplayLayerProgress plugin installed?

I got issues with printing stalls due to high CPU load on the raspberry Pi using octoprint because of the DisplayLayerProgress plugin.
When this plugin is enabled, the CPU load of the raspberry is constantly over 100% causing print stalls when lots of small movelents (circles etc.) are active.
This i issue is also mentioned e.g. here:
https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/124

**Comment by UnchartedBull** [comment]
Has been addressed in #584. There is a dev version 1.5.0 linked there with DLP disabled temporarily. I'll post the link to the follow-up issue there.
