### ISSUE TITLE
Possible to add functionnality to command raspberry

### ISSUE THREAD

**Issue by jpreculeau** [UnchartedBull/OctoDash#719]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. If applicable also link other issues / bugs here.

**Describe the solution you'd like**
Would like to be able to reboot raspberry and to turn it off

**Link other projects**
If you want OctoDash to include other OctoPrint plugins or similar please link them here.

**Additional context**
just like that
https://github.com/Z-Bolt/OctoScreen/blob/master/docs/README.md#system-info-and-commands

**Comment by UnchartedBull** [comment]
Already supported: https://github.com/UnchartedBull/OctoDash/wiki/Custom-Actions#predefined-actions
