### ISSUE TITLE
File manager screen gets in locked state

### ISSUE THREAD

**Issue by JeffB42** [UnchartedBull/OctoDash#733]
**Describe the bug**
I've encountered a state where OctoDash becomes unresponsive and doesn't respond to touch or clicks.

**To Reproduce**
1. This issue requires there to be no files (either on SD card or in OctoPrint)
2. Run OctoDash, then click on the folder icon
(there are no files, and none should be listed)
3. Click on the Sort button in the upper right
4. The Sort modal then comes up.  Click the Close button to close the modal.
5. At this point, we're still in the File Manager screen.  Click either the Back button (upper left) or the Sort button (upper right)

**Expected behavior**
At this point, the screen does not respond to either clicks (using a mouse) or touching the touch screen, and the app becomes "locked" because it's stuck in the File Manager page and doesn't respond to user input.

Note, this only happens when there are no files.

**Comment by UnchartedBull** [comment]
Hi, sorry for my late reply. I'll make sure to remove the sort button if there are no files available. Thanks for the report!
