### ISSUE TITLE
How to replace "G1" command in motion control?

### ISSUE THREAD

**Issue by chunter1** [UnchartedBull/OctoDash#734]
Since Klipper firmware does not allow any moves without a homing sequence before, it refuses any G1 command sent from OctoDash.
However there is a command in Klipper called "FORCE_MOVE" that can be used instead.
My question is if and how it is possible to replace the "G1" command by e.g. "FORCE_MOVE STEPPER=stepper_x DISTANCE=0.01 VELOCITY=10"?

**Comment by UnchartedBull** [comment]
Hi, sorry for my late reply. I don't know, whether that is possible or not. I'm not sending the GCode directly to the printer, but I'm rather using the OctoPrint Jog command: https://docs.octoprint.org/en/master/api/printer.html#issue-a-print-head-command. Maybe if you could overwrite what OctoPrint does with that it should work. Maybe ask in the forums if anyone knows where to start.
