### ISSUE TITLE
UI Inconsistency - Filament manager vs main dash

### ISSUE THREAD

**Issue by thegarbz** [UnchartedBull/OctoDash#770]
I noticed recently that filament management seems to have the temperature interface reversed from the rest of the interface. 

Main dashboard:  Actual Temperature / Target Temperature 
Printing dashboard: Actual Temperature / Target Temperature
Filament manager pre-heat: Target Temperature / Actual Temperature.

**Comment by UnchartedBull** [comment]
Good catch! Will switch those around. Thanks.
