### ISSUE TITLE
Screen Calibration

### ISSUE THREAD

**Issue by Hawkins00000** [UnchartedBull/OctoDash#783]
Is there an easy way to temporarily disable OctoDash from launching, so that I can run the calibration utility, then re-enable it, so it auto boots into the tool? 

I have a 5in HDMI screen that is working with a few HTTP errors, that sporadically appear,... but my current issue is touch panel caligration.

Sorry< I am a noob, and am not familiar enough with now your awesome tool is integrated.

Great tool though! TY

**Comment by UnchartedBull** [comment]
You could either edit your `~/.xinitrc` and put a `#` in front of the line that reads octodash (which will prevent OctoDash from starting up). Or you could get the process id (i.e. with `pgrep octodash`) and then just use `kill <process id>` to stop OctoDash while running.

**Comment by UnchartedBull** [comment]
There is also a custom action available to stop OctoDash: https://github.com/UnchartedBull/OctoDash/wiki/Custom-Actions#predefined-actions (`[!STOPDASHBOARD]`)
