### ISSUE TITLE
Desktop 

### ISSUE THREAD

**Issue by niklask52t** [UnchartedBull/OctoDash#793]
Do i need a desktop Installation?

**Comment by Dryphter** [comment]
No. I just installed OctoDash today. Fresh Octoprint install with the latest image and then follow the octodash install instructions.  The Octoprint image doesn’t include a desktop environment. The only thing you may have to do is make sure you have the right driver for your screen.

**Comment by UnchartedBull** [comment]
Nope not needed. Ratpoison will be installed by default as the window manager.
