### ISSUE TITLE
Screensaver

### ISSUE THREAD

**Issue by niklask52t** [UnchartedBull/OctoDash#809]
Is it possible that the screen turns off after a while? and also in the print monitor?

**Comment by ChaosBlades** [comment]
Both my adafruit pitft plus 3.5" and OSOYOO 5 inch DSI Touch Screen turn off the backlight after a while. My best guess is that whatever screen you are using isn't supported and you will need to get a different screen.

Same goes for the screens in the Supported Devices Wiki page.
https://github.com/UnchartedBull/OctoDash/wiki/Supported-Devices

**Comment by UnchartedBull** [comment]
There are 2 options:

- enable screen sleep in OctoDash (only turns off the screen if disconnected and sleep mode is active)
- adjust your `~/.xinitrc` and set up DPMS normally (disable OctoDash's sleep feature then) - this will then always work and turn off the screen after the set amount of time.
