### ISSUE TITLE
Ultimaker Format Package OctoPrint Plugin is required to support UFP files in OctoPrint

### ISSUE THREAD

**Issue by ChaosBlades** [UnchartedBull/OctoDash#812]
In order to utilize OctoDash's ability to use ufp files the user would need to install the Ultimaker Format Package OctoPrint Plugin. Since other plugins are automatically installed on installation this one might as well be as well. Otherwise, OctoPrint shows and error when you try to upload upf files.

https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage

**Comment by UnchartedBull** [comment]
The new installation script offers the option to install the UFP plugin. Not everyone uses Cura though, so there is no need to make this mandatory, as it is useless for other slicers. Also the plugins page in the wiki offers some info there. That should be enough, shouldn't it?

**Comment by ChaosBlades** [comment]
Last time I installed must have been before the new script.. Thats what I was asking for.
