### ISSUE TITLE
Fan Percentage won't be updated

### ISSUE THREAD

**Issue by nicedevil007** [UnchartedBull/OctoDash#814]
I'm using marlin TFT during print to setup everything (like Z-Offset) if needed anytime.

I figured out that adjusting the fanspeed to another percentage than it was setup in the gcode won't be updated as expected in octodash.

Fan stays at the point how it is setup in the gcode.

**Comment by UnchartedBull** [comment]
Yep, can't do anything about that unfortunately. Marlin doesn't report the fan speed, so OctoPrint doesn't know what the current fan speed is, thus OctoDash can't know either. DisplayLayerProgress uses the GCode to extract the fan speeds that are defined in the scripts, but that's the best info we can get, manual overwrites won't be reported anywhere ...

**Comment by nicedevil007** [comment]
Oh, didn't know that :/

**Comment by nicedevil007** [comment]
Maybe it is fixed now? Marlin 2.0.6 :)

#define REPORT_FAN_CHANGE   // Report the new fan speed when changed by M106 (and others)

**Comment by UnchartedBull** [comment]
Once OctoPrint supports that command I'll update OctoDash :) I haven't found an issue in the repo though, so maybe go ahead and open one over there :)
