### ISSUE TITLE
problems when trying to install octodash

### ISSUE THREAD

**Issue by bensaminge** [UnchartedBull/OctoDash#839]
hi guys im a complete novice to coding and linux and the pi. im trying to do the automatic install for octodash and its having trouble finding some files. i will leave a copy of the text below. many thanks

bash <(wget -qO- https://github.com/UnchartedBull/OctoDash/raw/mter/scripts/install.sh)
Installing OctoDash v1.5.0
Installing Dependencies ...
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Package libatspi2.0-0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libnss3 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package bc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libnotify4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package xserver-xorg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  xserver-xorg-core

Package desktop-file-utils is not available, but is referred to by another pacge.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libsecret-1-0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libnotify4' has no installation candidate
E: Package 'libnss3' has no installation candidate
E: Package 'libatspi2.0-0' has no installation candidate
E: Unable to locate package libappindicator3-1
E: Package 'libsecret-1-0' has no installation candidate
E: Package 'xserver-xorg' has no installation candidate
E: Unable to locate package ratpoison
E: Unable to locate package xinit
E: Package 'bc' has no installation candidate
E: Package 'desktop-file-utils' has no installation candidate

**Comment by fwdixon** [comment]
The auto-install script hung up for me, I had to install manually (which, btw, the instructions refer to v2.0.0, but 1.5.0 is the current release).

**Comment by stevo1957** [comment]
The auto install script is not working for me either.

I am getting these errors:

Failed to fetch http://raspbian.melbourneitmirror.net/raspbian/pool/main/libe/libevdev/libevdev2_1.6.0+dfsg-1_armhf.deb

Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by stevo1957** [comment]
I just tried a manual install and am also receiving errors:

pi@octopi:~ $ sudo apt install libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libuuid1 libappindicator3-1 libsecret-1-0 gir1.2-gnomekeyring-1.0
[sudo] password for pi:
Reading package lists... Done
Building dependency tree
Reading state information... Done
libuuid1 is already the newest version (2.33.1-0.1).
libxss1 is already the newest version (1:1.2.3-1).
libxss1 set to manually installed.
libxtst6 is already the newest version (2:1.2.3-1).
libxtst6 set to manually installed.
The following additional packages will be installed:
  adwaita-icon-theme at-spi2-core dbus-user-session dconf-gsettings-backend dconf-service gir1.2-glib-2.0 glib-networking glib-networking-common
  glib-networking-services gsettings-desktop-schemas gtk-update-icon-cache libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libauthen-sasl-perl libcairo-gobject2
  libcolord2 libcups2 libdata-dump-perl libdbusmenu-glib4 libdbusmenu-gtk3-4 libdconf1 libencode-locale-perl libepoxy0 libfile-basedir-perl libfile-desktopentry-perl
  libfile-listing-perl libfile-mimeinfo-perl libfont-afm-perl libfontenc1 libgirepository-1.0-1 libgnome-keyring-common libgnome-keyring0 libgtk-3-bin libgtk-3-common
  libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl
  libhttp-message-perl libhttp-negotiate-perl libindicator3-7 libio-html-perl libio-socket-ssl-perl libio-stringy-perl libipc-system-simple-perl libjson-glib-1.0-0
  libjson-glib-1.0-common liblwp-mediatypes-perl liblwp-protocol-https-perl libmailtools-perl libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl
  libnet-ssleay-perl libnspr4 libproxy1v5 librest-0.7-0 librsvg2-common libsecret-common libsoup-gnome2.4-1 libsoup2.4-1 libtie-ixhash-perl libtimedate-perl
  libtry-tiny-perl liburi-perl libwww-perl libwww-robotrules-perl libx11-protocol-perl libxaw7 libxcomposite1 libxft2 libxml-parser-perl libxml-twig-perl
  libxml-xpathengine-perl libxmu6 libxpm4 libxt6 libxxf86dga1 notification-daemon perl-openssl-defaults x11-utils x11-xserver-utils
Suggested packages:
  libdigest-hmac-perl libgssapi-perl colord cups-common gnome-keyring gvfs libcrypt-ssleay-perl libauthen-ntlm-perl libunicode-map8-perl libunicode-string-perl
  xml-twig-tools mesa-utils nickle cairo-5c xorg-docs-core
The following NEW packages will be installed:
  adwaita-icon-theme at-spi2-core dbus-user-session dconf-gsettings-backend dconf-service gir1.2-glib-2.0 gir1.2-gnomekeyring-1.0 glib-networking
  glib-networking-common glib-networking-services gsettings-desktop-schemas gtk-update-icon-cache libappindicator3-1 libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data
  libatspi2.0-0 libauthen-sasl-perl libcairo-gobject2 libcolord2 libcups2 libdata-dump-perl libdbusmenu-glib4 libdbusmenu-gtk3-4 libdconf1 libencode-locale-perl
  libepoxy0 libfile-basedir-perl libfile-desktopentry-perl libfile-listing-perl libfile-mimeinfo-perl libfont-afm-perl libfontenc1 libgirepository-1.0-1
  libgnome-keyring-common libgnome-keyring0 libgtk-3-0 libgtk-3-bin libgtk-3-common libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl
  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl libhttp-message-perl libhttp-negotiate-perl libindicator3-7 libio-html-perl
  libio-socket-ssl-perl libio-stringy-perl libipc-system-simple-perl libjson-glib-1.0-0 libjson-glib-1.0-common liblwp-mediatypes-perl liblwp-protocol-https-perl
  libmailtools-perl libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl libnotify4 libnspr4 libnss3 libproxy1v5 librest-0.7-0 librsvg2-common
  libsecret-1-0 libsecret-common libsoup-gnome2.4-1 libsoup2.4-1 libtie-ixhash-perl libtimedate-perl libtry-tiny-perl liburi-perl libwww-perl libwww-robotrules-perl
  libx11-protocol-perl libxaw7 libxcomposite1 libxft2 libxml-parser-perl libxml-twig-perl libxml-xpathengine-perl libxmu6 libxpm4 libxt6 libxxf86dga1
  notification-daemon perl-openssl-defaults x11-utils x11-xserver-utils xdg-utils
0 upgraded, 95 newly installed, 0 to remove and 30 not upgraded.
Need to get 25.4 MB of archives.
After this operation, 88.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf libgnome-keyring-common all 3.12.0-1 [59.5 kB]
Get:2 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libxxf86dga1 armhf 2:1.1.4-1 [22.4 kB]
Get:4 http://archive.raspberrypi.org/debian buster/main armhf libgnome-keyring0 armhf 3.12.0-1+b1 [79.9 kB]
Get:3 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf librsvg2-common armhf 2.44.10-2.1+rpi1 [23.1 kB]
Get:5 http://archive.raspberrypi.org/debian buster/main armhf gtk-update-icon-cache armhf 3.24.5-1+rpt2 [80.5 kB]
Get:6 http://archive.raspberrypi.org/debian buster/main armhf gir1.2-gnomekeyring-1.0 armhf 3.12.0-1+b1 [40.4 kB]
Get:7 http://archive.raspberrypi.org/debian buster/main armhf libcairo-gobject2 armhf 1.16.0-4+rpt1 [123 kB]
Get:9 http://archive.raspberrypi.org/debian buster/main armhf libgtk-3-common all 3.24.5-1+rpt2 [3,680 kB]
Get:8 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf adwaita-icon-theme all 3.30.1-1 [11.7 MB]
Get:10 http://mirror.datamossa.io/raspbian buster/main armhf libatspi2.0-0 armhf 2.30.0-7 [54.3 kB]
Get:11 http://archive.raspberrypi.org/debian buster/main armhf libgtk-3-0 armhf 3.24.5-1+rpt2 [2,136 kB]
Get:12 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf at-spi2-core armhf 2.30.0-7 [64.6 kB]
Get:13 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf dbus-user-session armhf 1.12.16-1 [93.4 kB]
Get:14 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libdconf1 armhf 0.30.1-2 [36.3 kB]
Get:15 http://archive.raspberrypi.org/debian buster/main armhf libgtk-3-bin armhf 3.24.5-1+rpt2 [111 kB]
Get:16 http://archive.raspberrypi.org/debian buster/main armhf xdg-utils all 1.1.3-1+rpt1 [73.4 kB]
Get:17 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf dconf-service armhf 0.30.1-2 [33.3 kB]
Get:18 http://raspbian.mirror.digitalpacific.com.au/raspbian buster/main armhf dconf-gsettings-backend armhf 0.30.1-2 [24.7 kB]
Get:19 http://mirror.datamossa.io/raspbian buster/main armhf libgirepository-1.0-1 armhf 1.58.3-2 [78.8 kB]
Get:20 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf gir1.2-glib-2.0 armhf 1.58.3-2 [143 kB]
Get:21 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libproxy1v5 armhf 0.4.15-5 [49.8 kB]
Get:22 http://mirror.datamossa.io/raspbian buster/main armhf glib-networking-common all 2.58.0-2 [59.3 kB]
Get:23 http://mirror.datamossa.io/raspbian buster/main armhf glib-networking-services armhf 2.58.0-2 [13.0 kB]
Get:24 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf gsettings-desktop-schemas all 3.28.1-1 [529 kB]
Get:25 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf glib-networking armhf 2.58.0-2 [47.7 kB]
Get:26 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libatk1.0-data all 2.30.0-2 [145 kB]
Get:27 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libatk1.0-0 armhf 2.30.0-2 [42.7 kB]
Get:28 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libdbusmenu-glib4 armhf 18.10.20180917~bzr490+repack1-1 [50.6 kB]
Get:29 http://raspbian.mirror.digitalpacific.com.au/raspbian buster/main armhf libdbusmenu-gtk3-4 armhf 18.10.20180917~bzr490+repack1-1 [39.8 kB]
Get:30 http://raspbian.mirror.digitalpacific.com.au/raspbian buster/main armhf libatk-bridge2.0-0 armhf 2.30.0-5 [51.1 kB]
Get:31 http://mirror.datamossa.io/raspbian buster/main armhf libcolord2 armhf 1.4.3-4 [119 kB]
Err:32 http://raspbian.raspberrypi.org/raspbian buster/main armhf libcups2 armhf 2.2.10-6+deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Get:33 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libepoxy0 armhf 1.5.3-0.1 [167 kB]
Get:34 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libjson-glib-1.0-common all 1.4.4-2 [52.3 kB]
Get:35 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libjson-glib-1.0-0 armhf 1.4.4-2 [52.7 kB]
Get:36 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libsoup2.4-1 armhf 2.64.2-2 [216 kB]
Get:37 http://mirror.datamossa.io/raspbian buster/main armhf libsoup-gnome2.4-1 armhf 2.64.2-2 [17.5 kB]
Get:38 http://mirror.datamossa.io/raspbian buster/main armhf librest-0.7-0 armhf 0.8.1-1 [27.8 kB]
Get:39 http://mirror.datamossa.io/raspbian buster/main armhf libxcomposite1 armhf 1:0.4.4-2 [16.1 kB]
Get:40 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libindicator3-7 armhf 0.5.0-4 [49.8 kB]
Get:41 http://mirror.datamossa.io/raspbian buster/main armhf libappindicator3-1 armhf 0.4.92-7 [50.8 kB]
Get:42 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libauthen-sasl-perl all 2.1600-1 [50.8 kB]
Get:43 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libdata-dump-perl all 1.23-1 [29.5 kB]
Get:44 http://mirror.datamossa.io/raspbian buster/main armhf libencode-locale-perl all 1.05-1 [13.7 kB]
Get:45 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libipc-system-simple-perl all 1.25-4 [26.5 kB]
Get:46 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libfile-basedir-perl all 0.08-1 [17.7 kB]
Get:47 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf liburi-perl all 1.76-1 [89.9 kB]
Get:48 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libfile-desktopentry-perl all 0.22-1 [19.2 kB]
Get:49 http://mirror.datamossa.io/raspbian buster/main armhf libtimedate-perl all 2.3000-2 [42.2 kB]
Get:50 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libhttp-date-perl all 6.02-1 [10.7 kB]
Get:51 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libfile-listing-perl all 6.04-1 [10.3 kB]
Get:52 http://mirror.datamossa.io/raspbian buster/main armhf libfile-mimeinfo-perl all 0.29-1 [46.5 kB]
Get:53 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libfont-afm-perl all 1.20-2 [13.6 kB]
Get:54 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libfontenc1 armhf 1:1.1.3-1 [22.2 kB]
Get:55 http://mirror.datamossa.io/raspbian buster/main armhf libhtml-tagset-perl all 3.20-3 [12.7 kB]
Get:56 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libhtml-parser-perl armhf 3.72-3+b2 [101 kB]
Get:57 http://mirror.datamossa.io/raspbian buster/main armhf libio-html-perl all 1.001-1 [17.6 kB]
Get:58 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf liblwp-mediatypes-perl all 6.02-1 [22.1 kB]
Get:59 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libhttp-message-perl all 6.18-1 [77.8 kB]
Get:60 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libhtml-form-perl all 6.03-1 [23.9 kB]
Get:61 http://mirror.datamossa.io/raspbian buster/main armhf libhtml-tree-perl all 5.07-2 [213 kB]
Get:62 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libhtml-format-perl all 2.12-1 [43.5 kB]
Get:63 http://mirror.datamossa.io/raspbian buster/main armhf libhttp-cookies-perl all 6.04-1 [17.8 kB]
Get:64 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libhttp-daemon-perl all 6.01-3 [16.6 kB]
Get:65 http://mirror.datamossa.io/raspbian buster/main armhf libhttp-negotiate-perl all 6.01-1 [12.8 kB]
Get:66 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf perl-openssl-defaults armhf 3 [6,782 B]
Get:67 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libnet-ssleay-perl armhf 1.85-2+b1 [286 kB]
Get:68 http://mirror.datamossa.io/raspbian buster/main armhf libio-socket-ssl-perl all 2.060-3 [207 kB]
Get:69 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libio-stringy-perl all 2.111-3 [56.5 kB]
Get:70 http://mirror.datamossa.io/raspbian buster/main armhf libnet-http-perl all 6.18-1 [24.5 kB]
Get:71 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libtry-tiny-perl all 0.30-1 [23.3 kB]
Get:72 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libwww-robotrules-perl all 6.02-1 [12.9 kB]
Get:73 http://mirror.datamossa.io/raspbian buster/main armhf libwww-perl all 6.36-2 [188 kB]
Get:74 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf liblwp-protocol-https-perl all 6.07-2 [9,242 B]
Get:75 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libnet-smtp-ssl-perl all 1.04-1 [6,184 B]
Get:76 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libmailtools-perl all 2.18-1 [88.5 kB]
Get:77 http://mirror.datamossa.io/raspbian buster/main armhf libxml-parser-perl armhf 2.44-4 [209 kB]
Get:78 http://raspbian.mirror.digitalpacific.com.au/raspbian buster/main armhf libxml-twig-perl all 1:3.50-1.1 [179 kB]
Get:79 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libnet-dbus-perl armhf 1.1.0-5+b1 [176 kB]
Get:80 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libnotify4 armhf 0.7.7-4 [27.2 kB]
Get:81 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libnspr4 armhf 2:4.20-1 [89.6 kB]
Err:82 http://raspbian.raspberrypi.org/raspbian buster/main armhf libnss3 armhf 2:3.42.1-1+deb10u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Get:83 http://mirror.datamossa.io/raspbian buster/main armhf libsecret-common all 0.18.7-1 [25.7 kB]
Get:84 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libsecret-1-0 armhf 0.18.7-1 [82.1 kB]
Get:85 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libtie-ixhash-perl all 1.23-2 [11.7 kB]
Get:86 http://mirror.datamossa.io/raspbian buster/main armhf libx11-protocol-perl all 0.56-7 [150 kB]
Get:87 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libxt6 armhf 1:1.1.5-1+b3 [156 kB]
Get:88 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libxmu6 armhf 2:1.1.2-2+b3 [52.1 kB]
Get:89 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libxpm4 armhf 1:3.5.12-1 [43.6 kB]
Get:90 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libxaw7 armhf 2:1.0.13-1+b2 [163 kB]
Get:91 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf libxft2 armhf 2.3.2-2 [49.3 kB]
Get:92 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libxml-xpathengine-perl all 0.14-1 [33.3 kB]
Get:93 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf notification-daemon armhf 3.20.0-4 [56.3 kB]
Get:94 http://raspbian.mirror.digitalpacific.com.au/raspbian buster/main armhf x11-utils armhf 7.7+4 [176 kB]
Get:95 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf x11-xserver-utils armhf 7.7+8 [150 kB]
Fetched 24.2 MB in 1min 5s (374 kB/s)
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/c/cups/libcups2_2.2.10-6+deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/n/nss/libnss3_3.42.1-1+deb10u1_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by UnchartedBull** [comment]
Could you please provide further information on your system, especially Distribution and version. I can then have a look why the packages aren't available in your repository.

@fwdixon What do you mean by hung up? Some parts of the script take a good 5 minutes on slower machines. And yeah the instructions are already updated for v2.0 which hopefully will come soon.

@stevo1957 The packages should be available. There are listed normally for buster: https://packages.debian.org/buster/libnss3. Did you try running `sudo apt update`? I've also heard of some problems with that repo, so maybe just try again :)

**Comment by NightSkySK** [comment]
In my bash installations logs are as follows:
```bash <(wget -qO- https://github.com/UnchartedBull/OctoDash/raw/master/scripts/install.sh)
Installing OctoDash v1.5.0
Installing Dependencies ...
All packages are up to date.
Package gir1.2-gnomekeyring-1.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gir1.2-gnomekeyring-1.0' has no installation candidate```

**Comment by stevo1957** [comment]
Thanks for your help with this.

I am running an Acer laptop with Windows 10 and have previously had Octodash installed and running perfectly with a cheap 3.5" touchscreen.

I was doing a fresh install with a new Raspberry 7" touchscreen last night when I was receiving the errors.

I tried the auto install script again tonight and everything went smoothly.

I didn't do anything differently tonight except start with a fresh install of Octopi from an image backup I had, so can't explain why it worked fine tonight, but I had issues yesterday.

Thanks again for a great bit of software and for your technical support.

**Comment by UnchartedBull** [comment]
I guess this was due to an error with one of your mirrors, which got fixed in between the two installations.

@NightSkySK Could you try installing again? Maybe you encountered a similar issue

**Comment by pciavald** [comment]
I'm getting the same issue on plain fresh debian 10 currently (manual install) : 
```
E: Package 'gir1.2-gnomekeyring-1.0' has no installation candidate
```
