### ISSUE TITLE
Fan Speed Control

### ISSUE THREAD

**Issue by GrubbyZebra** [UnchartedBull/OctoDash#841]
**Is your feature request related to a problem? Please describe.**
When pressing the "fan" icon during print, the "adjustment" option does not include a fan speed adjustment.

**Describe the solution you'd like**
Since you can adjust temps already by pressing the extruder and bed icons during printing, perhaps replace those settings on the "adjustment" screen with a fan speed adjustment.

**Comment by whoim2** [comment]
Sorry, bad speak english. Need update for fan speed?
