### ISSUE TITLE
Black screen after running updates on Pi 4

### ISSUE THREAD

**Issue by morphias2004** [UnchartedBull/OctoDash#848]
**What doesn't work?**
Pi 4 with Pimoroni HyperPixel 4.0 Touch

Ran Octodash installation on OctoPrint 1.4.0 with OctoPi 0.17.0

Installed without errors and the OctoDash first run wizard ran fine.

Ran Pi APT update as I hadn't run it in a month and it loaded 153 updates.

On reboot, OctoDash no longer appears to launch. I briefly see the Pi boot on the screen, but then the screen goes black.

OctoPi is fine.

**What did you already try?**
Reinstalled latest driver from Pimoroni

Uninstalled OctoDash
Deleted .config/octodash 
Rebooted
Reinstalled OctoDash
Issue is the same and I don't even get to see the first run wizard now.
I note the config.json file does not get created.

Downloaded the sample config.json, edited it, renamed it and copied it into .config/octodash
No Change

Deleted the config.json I had copied over.

Ran sudo chmod ug+s /usr/lib/xorg/Xorg and rebooted
No Change

Double checked B2 is set in raspi-config and rebooted
No Change

Ran sudo dpkg-reconfigure x11-common and rebooted
No Change

Ran sudo apt install libpam0g-dev libx11-dev and rebooted
No Change

Uninstalled OctoDash again
Deleted .config/octodash again
Rebooted
Reinstalled OctoDash
No Change and no first run wizard

I don't have a mini HDMi to HDMi adapter to test output to an external monitor, but I do see the startup of the Pi before the screen goes black, so the screen and drivers work.

OctoDash was working prior to running the updates.

**General Information:**
Pi 4 4GB
32GB Samsung Evo Class 10 micro SD card
Latest OctoPi image from octoprint.org with OctoPrint 1.4.0 and OctoPi 0.17.0
OctoDash 1.5.0

**Additional context**
I suspect one of the plethora of updates that were loaded has broken OctoDash, but I have no idea which one.

**Comment by morphias2004** [comment]
I've just done a fresh install of the Octoprint/OctoPi image, installed the Pimoroni HyperPixel drivers and installed OctoDash. Everything works correctly.

I'll now try a **sudo apt update** again and see if that breaks it again.

**Comment by morphias2004** [comment]
The updates have broken it again.

Here is the list of updates:

pi@octopi:~ $ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libllvm8 rpi-eeprom-images
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  busybox initramfs-tools initramfs-tools-core klibc-utils libfl2 libklibc libllvm9 linux-base pigz rpi.gpio-common
The following packages will be upgraded:
  apt apt-utils base-files bind9-host binutils binutils-arm-linux-gnueabihf binutils-common bluez bluez-firmware ca-certificates cron curl dhcpcd5
  distro-info-data dphys-swapfile e2fsprogs ffmpeg file firmware-atheros firmware-brcm80211 firmware-libertas firmware-misc-nonfree firmware-realtek
  freetype2-doc fuse git git-man imagemagick imagemagick-6-common imagemagick-6.q16 iputils-ping libapt-inst2.0 libapt-pkg5.0 libarchive13 libavcodec58
  libavdevice58 libavfilter7 libavformat58 libavresample4 libavutil56 libbind9-161 libbinutils libcom-err2 libcurl3-gnutls libcurl4 libdns-export1104
  libdns1104 libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libext2fs2 libfreetype6 libfreetype6-dev libfribidi0 libfuse2 libgl1-mesa-dri
  libglib2.0-0 libglib2.0-data libgnutls30 libicu63 libidn2-0 libisc-export1100 libisc1100 libisccc161 libisccfg163 libldap-2.4-2 libldap-common liblwres161
  libmagic-mgc libmagic1 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmysofa0 libncurses6 libncursesw5 libncursesw6 libopenjp2-7 libopenmpt0
  libpam-chksshpwd libpam-modules libpam-modules-bin libpam-runtime libpam-systemd libpam0g libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpostproc55
  libpython2.7 libpython2.7-dev libpython2.7-minimal libpython2.7-stdlib libpython3.7 libpython3.7-minimal libpython3.7-stdlib libraspberrypi-bin
  libraspberrypi-dev libraspberrypi-doc libraspberrypi0 libsasl2-2 libsasl2-modules-db libss2 libssh-gcrypt-4 libssl-dev libssl1.1 libswresample3 libswscale5
  libsystemd0 libtiff5 libtinfo5 libtinfo6 libudev1 libvpx5 libxml2 libxmuu1 ncurses-base ncurses-bin ncurses-term openssh-client openssh-server
  openssh-sftp-server openssl pi-bluetooth python-apt-common python-rpi.gpio python2.7 python2.7-dev python2.7-minimal python3-apt python3.7 python3.7-minimal
  raspberrypi-bootloader raspberrypi-kernel raspberrypi-sys-mods raspi-config rpcbind rpi-eeprom rpi-eeprom-images rpi-update ssh sudo systemd systemd-sysv
  tzdata udev wpasupplicant
148 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 258 MB of archives.
After this operation, 116 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf libpam0g armhf 1.3.1-5+rpt2 [121 kB]
Get:4 http://archive.raspberrypi.org/debian buster/main armhf libpam-modules-bin armhf 1.3.1-5+rpt2 [103 kB]
Get:5 http://archive.raspberrypi.org/debian buster/main armhf libpam-modules armhf 1.3.1-5+rpt2 [290 kB]
Get:6 http://archive.raspberrypi.org/debian buster/main armhf libpam-runtime all 1.3.1-5+rpt2 [211 kB]
Get:8 http://archive.raspberrypi.org/debian buster/main armhf bluez armhf 5.50-1.2~deb10u1+rpt1 [765 kB]
Get:10 http://archive.raspberrypi.org/debian buster/main armhf libssl-dev armhf 1.1.1d-0+deb10u3+rpt1 [1,583 kB]
Get:2 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf base-files armhf 10.3+rpi1+deb10u4 [70.0 kB]
Get:3 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf ncurses-bin armhf 6.1+20181013-2+deb10u2 [400 kB]
Get:7 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf ncurses-base all 6.1+20181013-2+deb10u2 [258 kB]
Get:9 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf systemd-sysv armhf 241-7~deb10u4+rpi1 [100 kB]
Get:11 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libpam-systemd armhf 241-7~deb10u4+rpi1 [194 kB]
Get:12 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libsystemd0 armhf 241-7~deb10u4+rpi1 [305 kB]
Get:13 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf systemd armhf 241-7~deb10u4+rpi1 [3,255 kB]
Get:14 http://archive.raspberrypi.org/debian buster/main armhf libssl1.1 armhf 1.1.1d-0+deb10u3+rpt1 [1,275 kB]
Get:15 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf udev armhf 241-7~deb10u4+rpi1 [1,248 kB]
Get:16 http://archive.raspberrypi.org/debian buster/main armhf bluez-firmware all 1.2-4+rpt3 [120 kB]
Get:17 http://archive.raspberrypi.org/debian buster/main armhf openssl armhf 1.1.1d-0+deb10u3+rpt1 [807 kB]
Get:18 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libudev1 armhf 241-7~deb10u4+rpi1 [144 kB]
Get:19 http://archive.raspberrypi.org/debian buster/main armhf dhcpcd5 armhf 1:8.1.2-1+rpt1 [146 kB]
Get:21 http://archive.raspberrypi.org/debian buster/main armhf dphys-swapfile all 20100506-5+rpt1 [21.4 kB]
Get:22 http://archive.raspberrypi.org/debian buster/main armhf ffmpeg armhf 7:4.1.6-1~deb10u1+rpt1 [1,432 kB]
Get:20 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libglib2.0-0 armhf 2.58.3-2+deb10u2 [1,078 kB]
Get:23 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libidn2-0 armhf 2.0.5-1+deb10u1 [74.0 kB]
Get:24 http://archive.raspberrypi.org/debian buster/main armhf libavdevice58 armhf 7:4.1.6-1~deb10u1+rpt1 [147 kB]
Get:25 http://archive.raspberrypi.org/debian buster/main armhf libavfilter7 armhf 7:4.1.6-1~deb10u1+rpt1 [1,450 kB]
Get:26 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libgnutls30 armhf 3.6.7-4+deb10u4 [1,047 kB]
Get:27 http://archive.raspberrypi.org/debian buster/main armhf libswscale5 armhf 7:4.1.6-1~deb10u1+rpt1 [253 kB]
Get:28 http://archive.raspberrypi.org/debian buster/main armhf libavformat58 armhf 7:4.1.6-1~deb10u1+rpt1 [1,516 kB]
Get:31 http://archive.raspberrypi.org/debian buster/main armhf libavcodec58 armhf 7:4.1.6-1~deb10u1+rpt1 [8,904 kB]
Get:29 http://mirror.datamossa.io/raspbian buster/main armhf libapt-pkg5.0 armhf 1.8.2.1 [855 kB]
Get:30 http://mirror.datamossa.io/raspbian buster/main armhf libapt-inst2.0 armhf 1.8.2.1 [199 kB]
Get:32 http://mirror.datamossa.io/raspbian buster/main armhf apt armhf 1.8.2.1 [1,349 kB]
Get:33 http://mirror.datamossa.io/raspbian buster/main armhf apt-utils armhf 1.8.2.1 [399 kB]
Get:34 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libext2fs2 armhf 1.44.5-1+deb10u3 [202 kB]
Get:35 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf e2fsprogs armhf 1.44.5-1+deb10u3 [532 kB]
Get:36 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf cron armhf 3.0pl1-134+deb10u1 [94.0 kB]
Get:38 http://archive.raspberrypi.org/debian buster/main armhf libswresample3 armhf 7:4.1.6-1~deb10u1+rpt1 [118 kB]
Get:39 http://archive.raspberrypi.org/debian buster/main armhf libpostproc55 armhf 7:4.1.6-1~deb10u1+rpt1 [95.1 kB]
Get:40 http://archive.raspberrypi.org/debian buster/main armhf libavresample4 armhf 7:4.1.6-1~deb10u1+rpt1 [104 kB]
Get:37 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf freetype2-doc all 2.9.1-3+deb10u1 [2,309 kB]
Get:41 http://archive.raspberrypi.org/debian buster/main armhf libdrm-common all 2.4.100-4+rpi1~bpo10+1 [14.4 kB]
Get:42 http://archive.raspberrypi.org/debian buster/main armhf libdrm2 armhf 2.4.100-4+rpi1~bpo10+1 [36.6 kB]
Get:43 http://archive.raspberrypi.org/debian buster/main armhf libavutil56 armhf 7:4.1.6-1~deb10u1+rpt1 [354 kB]
Get:44 http://archive.raspberrypi.org/debian buster/main armhf libraspberrypi-bin armhf 1.20200723-1 [340 kB]
Get:45 http://archive.raspberrypi.org/debian buster/main armhf libraspberrypi-doc armhf 1.20200723-1 [31.4 MB]
Get:46 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libfreetype6-dev armhf 2.9.1-3+deb10u1 [479 kB]
Get:47 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libfreetype6 armhf 2.9.1-3+deb10u1 [317 kB]
Get:48 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libopenjp2-7 armhf 2.3.0-2+deb10u1 [138 kB]
Get:49 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libtiff5 armhf 4.1.0+git191117-2~deb10u1 [249 kB]
Get:50 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libicu63 armhf 63.1-6+deb10u1 [7,973 kB]
Get:51 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libxml2 armhf 2.9.4+dfsg1-7+b3 [571 kB]
Get:52 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf imagemagick-6-common all 8:6.9.10.23+dfsg-2.1+deb10u1 [200 kB]
Get:53 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmagickcore-6.q16-6 armhf 8:6.9.10.23+dfsg-2.1+deb10u1 [1,600 kB]
Get:55 http://mirror.datamossa.io/raspbian buster/main armhf pigz armhf 2.4-1 [47.2 kB]
Get:54 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmagickwand-6.q16-6 armhf 8:6.9.10.23+dfsg-2.1+deb10u1 [419 kB]
Get:56 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python2.7-dev armhf 2.7.16-2+deb10u1 [291 kB]
Get:57 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython2.7-dev armhf 2.7.16-2+deb10u1 [30.9 MB]
Get:65 http://archive.raspberrypi.org/debian buster/main armhf libraspberrypi-dev armhf 1.20200723-1 [412 kB]
Get:66 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel armhf 1.20200723-1 [73.0 MB]
Get:84 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf ssh all 1:7.9p1-10+deb10u2 [202 kB]
Get:58 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython2.7 armhf 2.7.16-2+deb10u1 [873 kB]
Get:59 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python2.7 armhf 2.7.16-2+deb10u1 [305 kB]
Get:102 http://mirror.datamossa.io/raspbian buster/main armhf libfl2 armhf 2.6.4-6.2 [103 kB]
Get:60 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython2.7-stdlib armhf 2.7.16-2+deb10u1 [1,844 kB]
Get:61 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python2.7-minimal armhf 2.7.16-2+deb10u1 [1,091 kB]
Get:103 http://mirror.datamossa.io/raspbian buster/main armhf busybox armhf 1:1.30.1-4 [405 kB]
Get:62 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython2.7-minimal armhf 2.7.16-2+deb10u1 [395 kB]
Get:63 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libncurses6 armhf 6.1+20181013-2+deb10u2 [78.9 kB]
Get:64 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libtinfo6 armhf 6.1+20181013-2+deb10u2 [312 kB]
Get:67 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libncursesw6 armhf 6.1+20181013-2+deb10u2 [103 kB]
Get:68 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python3.7 armhf 3.7.3-2+deb10u1 [330 kB]
Get:69 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython3.7 armhf 3.7.3-2+deb10u1 [1,252 kB]
Get:104 http://mirror.datamossa.io/raspbian buster/main armhf ca-certificates all 20200601~deb10u1 [158 kB]
Get:70 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython3.7-stdlib armhf 3.7.3-2+deb10u1 [1,662 kB]
Get:71 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python3.7-minimal armhf 3.7.3-2+deb10u1 [1,463 kB]
Get:72 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython3.7-minimal armhf 3.7.3-2+deb10u1 [583 kB]
Get:73 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf openssh-sftp-server armhf 1:7.9p1-10+deb10u2 [35.9 kB]
Get:74 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libcom-err2 armhf 1.44.5-1+deb10u3 [67.6 kB]
Get:75 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf openssh-server armhf 1:7.9p1-10+deb10u2 [291 kB]
Get:76 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf git-man all 1:2.20.1-2+deb10u3 [1,620 kB]
Get:77 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libsasl2-modules-db armhf 2.1.27+dfsg-1+deb10u1 [67.5 kB]
Get:78 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libsasl2-2 armhf 2.1.27+dfsg-1+deb10u1 [98.8 kB]
Get:79 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libldap-common all 2.4.47+dfsg-3+rpi1+deb10u2 [89.8 kB]
Get:80 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libldap-2.4-2 armhf 2.4.47+dfsg-3+rpi1+deb10u2 [198 kB]
Get:81 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libcurl3-gnutls armhf 7.64.0-4+deb10u1 [292 kB]
Get:82 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf git armhf 1:2.20.1-2+deb10u3 [4,194 kB]
Get:83 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf openssh-client armhf 1:7.9p1-10+deb10u2 [670 kB]
Get:85 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf tzdata all 2020a-0+deb10u1 [263 kB]
Get:86 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf iputils-ping armhf 3:20180629-2+deb10u1 [40.2 kB]
Get:87 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf bind9-host armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [268 kB]
Get:88 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libbind9-161 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [243 kB]
Get:89 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libisccfg163 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [258 kB]
Get:90 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libisccc161 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [234 kB]
Get:91 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libdns1104 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [1,078 kB]
Get:92 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libisc1100 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [422 kB]
Get:93 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf liblwres161 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [246 kB]
Get:94 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf file armhf 1:5.35-4+deb10u1 [65.4 kB]
Get:95 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmagic1 armhf 1:5.35-4+deb10u1 [110 kB]
Get:96 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmagic-mgc armhf 1:5.35-4+deb10u1 [242 kB]
Get:97 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf ncurses-term all 6.1+20181013-2+deb10u2 [490 kB]
Get:98 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf binutils-arm-linux-gnueabihf armhf 2.31.1-16+rpi2 [1,814 kB]
Get:112 http://archive.raspberrypi.org/debian buster/main armhf libraspberrypi0 armhf 1.20200723-1 [850 kB]
Get:99 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libbinutils armhf 2.31.1-16+rpi2 [302 kB]
Get:100 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf binutils armhf 2.31.1-16+rpi2 [57.0 kB]
Get:101 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf binutils-common armhf 2.31.1-16+rpi2 [2,075 kB]
Get:114 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-bootloader armhf 1.20200723-1 [4,505 kB]
Get:105 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf curl armhf 7.64.0-4+deb10u1 [254 kB]
Get:106 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libcurl4 armhf 7.64.0-4+deb10u1 [294 kB]
Get:107 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf distro-info-data all 0.41+deb10u2 [6,584 B]
Get:108 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libfribidi0 armhf 1.0.5-3.1+deb10u1 [62.3 kB]
Get:109 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmysofa0 armhf 0.6~dfsg0-3+deb10u1 [34.2 kB]
Get:110 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libopenmpt0 armhf 0.4.3-1+deb10u1 [535 kB]
Get:111 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libssh-gcrypt-4 armhf 0.8.7-1+deb10u1 [171 kB]
Get:113 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libvpx5 armhf 1.7.0-3+deb10u1 [449 kB]
Get:115 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf fuse armhf 2.9.9-1+deb10u1 [69.2 kB]
Get:116 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libfuse2 armhf 2.9.9-1+deb10u1 [116 kB]
Get:117 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf imagemagick-6.q16 armhf 8:6.9.10.23+dfsg-2.1+deb10u1 [580 kB]
Get:118 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf imagemagick armhf 8:6.9.10.23+dfsg-2.1+deb10u1 [156 kB]
Get:119 http://archive.raspberrypi.org/debian buster/main armhf firmware-atheros all 1:20190114-1+rpt7 [3,887 kB]
Get:120 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libklibc armhf 2.0.6-1+rpi1 [52.5 kB]
Get:121 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf klibc-utils armhf 2.0.6-1+rpi1 [87.1 kB]
Get:122 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf initramfs-tools-core all 0.133+deb10u1 [99.2 kB]
Get:123 http://archive.raspberrypi.org/debian buster/main armhf firmware-brcm80211 all 1:20190114-1+rpt7 [4,457 kB]
Get:124 http://mirror.datamossa.io/raspbian buster/main armhf linux-base all 4.6 [32.4 kB]
Get:125 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf initramfs-tools all 0.133+deb10u1 [69.7 kB]
Get:126 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libarchive13 armhf 3.3.3-4+deb10u1 [271 kB]
Get:127 http://archive.raspberrypi.org/debian buster/main armhf firmware-libertas all 1:20190114-1+rpt7 [3,423 kB]
Get:128 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libisc-export1100 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [360 kB]
Get:129 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libdns-export1104 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [871 kB]
Get:130 http://archive.raspberrypi.org/debian buster/main armhf firmware-misc-nonfree all 1:20190114-1+rpt7 [3,070 kB]
Get:131 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libglib2.0-data all 2.58.3-2+deb10u2 [1,110 kB]
Get:133 http://archive.raspberrypi.org/debian buster/main armhf firmware-realtek all 1:20190114-1+rpt7 [495 kB]
Get:134 http://archive.raspberrypi.org/debian buster/main armhf libdrm-amdgpu1 armhf 2.4.100-4+rpi1~bpo10+1 [26.9 kB]
Get:135 http://archive.raspberrypi.org/debian buster/main armhf libdrm-nouveau2 armhf 2.4.100-4+rpi1~bpo10+1 [24.8 kB]
Get:136 http://archive.raspberrypi.org/debian buster/main armhf libdrm-radeon1 armhf 2.4.100-4+rpi1~bpo10+1 [29.0 kB]
Get:137 http://archive.raspberrypi.org/debian buster/main armhf libllvm9 armhf 1:9.0.1-6+rpi1~bpo10+1 [13.1 MB]
Get:132 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libncursesw5 armhf 6.1+20181013-2+deb10u2 [94.3 kB]
Get:138 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libtinfo5 armhf 6.1+20181013-2+deb10u2 [309 kB]
Get:139 http://mirror.datamossa.io/raspbian buster/main armhf libpango-1.0-0 armhf 1.42.4-8~deb10u1 [169 kB]
Get:140 http://mirror.datamossa.io/raspbian buster/main armhf libpangoft2-1.0-0 armhf 1.42.4-8~deb10u1 [62.3 kB]
Get:141 http://mirror.datamossa.io/raspbian buster/main armhf libpangocairo-1.0-0 armhf 1.42.4-8~deb10u1 [52.0 kB]
Get:142 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libss2 armhf 1.44.5-1+deb10u3 [71.0 kB]
Get:143 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libxmuu1 armhf 2:1.1.2-2+b3 [23.4 kB]
Get:144 http://archive.raspberrypi.org/debian buster/main armhf libgl1-mesa-dri armhf 19.3.2-1~bpo10+1~rpt1 [5,550 kB]
Get:145 http://mirror.datamossa.io/raspbian buster/main armhf python-apt-common all 1.8.4.1 [95.7 kB]
Get:146 http://mirror.datamossa.io/raspbian buster/main armhf python3-apt armhf 1.8.4.1 [167 kB]
Get:147 http://archive.raspberrypi.org/debian buster/main armhf libpam-chksshpwd armhf 1.3.1-5+rpt2 [81.7 kB]
Get:148 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-sys-mods armhf 20200514 [10.6 kB]
Get:149 http://archive.raspberrypi.org/debian buster/main armhf pi-bluetooth all 0.1.13 [4,908 B]
Get:150 http://archive.raspberrypi.org/debian buster/main armhf rpi.gpio-common armhf 0.7.0-0.1~bpo10+1 [5,776 B]
Get:151 http://archive.raspberrypi.org/debian buster/main armhf python-rpi.gpio armhf 0.7.0-0.1~bpo10+1 [20.8 kB]
Get:152 http://archive.raspberrypi.org/debian buster/main armhf raspi-config all 20200707 [26.4 kB]
Get:153 http://archive.raspberrypi.org/debian buster/main armhf rpi-eeprom-images all 7.8-1 [6,112 B]
Get:154 http://archive.raspberrypi.org/debian buster/main armhf rpi-eeprom all 7.8-1 [316 kB]
Get:155 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf rpcbind armhf 1.2.5-0.3+deb10u1 [41.2 kB]
Get:156 http://archive.raspberrypi.org/debian buster/main armhf rpi-update all 20200409 [7,488 B]
Get:157 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf sudo armhf 1.8.27-1+deb10u2 [1,201 kB]
Get:158 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf wpasupplicant armhf 2:2.7+git20190128+0c1e29f-6+deb10u2 [1,008 kB]
Fetched 258 MB in 2min 11s (1,968 kB/s)

**Comment by morphias2004** [comment]
I have done another fresh install of OctoPrint/OctoPi and only loaded the HyperPixel 4 drivers. I then went straight to doing the update and full-upgrade and the issue has reoccurred.

On the up side, this conclusively rules out any fault with OctoDash.

This matter can be closed and I will open a support case on the Pimoroni HyperPixel 4 GitHub page.

https://github.com/pimoroni/hyperpixel4/issues

**Comment by morphias2004** [comment]
Case opened on Pimoroni HyperPixel 4 GitHub page:

https://github.com/pimoroni/hyperpixel4/issues/88

**Comment by UnchartedBull** [comment]
Thanks for the info! 👍
