### ISSUE TITLE
Design an App Icon

### ISSUE THREAD

**Issue by UnchartedBull** [UnchartedBull/OctoDash#85]
General Guidelines:
- should be a png with transparent background
- 512x512px
- I would like it to reflect the connection to OctoPrint but also look modern, but I'm open for anything.
- ColorPalette used for OctoDash is this one: https://flatuicolors.com/palette/gb so probably a good point to start
- It should look modern and follow the general design of OctoDash

**Comment by hessius** [comment]
I saw that someone was helping out with this on reddit, but if that's stalled it would be good to get some specifications (sizes, format) and if there are any guidelines (palette, general ideas etc)

**Comment by UnchartedBull** [comment]
Yes it went silent, unfortunately. I may ask that guy for an update but I don't want to push anyone. I added some information to the issue.

@hessius thanks for all your feedback and suggestions so far. If you would like to become a contributer and help me out in some places let me know. I'll be happy to add you.

**Comment by hessius** [comment]
Unfortunately I'm not familiar with angular, so I think "onboarding" me wouldn't be worth the hassle.

I really like the work you've done, so I'm happy to help - Don't worry though, I'm out of ideas now and won't keep submitting issues at this pace ;) 

I do have an idea for an icon though and will se if I can get it to an okay state :)

**Comment by hessius** [comment]
So here's my take, I wanted something simple that could also be incorporated into the ui if needed / wanted, I'm a fan using single coloured logos as they can be reproduced on any background with any background and colour scheme.

So here, presented in white on the OctoDash background colour is simply a combination of a dashboard and an octopus - OctoDash!


![octodash-icon](https://user-images.githubusercontent.com/1499030/66839189-54ce0000-ef66-11e9-8b56-c67a9c4c15da.png)


_Note, while I've made minor adjustments, this is made out of icons from the noun project which can be used even commercially but without a paid license (a one time fee of a few dollars) require attribution (shouldn't be a problem but wanted to mention it)_

**Comment by UnchartedBull** [comment]
That icon does look quite cool. Would you mind adding some colors (like the green tone from the OctoPrint logo)? I've tried to sprinkle color into OctoDash where it was possible to make it look a little bit friendlier, so maybe a few spots of colors does no harm to the logo.

I also used the noun project for almost all other icons, so don't worry, they will get their mentioning soon (currently only in the icons.txt file)

**Comment by hessius** [comment]
Yeah absolutely, I can get on that tonight. Do you want the same colour everywhere?
I might convert it to an svg and then I could just post a jsfiddle and you experiment with fill colours in css

**Comment by hessius** [comment]
Maybe something along these lines?
![octodash-icon-3](https://user-images.githubusercontent.com/1499030/66864618-da1cd900-ef95-11e9-91b3-cdb15bdb3890.png)

**Comment by UnchartedBull** [comment]
That does look way better IMO. Could you also create a version where the suction cups (the round things on the tentacle) are white?

**Comment by UnchartedBull** [comment]
And maybe the grey part between the tentacle and the circle even on both sides? So right side a little smaller and left side a little bigger,

**Comment by hessius** [comment]
Yeah, now I centered it on the base, I'm gonna try a different tentacle and see how it turns out, the suction cups should be symmetrical imo

**Comment by hessius** [comment]
So with a new tentacle, how about this?

At first I considered making the tentacle a solid green, but kept the outline version, looked surprisingly good

![octodash-icon-4](https://user-images.githubusercontent.com/1499030/66868239-44854780-ef9d-11e9-8407-7e08eb386488.png)

**Comment by hessius** [comment]
A minor colour adjustment to use the supplied palette, here with bg and transparent.

Been trying a few different versions with the tentacle filled in, white suction cups and more, everything looked worse than the original though.

![octodash-icon-5-tp](https://user-images.githubusercontent.com/1499030/66954737-47e20700-f061-11e9-8205-123e9874db82.png)
![octodash-icon-5-bg](https://user-images.githubusercontent.com/1499030/66954741-47e20700-f061-11e9-97a8-8f854a155536.png)

**Comment by UnchartedBull** [comment]
Ok I had some time to have a look at the logos and they all do look really good! I like the one with the  asymetrical suction cups a little more than the other one. Also the idea is really neat to replace the needle of the instrument with the tentacle. I stylized that a little further and came up with four super quick mockups (all based on you awesome idea, that I definitely wouldn't be able to come up with!). How do you like them? They are all pretty similar, but I'm on the fence between number 3 and 4.


![66864618-da1cd900-ef95-11e9-91b3-cdb15bdb38902](https://user-images.githubusercontent.com/19818061/66956278-6d244480-f064-11e9-98be-656bae7255f8.png)

![66864618-da1cd900-ef95-11e9-91b3-cdb15bdb3890](https://user-images.githubusercontent.com/19818061/66956409-a2c92d80-f064-11e9-9de9-c069d376d3cd.png)

![66864618-da1cd900-ef95-11e9-91b3-cdb15bdb389023](https://user-images.githubusercontent.com/19818061/66956282-6e557180-f064-11e9-8def-ec0eda1dc68f.png)

![66864618-da1cd900-ef95-11e9-91b3-cdb15bdb3890234](https://user-images.githubusercontent.com/19818061/66956288-70b7cb80-f064-11e9-8668-f6ab45a96925.png)

**Comment by hessius** [comment]
I could probably clean it up for you and convert it to svg. 

Your versions are really a step in the right direction!

I like the simplified meter, and the colouring was nice, although I still prefer the look of the symmetrical suction cups, as they look more like an octopus tentacle and less like some sort of alien limb.

I also like the font, I was thinking of using a way thinner sans serif, circle based font (haven’t tried it yet but it’s available here: http://designbeep.com/2014/05/20/free-font-of-the-day-universum/ ) but especially now with the meter a bit bulkier that font could look out of place

**Comment by UnchartedBull** [comment]
The Font used is actually the font, that OctoPrint uses for the logo as well, which I though is quite a nice touch, but probably not noticeable on a first look.

The problem I have with the symmetrical one is, that it tries to be kind of 3D, which is exactly the opposite of what I tried to do with OctoDash, being as flat as possible. And I also think some breakup of the symmetric concept looks kinda good. I'll look for some more tentacles, but I really like the one you used first. Although I can't find it on thenounproject ...

**Comment by hessius** [comment]
It's a slightly modified version of this: https://thenounproject.com/term/octopus-tentacles/703933/

Maybe the symmetrical can be flattened a bit... I'll try my hand at it just as a test

**Comment by hessius** [comment]
Or a SUPER minimalist icon:
![octodash-icon-10-bg](https://user-images.githubusercontent.com/1499030/67014802-c2f4fd00-f0f5-11e9-9517-15a3e47def0e.png)

**Comment by UnchartedBull** [comment]
I really like the colorful one. I just have one minor idea on how this could be improved:

Maybe make the suction cups a little more circle like and for the top 4 lines to only one suction cup instead of two. This exceeds my SVG capabilities by far, but if you feel confident, that you can do that then OctoDash has a new logo :)

**Comment by UnchartedBull** [comment]
The thickness of the ring could also be touch thinner and follow the tentacle a little better on the right side. Otherwise great design!

**Comment by hessius** [comment]
So I remade the circle to be thinner, remade the base of the tentacle to be the same circumference as the circle. I also remade the suction cups, they're now completely circular (there's something satisfying with the congruence between the shapes). 

Right now I'm editing in photoshop as well but will convert it to SVG once we land on a final design.

I made a regular version and a version with a cutout border on the suction cups (like you did on a previous design which I thought looked neat there but not as good here).

![octodash-icon-11](https://user-images.githubusercontent.com/1499030/67082452-78c55780-f199-11e9-80ae-906c0ed3b1aa.png)
![octodash-icon-11-cutout](https://user-images.githubusercontent.com/1499030/67082453-78c55780-f199-11e9-8ae3-69e0bc387e29.png)

**Comment by hessius** [comment]
Two more iterations (with a more appropriate size for the text as well):
No suction cups
Smaller suction cups
![octodash-icon-13](https://user-images.githubusercontent.com/1499030/67084313-0191c280-f19d-11e9-9fb4-e5b83b1a89fd.png)
![octodash-icon-12](https://user-images.githubusercontent.com/1499030/67084314-0191c280-f19d-11e9-877a-b25c7ec143d9.png)

**Comment by ajanky** [comment]
The version with the smaller suction cups!  👍

**Comment by UnchartedBull** [comment]
Yes the version with the small suction cups does look the best I think. One last thing: Could you try making the top 3 cups just a touch bigger? Otherwise I'm super happy with that design! Thank you so much!

**Comment by hessius** [comment]
Ok, made the top two 10% bigger and the third one 5 % bigger, it started looking too much like the last pair if any bigger than that.

I just realised that I messed some layer styles up with the last one, because I resized it to fit the text which caused the dash to regain some thickness. So I made one version where I kept the thickness and one where it's "the old" thinner version.

So, any more adjustments? Or are we ready to go vector?


![octodash-icon-15](https://user-images.githubusercontent.com/1499030/67093326-a8805980-f1b1-11e9-942b-0b145cc620b7.png)


![octodash-icon-14](https://user-images.githubusercontent.com/1499030/67093324-a7e7c300-f1b1-11e9-9e20-9ca88d1c18a3.png)

**Comment by UnchartedBull** [comment]
I'm still trying to figure out if I like the plain one (without the background around the suction cups) or the other one better. I'll have a closer look later today and respond here again. But we're 99% there :). Sorry I'm kinda picky if it comes to logos ...

**Comment by hessius** [comment]
Well then, to make matters worse, here's a version without background around the suction cups with the round suction cups. And one without the background but with the suction cups in green.
![octodash-icon-16g](https://user-images.githubusercontent.com/1499030/67113451-d5486700-f1d9-11e9-9702-739d6003961f.png)

![octodash-icon-16](https://user-images.githubusercontent.com/1499030/67113403-b9dd5c00-f1d9-11e9-9861-76c0053a0d2a.png)

**Comment by UnchartedBull** [comment]
I still like the one with the tentacle more, the one with only the suction cups kind of reminds of a plant ... I did some tinkering because I really liked the transparent part around the suction cups, but something seemed a little off. I started slowy increasing the width of the border around the suction cups and started spreading them apart at the very bottom (last two rows) a little more. There are still a little thin on this quick mockup. I think in your mockup they look perfect for the top 4 lines of cups and after this they should increase to keep the same look. Could you maybe try that. Of course only if you have the time :) After that I won't have anything more, I promise 😄 

![67093326-a8805980-f1b1-11e9-942b-0b145cc620b7](https://user-images.githubusercontent.com/19818061/67127207-29167880-f1f9-11e9-86f3-e5059aa52940.png)

**Comment by hessius** [comment]
Haha I have no problem with making more adjustments, keep em coming!

I kept them at the same distance but notched up the transparent border progressively.

![octodash-icon-17](https://user-images.githubusercontent.com/1499030/67140188-3d3d9280-f258-11e9-8091-77e72ff77af7.png)


The decision is yours of course, but while this looks good at full size, think about where and how you are going to display this, because in my mind the version with transparent rims does not work at smaller sizes. Here for example, I've just taken a screenshot of the thumbnails of the different versions:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/1499030/67140205-82fa5b00-f258-11e9-8730-58c251f48361.png">

Here it becomes obvious that if the icon is at any point going to be part of the UI many of the versions would be hard to read

**Comment by UnchartedBull** [comment]
Yeah I like that with the transparent border! The icon will be quite big if it is diplayed (either at startup or in the about section). But it will be probably good to  have a small icon  available for places where  the big ones does not fit.

It will be awesome if you could create a SVG from the last one and the same one, but without the transparent border.So I think  15 and 17 :D

If you export them:
- Could you please  do that without the name (so only the logo) with no background.
- Replace  the  white color with #f5f6fa, that would be great :)
- If it  isn't too much work  the one with  the suction cup borders  would be nice with the name as well.

Otherwise I'm super happy with the logo! Thank you so much!

**Comment by hessius** [comment]
Yeah no problem! 
What font did you use for the name?

Btw I couldn't resist trying a few more variations:
![octodash-icon-18](https://user-images.githubusercontent.com/1499030/67163740-dd87da00-f372-11e9-93cb-321ceac773a3.png)
![octodash-icon-19](https://user-images.githubusercontent.com/1499030/67163741-dd87da00-f372-11e9-9253-e8f16869626f.png)
![octodash-icon-20](https://user-images.githubusercontent.com/1499030/67163742-dd87da00-f372-11e9-8adf-a4a1bf035b02.png)

**Comment by UnchartedBull** [comment]
The Font is called Arvo: https://fonts.google.com/specimen/Arvo

They definitely look interesting, but I still like the one with the white suction cup and border more.

**Comment by hessius** [comment]
Before I finish the other two versions (i.e. this but with the title as well and the one without borders), just check that this look ok for you: https://codepen.io/hessius/pen/pooRYjO

(Just added a moving gradient background to see it against some different backgrounds)

After I get the green light I'll finish the other two, how do you want them delivered? (Github did not allow me to attach them here)

**Comment by UnchartedBull** [comment]
Yes that looks awesome! Thank you so much!

You can either send them to my mail (timon.gaebelein@icloud.com) or open a Pull Request (this way you‘ll get the credit you deserve). But that’s up to you :)

**Comment by hessius** [comment]
Submitted a PR, also updated the codepen for anyone curious, it now uses bg colours from the swatch you provided

**Comment by hessius** [comment]
Added dark icons to be used on light backgrounds and added the main icon with title to the readme, PR updated
