### ISSUE TITLE
error (undefined)

### ISSUE THREAD

**Issue by Epuerto96** [UnchartedBull/OctoDash#862]
**Describe the bug**
"error (undefined)" flashing on the bottom right corner and a constant error banners popping up.

**To Reproduce**
When going to settings>octodash>Custom Actions updating any values in Gcode/Action field and saving configuration octodash goes into an endless loop of error banners "Can't retrieve layer progress!","Can't retrieve printer status!", "Can't retrieve Jobs" every second.

Each banner shares the subtext "Failed to execute 'open' on 'XMLHttpRequest': Invalid URL"

Closing the banners results in a new banner appearing a second later

**General Information:**
 - Raspberry Pi 3 B+
 - OctoDash Version 1.5.0
 - OctoPrint Version 1.4.0

**Additional context**
I have tried uninstalling and reinstalling octodash along with deleting the octodash configuration file and redoing setup. Bug still occurs

**Comment by UnchartedBull** [comment]
Seems like your URL is invalid. Could you please post the URL from your config file here (or a screenshot from the settings menu?)
