### ISSUE TITLE
Any easy way to uninstall Octoprint-TFT to install this?

### ISSUE THREAD

**Issue by pilotw7** [UnchartedBull/OctoDash#887]
Is there an easy way to uninstall Octoprint-TFT and then install this instead without having to nuke my Raspberry Pi? If it helps the version of OctoPrint-TFT that I'm running is a "Fix-Jessie" one that someone put out to fix the freezing issue that Octoprint-TFT had regarding it displaying temperatures on the status page.

**Comment by Hypertoken** [comment]
Kinda the wrong place to ask, but; 
dpkg -r octoprint-tft

**Comment by UnchartedBull** [comment]
Thanks @Hypertoken.
