### ISSUE TITLE
Fan 'OFF' and '100%' buttons in Fan controlls

### ISSUE THREAD

**Issue by morphias2004** [UnchartedBull/OctoDash#898]
**Describe the solution you'd like**

Just one of those 'nice to have' things. No big deal.  😃 

It would be great to have an 'OFF' and a '100%'  button in the fan controls when you press on the Fan icon on the home screen.

Currently you have to spam the plus or minus button and then press SET.

Thank-you! 👍

**Comment by UnchartedBull** [comment]
You can just tap on the number to switch between 0 and 100% :) Or do you mean changing those values during print?
