### ISSUE TITLE
Restart octodash on octopi

### ISSUE THREAD

**Issue by steviehs** [UnchartedBull/OctoDash#899]
As I have not seen a way to contribute directly to the wiki, let me do it this way:

It may be helpful - in the time of installation and configuration - to restart octodash without rebooting the whole pi. 
As octodash is started via raspi-configs autostart option, it is easy to be done by restarting the suiting getty service (as root):

`service getty@tty1 stop`
`service getty@tty1 start`

Thanks for all your work on OctoDash it is now really in a state where you can operate your regular flow via it!

Cheers
 Steve

**Comment by UnchartedBull** [comment]
Thanks! Has been added to the wiki: https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings#restarting-octodash-without-restarting-the-raspberry-pi.

Great to hear, that it is now in a useable state for more people :)
