### ISSUE TITLE
Wrong filament used calculation?

### ISSUE THREAD

**Issue by Protoncek** [UnchartedBull/OctoDash#906]
I'm not sure if this is OctoDash's error, but i have "a problem": does anyone of you noticed: "filament used" is different on OctoDash than the one in PrusaSlicer. Example: a small hook, in Slicer says filament used 4,36g, while in OctoDash file info says 13.7g. Where to look for error?

Thanks!

**Comment by UnchartedBull** [comment]
That could very well be an OctoDash error. The filament calculation seems to be kind of flaky. I'll need to rewrite that part, will be included in one of the next versions.

**Comment by TacoScientist** [comment]
I'm having the same issue. Cura quotes at 19g, but display says 55.9g. Its pretty consistently off by a factor of just below 3.

**Comment by robwasteground** [comment]
Same issue here, Cura (and OctoPrint) show what seems to be correct length (5g, 1.72m), OctoDash shows 15.3g. It always seems to be off by a factor of somewhere around ~3 here as well.

**Comment by UnchartedBull** [comment]
Ok this was a really weird error. OctoPrint seems to be reporting the wrong filament volume (should be 2.5something in the screenshot), this then offsets OctoDash. Don't really know why the amount is still correct then. I'll revert back to calculate everything on my own from filament length, which should hopefully fix the problem.

![image](https://user-images.githubusercontent.com/19818061/96055240-ceebda00-0e83-11eb-8ad2-53a8e39c1e74.png)
