### ISSUE TITLE
Ubuntu Support

### ISSUE THREAD

**Issue by JNSmith1717** [UnchartedBull/OctoDash#910]
Anyway that this would work with Ubuntu Server 18.04 LTS?  I run Ocotprint off a old laptop board with Ubuntu Server 18.04 LTS and would like to have a 5in hdmi display connected directly to it.  Only other way is to use a Raspberrry pi zero to just have OctoDash on it  but i see that don't work either.

**Comment by dmiart** [comment]
I suspect you can just compile it on x86. 

https://github.com/UnchartedBull/OctoDash/blob/master/CONTRIBUTING.md

**Comment by UnchartedBull** [comment]
There is already an amd64 version attached to the releases, which should work with x86. You just need to adjust the installer script to point to the other archive / install manually. Let me know if this works.

**Comment by UnchartedBull** [comment]
Wrong button, sorry

**Comment by JNSmith1717** [comment]
Amd64 would work for me actullay how do I getbthis

**Comment by JNSmith1717** [comment]
Sorry kinda of new to using github

**Comment by UnchartedBull** [comment]
It's right at the bottom of the releases: https://github.com/UnchartedBull/OctoDash/releases/tag/v2.0.0 you can either click & download or execute `wget https://github.com/UnchartedBull/OctoDash/releases/download/v2.0.0/octodash_2.0.0_amd64.deb`, which will download the file. Can be installed with `sudo dpkg -i octodash_2.0.0_amd64.deb`
