### ISSUE TITLE
OctoDash won't connect to Octoprint, default/fresh installation.

### ISSUE THREAD

**Issue by Creat** [UnchartedBull/OctoDash#931]
**What doesn't work?**
OctoDash can't connect to Octoprint. Default installation, just updated but nothing actually modified.
All I see is "Octodash is sleeping". I can tap on it to try and connect, but it can't actually connect. Can't get to options either, since it's apparently sleeping pretty hard. Cross Site Scripting enabled.

**What did you already try?**
My installation was done like this (with frequent reboots duing the process):
- flash clean/fresh OctoPi image to sd. Configured config.txt for screen/resolution.
- Performed `apt full-upgrade` (as the image is quite old now).
- Opened/configured Octoprint (AccessControl is disabled), and installed any updates it had.
- Installed OctoDash via script, with autostart enabled and enabled auto-login to shell in raspi-config.
- Gui comes up, can go through first-run-wizard of OctoDash just fine (entered API-key for example)

Now we got the situation described above, sleepytime!

Tried other URLs via editing config (since I can't get to the options) and restarting OctoDash (port 5000, 80. localhost and 127.0.0.1). None worked. Seems port/URL is generally correct tho, since I get a response when using CURL on commandline on the same URL (like http://localhost:5000/api/login gives me a "405 not allowed", so someone's listening).

I noticed that the wiki entry [Setup & Settings](https://github.com/UnchartedBull/OctoDash/wiki/Setup-&-Settings) lists URL and port as separate entries. The default is just a URL containing the port, I assumed that's fine/correct.

**General Information:**
 - Hardware: Raspberry Pi 2B (just for testing right now, later will be 3B or 4B), 7inch IPS Touch display (touch and display work fine)
 - OS Info: OctoPi image 0.17.0, then updated (see above)
 - OctoDash Version: v2.0.0
 - OctoPrint Version: v1.4.2

**Additional context**
Can give any information you might want/need. Or video/pictures. Just let me know.
I'm kind of familiar with linux if that helps as basic information (I'm a programmer & admin in my dayjob), but far from an expert.

**Comment by TheSin-** [comment]
Try using :80 instead of :5000

**Comment by Creat** [comment]
As I already wrote, I already have. No change.

**Comment by TheSin-** [comment]
Sorry I see it now I missed it, that was the only issue I had.  I also don’t have authentication on might so not sure if that might be, and the fact that that octoprint takes forever to start up ;)

**Comment by Creat** [comment]
I did have it running for a looong time, and can access the web interface fine from another computer on the network. So it's deffinitely running and accepting requests...

**Comment by TheSin-** [comment]
that is very odd indeed.  Just curious (shouldn't matter) but when you setup octopi do you setup a user and password?  I just did a fresh install with your instructions and it all worked for me, but I select no username/password, just want to make sure I'm testing with the same setup.

Also do you have a printer setup?  if not please make sure to install the virtual printer plugin for octoprint and configure it.  Octodash won't work if there is no printer setup and connected.

**Comment by Creat** [comment]
I didn't setup a user, assuming you mean the "Access Control" that OctoPrint offers? That part is disabled, when I access the ip of the RasPI, I just see and can use OctoPrint.
Did you also `sudo apt update` and `sudo apt full-upgrade` before opening/setting up/updating OctoPrint itself? While I don't think that should matter, it might.

I did setup a printer (both in octoprint and in octodash), but it isn't connected at the moment. I can try again with a virtual printer, but since Octodash doesn't even connect I don't think that matters (yet). Once I get home, I'll give it a go tho.

**Comment by TheSin-** [comment]
yes though I do not use apt, but I used the same commands with apt-get.

That being said I'm 100% sure it's just cause your printer isn't accessible.  I'm working on trying to make the ui more usable one the printer isn't connected as it's something that has gotten me as well.

**Comment by UnchartedBull** [comment]
If it is sleeping that means everything is working just fine (most likely). Was your printer turned off / not connected in OctoPrint? If so please try turning on your printer & connecting it to OctoPrint.

**Comment by Creat** [comment]
Finally got a chance to test it, since had to move a bit of stuff around to get to a printer I could connect. Yes, it works! I did get a weird error message (http error 409 I think?), but that only happened once and seems fine now.

I'm just somewhat confused what happens now, when the Display is on, but printer off? As that's likely often the case for me. Will waking OctoDash (after turning on the printer) then implicitly connect Octoprint (with default settings)? Or do I have to go in with a browser, manually connect octoprint and then wake OctoDash?

And yes, it's not exactly clear that "sleeping" means the printer isn't connected.

**Comment by TheSin-** [comment]
don't worry we are working to correct that.  I use the PSU plugin so I'd like to be able to turn my printer off and on from the display so eventually....

for now to answer your question when you turn on your printer it'll just connect as it's now configured.

**Comment by UnchartedBull** [comment]
Great that it's working now! The 409 message is due to OctoPrint 1.4.2 still investigating this. If the PSU plugin is enabled tapping the screen while sleeping will turn on the PSU, wait a couple seconds and then connect to OctoPrint. Turning off can be done via a Custom Action.

Closing this here for now, if you have any more issues / questions feel free to open a new issue / comment here.
