### ISSUE TITLE
Add option to change filament roll selection when print is paused

### ISSUE THREAD

**Issue by zjsdlr2** [UnchartedBull/OctoDash#939]
**Is your feature request related to a problem? Please describe.**
Not a problem, feature request

**Describe the solution you'd like**
Add means to change the filament roll and/or execute filament change commands when print is paused.

**Additional context**
It would be useful if a filament roll change is needed to select new roll from pause screen to ensure proper filament quantities are removed from the correct rolls. Would also be useful to be able to back out old filament and load the new filament into the extruder.

**Comment by UnchartedBull** [comment]
Will be included together with another feature request to open the control screen from the pause menu. Might be a couple of releases down the line though.
