### ISSUE TITLE
Filament roll weights don't show on filament screen

### ISSUE THREAD

**Issue by zjsdlr2** [UnchartedBull/OctoDash#946]
**Describe the bug**
Filament roll weights do not show on the filament screen
Scroll bar is misaligned with it's background. 

**To Reproduce**
1. Install a clean version of Octopi
2. Install OctoDash from the script (following directions in the readme) having OctoDash install all supported plugins except for UtlimakerFormatPackage and PrusaSlicer Thumbnails. 
3. Enter a few test rolls in OctoPrint's filament manager plugin
4. Go to the filament screen

I did get this first without a clean system, but reinstalled everything to make sure it wasn't one of my settings. The issue persists through reboots.

**Expected behavior**
Expected to include roll weights as in screenshot in readme. While minor, scroll bar expected to be aligned.

**Screenshots**
![IMG_20200826_214400](https://user-images.githubusercontent.com/13398464/91374799-07a5f600-e7e7-11ea-8e81-5f134ce0fe8b.jpg)

**General Information:**
 - Hardware [Raspberry Pi 3b, 800x480 OSOYOO 5" DSI Screen]
 - OS Info [OctoPi 0.17.0 Raspbian distro]
 - OctoDash Version [2.0.0]
 - OctoPrint Version [1.4.2]

**Comment by UnchartedBull** [comment]
Already has been fixed (not released yet). Somehow missed that before the last release, will be shipped with 2.0.1.
