### ISSUE TITLE
Uninstall instructions - no desktop environement

### ISSUE THREAD

**Issue by msteele999** [UnchartedBull/OctoDash#956]
I recently installed OctoDash on my Intel Compute Stick running OctoPrint on Ubuntu 18.04 server - needless to say, I did not install a desktop environment and got it in my head that this was a web based Dashboard.

I'd like to cleanly remove everything from the install but I'm not sure where to start. 

Is there a clean linux command that will remove the plugin? 'apt list --installed' does not list octodash.

Thank you.

**Comment by UnchartedBull** [comment]
`wget -qO- https://github.com/UnchartedBull/OctoDash/raw/master/scripts/remove.sh | bash` should remove everything. Maybe delete the `~/.config/octodash` folder as well.

**Comment by ArrowRaider** [comment]
This did not remove it from automatically starting.

**Comment by ArrowRaider** [comment]
https://github.com/UnchartedBull/OctoDash/raw/master/scripts/remove.sh does not exist
