### ISSUE TITLE
Doesn't seem to be a good way to swap filament Mid-Print

### ISSUE THREAD

**Issue by KS-Husker** [UnchartedBull/OctoDash#967]
This is a seriously amazing piece of work. I've been waiting so long for something of this caliber to come to home 3D printers. Thank you for doing this!!

I have only found one thing I wish was implemented better, and that is filament changes when you run out mid-print.

I would like to be able to lower the bed, move the nozzle to a park position, have it cool down until I come and start the filament swap process.

Then start the filament swap process by heating up to a temp I pre-set in the settings, Retract or load the filament (I always just load more to prevent jamming issues), purge as long as I let it run until I click OK. Then Hit print resume and have it go back to work.

I have another expensive printer that works like this and it's beautiful. But I can't seem to make this Octodash work this way no matter what I try, including using the filament runout reloaded in octoprint and using the gcode inputs in octoprint. I have gotten it close, but I can't get the temperature to resume where it was prior to pausing, and it travels to and from the park location SUPER slow. AND I have to go and run all of this from my computer.

Maybe I'm missing something. But it looks like you have the filament swap implemented prior to running the print. If that can be used during a print that would be awesome. I can't figure out how to do that though.

**Comment by UnchartedBull** [comment]
Great that you're liking this. 👍 

Filament swap during printing will be tracked in #939. 
The parking of the head + cooldown and heating needs to be done via the OctoPrint pause / resume scripts though. Good starting points for those scripts are here: https://community.octoprint.org/t/writing-a-resume-gcode-script-using-last-temperature/774/2 and here: https://community.octoprint.org/t/my-pause-resume-scripts/3541. Feel free to post them here so I can include them in the wiki for other people :)
