### ISSUE TITLE
Text layout issue on printing screen

### ISSUE THREAD

**Issue by greendog99** [UnchartedBull/OctoDash#971]
**Describe the bug**
Status/progress text and icons are in wrong position on screen, resulting in overlapping and clipped text.

**Screenshots**
![IMG_2185](https://user-images.githubusercontent.com/30274/92135210-78957100-edd8-11ea-937b-63ad8168e38b.jpeg)

**General Information:**
- RPi 4 w/ OctoPi
- 800x480 touchscreen
- OctoDash v2.0.0 special version to fix touch/drag issue #838 

**Additional context**
Screen display was working properly in the past. May be related to #838 fix?

**Comment by greendog99** [comment]
Note: I've noticed that this only happens on some prints (so it may be unrelated to #838 after all). I'll try to narrow down the conditions where I see this happen...

**Comment by greendog99** [comment]
I've done some testing and this appears to be a text wrapping issue due to the font size. In the above photo, if I manually change the printer's temperature to 199 (instead of 200), the layout corrects itself, since "199ºC/199ºC" takes up less horizontal space than "200ºC/200ºC". Hope this helps!

**Comment by UnchartedBull** [comment]
That certainly doesn't look right. I'll have a look at that and check, whether I can reproduce it on my machine
