### ISSUE TITLE
Picam not recognized ? 

### ISSUE THREAD

**Issue by JPCossu** [UnchartedBull/OctoDash#978]
Hello everyone, I installed Octodash on my api 3b+ with a 5 inch Kuman lcd. Everything works fine except that I no longer have access to my picam? It seems that it is no longer recognized or powered? Any idea ?

**Comment by UnchartedBull** [comment]
Please try unplugging and plugging the camera back in (while powered off). Otherwise remove OctoDash (`wget -qO- https://github.com/UnchartedBull/OctoDash/raw/master/scripts/remove.sh | bash`) and check whether the PiCam is working again.
